### ISSUE TITLE
[BUG] Storage path template can turn from relative to absolute path

### ISSUE THREAD

**Issue by quantenmechaniker-b3rnd** [paperless-ngx/paperless-ngx#8091] opened 2024-10-28 20:38 UTC
### Description

Paperless will turn a relative storage path into an absolute path if you start your expression with a field that can yield NONE and you didn't write it with special care.

See webserver log below  "**Permission denied: '/2022'**": 
* with an unknown owner, `{{ owner_username }}` converted to ""
* Paperless now sees only [/{{ created_year }}](url) which it _can_ convert into a value --> "/2022"
... resolve remainder of storage path ...
* Paperless tries to write outside the _media_ folder and fails.

I could imagine that this could lead to document loss on a Docker image if the write succeeds somehow and ends up outside the defined volumes. On a bare metal install, this could overwrite other files.

You can avoid it if you write your storage path starting with '`./{{ owner_username }}/...`' but now this shows up in the UI like a klutz.

### Steps to reproduce

1. set `PAPERLESS_FILENAME_FORMAT: '{{ owner_username }}/{{ created_year }}/{{ correspondent }}/{{ document_type }}/{{ title }}'`
2. set `PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: true`
3. deactivate any workflows that may set an owner
2. import a document via the default consume folder

### Webserver logs

```bash
[2024-10-28 21:04:20,244] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...

[2024-10-28 21:04:31,173] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.19 savings: 16.1%

[2024-10-28 21:04:31,177] [INFO] [ocrmypdf._pipeline] Total file size ratio: 2.13 savings: 53.0%

[2024-10-28 21:04:31,194] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)

[2024-10-28 21:04:37,045] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2024-10-28 21:04:37,048] [DEBUG] [paperless.consumer] Generating thumbnail for paperless_s2d28102024-collated.pdf...

[2024-10-28 21:04:37,061] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-us440eer/archive.pdf[0] /tmp/paperless/paperless-us440eer/convert.webp

[2024-10-28 21:04:39,219] [INFO] [paperless.parsing] convert exited 0

[2024-10-28 21:04:40,769] [DEBUG] [paperless.consumer] Saving record to database

[2024-10-28 21:04:40,770] [DEBUG] [paperless.consumer] Creation date from parse_date: 2022-03-22 00:00:00+01:00

[2024-10-28 21:04:41,434] [INFO] [paperless.handlers] Assigning correspondent xxxxxxxxx to 2022-03-22 paperless_s2d28102024-collated

[2024-10-28 21:04:41,473] [INFO] [paperless.handlers] Assigning document type xxxxxxxxx to 2022-03-22 xxxxxxxxx paperless_s2d28102024-collated

[2024-10-28 21:04:41,772] [ERROR] [paperless.consumer] The following error occurred while storing document paperless_s2d28102024-collated.pdf after parsing: [Errno 13] Permission denied: '/2022'

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 565, in run

    create_source_path_directory(document.source_path)

  File "/usr/src/paperless/src/documents/file_handling.py", line 11, in create_source_path_directory

    os.makedirs(os.path.dirname(source_path), exist_ok=True)

  File "<frozen os>", line 215, in makedirs

  File "<frozen os>", line 215, in makedirs

  File "<frozen os>", line 225, in makedirs

PermissionError: [Errno 13] Permission denied: '/2022'

[2024-10-28 21:04:41,774] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-us440eer

[2024-10-28 21:04:41,778] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: paperless_s2d28102024-collated.pdf: The following error occurred while storing document paperless_s2d28102024-collated.pdf after parsing: [Errno 13] Permission denied: '/2022'

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/consumer.py", line 565, in run

    create_source_path_directory(document.source_path)

  File "/usr/src/paperless/src/documents/file_handling.py", line 11, in create_source_path_directory

    os.makedirs(os.path.dirname(source_path), exist_ok=True)

  File "<frozen os>", line 215, in makedirs

  File "<frozen os>", line 215, in makedirs

  File "<frozen os>", line 225, in makedirs

PermissionError: [Errno 13] Permission denied: '/2022'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/tasks.py", line 148, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 621, in run

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception

documents.consumer.ConsumerError: paperless_s2d28102024-collated.pdf: The following error occurred while storing document paperless_s2d28102024-collated.pdf after parsing: [Errno 13] Permission denied: '/2022'
```

### Paperless-ngx version

2.13

### Host OS

Linux-4.4.302+-x86_64-with-glibc2.36 (container running on Synology DSM 7.2.2))

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.0",
    "server_os": "Linux-4.4.302+-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 5901986357248,
        "available": 721619136512
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0027_mailaccount_expiration_mailaccount_account_type_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-28T21:04:41.752981+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-10-28T20:07:59.892454Z",
        "classifier_error": null
    }
}
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-10-28 20:42
Duplicate of #8063.  Please search

**Closed by stumpylog** 2024-10-28 20:42 UTC
Labels: bug, unconfirmed
