### ISSUE TITLE
paperless not able to download languages in docker compose environment

### ISSUE THREAD

**Issue by drivingmx** [paperless-ngx/paperless-ngx#2083] opened 2022-12-02 10:26 UTC
### Description

When starting the docker stack, paperless tries to download languages.
The container log shows, that it is not possible to resolve the source urls.

I noticed this behavior when updating to 1.10.0 because this prevents paperless from starting. 
Downgrade to 1.9.2 helps because paperless starts nevertheless.

### Steps to reproduce

every start of the docker compose stack

### Webserver logs

```bash
2022-12-02 11:09:38,500] [DEBUG] [paperless.management.consumer] Consumer exiting.

[2022-12-02 11:16:37,499] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/st bestätigt.pdf@SynoEAStream: Unknown file extension.

[2022-12-02 11:16:37,500] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume
```

### Browser logs

```bash
Container Log

Paperless-ngx docker container starting...


Installing languages...


Err:1 http://deb.debian.org/debian bullseye InRelease


  Temporary failure resolving 'deb.debian.org'


Err:2 http://deb.debian.org/debian-security bullseye-security InRelease


  Temporary failure resolving 'deb.debian.org'


Err:3 http://deb.debian.org/debian bullseye-updates InRelease


  Temporary failure resolving 'deb.debian.org'


Reading package lists...


W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'


W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'deb.debian.org'


W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'


W: Some index files failed to download. They have been ignored, or old ones used instead.


Package tesseract-ocr-deu already installed!


Mapping UID and GID for paperless:paperless to 1026:100


Creating directory /tmp/paperless


Adjusting permissions of paperless files. This may take a while.


Waiting for PostgreSQL to start...


Waiting for Redis...


nnected to Redis broker.


Apply database migrations...


Operations to perform:


  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions


Running migrations:


  No migrations to apply.


Executing /usr/local/bin/paperless_cmd.sh


2022-12-02 10:16:34,745 INFO Set uid to user 0 succeeded


2022-12-02 10:16:34,753 INFO supervisord started with pid 1


2022-12-02 10:16:35,755 INFO spawned: 'consumer' with pid 80


2022-12-02 10:16:35,758 INFO spawned: 'gunicorn' with pid 81


2022-12-02 10:16:35,760 INFO spawned: 'scheduler' with pid 82


2022-12-02 10:16:36,761 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)


2022-12-02 10:16:36,761 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)


2022-12-02 10:16:36,761 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)


[2022-12-02 11:16:37,499] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/@eaDir/steinbach bestätigt.pdf@SynoEAStream: Unknown file extension.


[2022-12-02 11:16:37,500] [INFO] [paperless.management.consumer] Polling directory for changes: /usr/src/paperless/consume


11:16:37 [Q] INFO Q Cluster low-north-asparagus-green starting.


11:16:37 [Q] INFO Process-1:1 ready for work at 104


11:16:37 [Q] INFO Process-1:2 ready for work at 105


11:16:37 [Q] INFO Process-1:3 monitoring at 106


11:16:37 [Q] INFO Process-1 guarding cluster low-north-asparagus-green


11:16:37 [Q] INFO Q Cluster low-north-asparagus-green running.


11:16:37 [Q] INFO Process-1:4 pushing tasks at 107


[2022-12-02 11:16:37 +0100] [81] [INFO] Starting gunicorn 20.1.0


[2022-12-02 11:16:37 +0100] [81] [INFO] Listening at: http://[::]:8000 (81)


[2022-12-02 11:16:37 +0100] [81] [INFO] Using worker: paperless.workers.ConfigurableWorker


[2022-12-02 11:16:37 +0100] [81] [INFO] Server is ready. Spawning workers
```

### Paperless-ngx version

1.9.2

### Host OS

Synology DSM 7.1

### Installation method

Docker - official image

### Browser

firefox, chrome

### Configuration changes

version: "3.4" services:   broker:     image: docker.io/library/redis:7     restart: unless-stopped     volumes:       - /volume1/docker/paperless/redisdata:/data #    networks: #      - no-internet    db:     image: docker.io/library/postgres:13     restart: unless-stopped     volumes:       - pgdata:/var/lib/postgresql/data     environment:       POSTGRES_DB: paperless       POSTGRES_USER: paperless       POSTGRES_PASSWORD: paperless #    networks: #      - no-internet    webserver:       image: ghcr.io/paperless-ngx/paperless-ngx:1.9.2     restart: unless-stopped     depends_on:       - db       - broker       - gotenberg       - tika     ports:       - 8931:8000     healthcheck:       test: ["CMD", "curl", "-f", "http://localhost:8000"]       interval: 30s       timeout: 10s       retries: 5     volumes:       - /volume1/docker/paperless/data:/usr/src/paperless/data       - /volume1/homes/lalala/Drive/Documents/00_Ablage_Paperless:/usr/src/paperless/media       - /volume1/_intern/paperless_export:/usr/src/paperless/export       - /volume1/scanner/lalala_IN/scan_in:/usr/src/paperless/consume     env_file: docker-compose.env     environment:       PAPERLESS_REDIS: redis://broker:6379       PAPERLESS_DBHOST: db       PAPERLESS_TIKA_ENABLED: 1       PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000       PAPERLESS_TIKA_ENDPOINT: http://tika:9998 #    networks: #      - internet #      - no-internet         gotenberg:     image: docker.io/gotenberg/gotenberg:7.6     restart: unless-stopped     command:       - "gotenberg"       - "--chromium-disable-routes=true" #    networks: #      - no-internet    tika:     image: ghcr.io/paperless-ngx/tika:latest     restart: unless-stopped #    networks: #      - no-internet  volumes:   data:   media:   pgdata:   redisdata:    #networks: #  no-internet: #    driver: bridge #    internal: true #  internet: #    driver: bridge

**Comment by drivingmx** [comment] 2022-12-02 10:26
Here the yml again with better format

version: "3.4"
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - /volume1/docker/paperless/redisdata:/data
#    networks:
#      - no-internet

  db:
    image: docker.io/library/postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
#    networks:
#      - no-internet

  webserver:  
    image: ghcr.io/paperless-ngx/paperless-ngx:1.9.2
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - 8931:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /volume1/docker/paperless/data:/usr/src/paperless/data
      - /volume1/homes/lalala/Drive/Documents/00_Ablage_Paperless:/usr/src/paperless/media
      - /volume1/_intern/paperless_export:/usr/src/paperless/export
      - /volume1/scanner/lalala_IN/scan_in:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
#    networks:
#      - internet
#      - no-internet
    

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.6
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
#    networks:
#      - no-internet

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
#    networks:
#      - no-internet

volumes:
  data:
  media:
  pgdata:
  redisdata:



#networks:
#  no-internet:
#    driver: bridge
#    internal: true
#  internet:
#    driver: bridge

**Comment by shamoon** [comment] 2022-12-02 10:53
I believe this is basically a dupe of #2061 

The logs imply it’s blocked from the internet, correcting that should solve it.

**Closed by shamoon** 2022-12-02 10:53 UTC
Labels: bug, unconfirmed
