### ISSUE TITLE
[Enhancement] Split docker image build into base image and application image

### ISSUE THREAD

**Issue by schnuffle** [paperless-ngx/paperless-ngx#222] opened 2022-03-06 16:03 UTC
For the moment, the job build-docker-image in ci.yml takes some hours. 
### The reason:
- The whole container is rebuild everytime it runs
- The 2 components jbig2enc and pikepdf ( only arm ) get rebuild for every new build, though there're no changes

### A possible Solution:
Seperate the docker build into 2 stages:
- Build the base image with all deps only when there has been changes
- Base the final image on the base image

I've started a POC in my fork and will report if there's any progress

Regards

Schnuffle

**Comment by schnuffle** [comment] 2022-03-06 21:53
I started with some test and had another idea. For now I have defined 3 workflows:

1. Build a nodejs base image, that should be triggered on changing files package.json and package-json.lock
2. Build a ngx base image, that should be triggered on any python dep changes
3. Build the ngx image using thise two others

I need to sort out how exactly the directive works and if I can it combine with tags:


```
on:
  push:
    tags: 
      - ngx-base-nodejs*
    paths:
      - 'example.c'
    branches-ignore:
      - 'translations**'
```

**Comment by schnuffle** [comment] 2022-03-07 17:37
After some more tests, I've adopted the workflow again:

1. Build a ngx base image, that should be triggered on any python dep changes
2. Use action/setup-node to compile frontend on the VM, not in docker
3. Build the ngx image referencing the base image and copy the compiled assets from the VM

**Comment by schnuffle** [comment] 2022-03-07 19:40
I've finally resolved the last problems and have  fully runing workflows

###  [docker-baseimage-ngx](https://github.com/schnuffle/paperless-ngx/blob/feature-split-dockerimage/.github/workflows/dockerimage-base-ngx.yml)

- Multiarch
- Creates base image: 
-- includes all the python dependencies
-- Install build packages and runtime packages
-- Removes build packages
-- Cleanup
-- Pushes to ghcr.io registry
-- Gets triggered by pushing a tag  ngx-baseX.X.X  on branch feature-split-dockerimage

###  [build-project](https://github.com/schnuffle/paperless-ngx/blob/feature-split-dockerimage/.github/workflows/build-project.yml)
- Starts frontend build on runner directly using action/setup-node
- Creates Multiarch docker image
- Docker image:
-- Copies ng assets from runner
-- References base image
-- Pushes to registry
-- Gets triggered when a tag ngx-projectX.X.X is pushed into btanch feature-split-dockerimage

Now I would like to have some advice howto integrate those changes into paperless-ngx repo.

Regards

Schnuffle

**Comment by stumpylog** [comment] 2022-03-11 23:35
I think the psycopg2 package which could benefit from being built against the source as well.  I'm not positive I'm right yet, but I think the cause of #266 is due to the `psycopg2-binary` not working for aarch64.

**Comment by schnuffle** [comment] 2022-03-14 11:48
Yeah,
we could integrate that.
I had some dependency problems missing some libs, so right now I'm adopting hte cleanest way to get qpdf/pikepdf installed, I'm creating a backport from debian testing, which has the needed version
Advantage is that I get all the debian package tests for free.

It's possible because there're very few dependencies, so I need to only backport qpdf and pike pdf.

For psycopg2, I'll need to have a look at.

Regards

Schnuffle

**Comment by shamoon** [comment] 2022-04-08 23:14
Closed by https://github.com/paperless-ngx/paperless-ngx/commit/9737e4a24d9bd2378204fd67e3458e543fe3ed1c 🎉

**Closed by shamoon** 2022-04-08 23:14 UTC
Labels: enhancement, backend, ci-cd
