### ISSUE TITLE
[BUG] After Update to 1.16.0 webserver thread crashes with RuntimeError

### ISSUE THREAD

**Issue by tom666-debug** [paperless-ngx/paperless-ngx#3611] opened 2023-06-17 07:52 UTC
### Description

Webserver thread crashes and hangs in a restart loop right after the update to version 1.16.0
Behavior is still unchanged with version 1.16.1.

Seems to be related to this bug (but on platform amd64) -> https://github.com/paperless-ngx/paperless-ngx/issues/3596
My comments there were marked as "off-topic" - Dont know why ...

### Steps to reproduce

1. docker-compose down
2. docker-compose up -d (latest paperless image was pulled)
3. check log

### Webserver logs

```bash
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 386, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 92, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 79, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.9/site-packages/django/conf/__init__.py", line 190, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/settings.py", line 605, in <module>
    setup_logging_queues()
  File "/usr/local/lib/python3.9/site-packages/concurrent_log_handler/queue.py", line 108, in setup_logging_queues
    listener.start()
  File "/usr/local/lib/python3.9/logging/handlers.py", line 1497, in start
    t.start()
  File "/usr/local/lib/python3.9/threading.py", line 899, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
```

### Paperless-ngx version

1.16.0

### Host OS

Linux amd64

### Installation method

Docker - official image

### Browser

Chrome, Edge, Firefox

### Configuration changes

none

**Comment by thorrrr** [comment] 2023-06-17 11:00
The fix has not worked for my setup in fact it has stopped me getting any access now!
I was able to restart the container before and fix it but now mine is no longer starting

**Comment by shamoon** [comment] 2023-06-17 14:06
They were marked off-topic because the cause is completely different. As noted there, this is likely https://github.com/docker-library/python/issues/835 which doesn’t appear to have a fix yet. Id suggest leaving paperless-ngx at an older version in the meantime

**Comment by thorrrr** [comment] 2023-06-17 17:54
How do I roll back ?

**Comment by tooomm** [comment] 2023-06-17 19:58
> How do I roll back ?

Change paperless-ngx:latest to the specific version, e.g. paperless-ngx:1.5 in your Docker file. 

Make sure to revert it to latest for auto updates, or pick newer versions as required once a fix for your issue is available.

**Comment by thorrrr** [comment] 2023-06-17 21:07
Hi 
I have tried 3 times keeps failing to roll back

**Comment by stumpylog** [comment] 2023-06-17 22:55
"it's failing" is never very helpful.  What is the error message when you update after setting the new version tag?  Is it a Docker error? Paperless?

**Comment by masta-bhawk** [comment] 2023-06-20 12:31
I also have the same problem exactly as described above.  Rollback to 1.15 resolved the issue for now.   It may be worth noting that I also had to rollback Redis to 7.0.10 prior to getting this error, since webserver couldn't connect to broker.  Presumably that issue is related to what was mentioned here:  https://discuss.circleci.com/t/redis-fatal-cant-initialize-background-jobs/48376/6

**Comment by shamoon** [comment] 2023-06-20 22:57
Can anyone experience this state explicitly what OS they’re running? Linked issue seems to suggest this is a backwards compatibility issue and since this relates to the base image of paperless we will ultimately be limited in what we can do about it:

1. Revert the base image upgrade. Seems short-sighted and the pros of the upgrade for the plurality of users likely outweigh the downsides for the minority experiencing this.
2. Users experiencing this either upgrade their OS, the relevant libraries (on the host) or remain on 1.15.x indefinitely (or until there is an upstream solution).

Of course, welcome any other thoughts.

**Comment by masta-bhawk** [comment] 2023-06-21 03:02
I am running in a docker container on Ubuntu 20 LTS, but I just upgraded  to 22.04.2 LTS and still see the same above error when using webserver:latest.  It works just fine at 1.15.

**Comment by shamoon** [comment] 2023-06-21 03:21
Thanks.

Please see: https://github.com/docker-library/python/issues/837#issuecomment-1599640563

**Comment by tom666-debug** [comment] 2023-06-21 06:16
I have just added this to my docker-compose.yml (webserver part) as a temporary fix:
    security_opt:
      - seccomp:unconfined
    
Not nice but now the latest version 1.16.2 is running on my system.

**Comment by stumpylog** [comment] 2023-06-22 15:21
That confirms it is the linked issue.  You would want to either update your libsecomp and/or Docker, based on the comments of the linked issue.  If you've installed Docker via your system packages, maybe consider installing it via their own package repository as well, for a more updated version

**Comment by tom666-debug** [comment] 2023-06-22 15:40
thx for your reply.
Updating libsecomp and/or Docker is not an option as I run Paperless currently on [UCS](https://www.univention.de/produkte/ucs/). The Docker environment and all packages are maintained by the UCS developer. Guess I will move Paperless to another VM in order to get rid of this dependancies.

**Comment by shamoon** [comment] 2023-06-22 15:40
I’m going to close this here, users with this problem should track the upstream issue for a fix / workarounds

**Closed by shamoon** 2023-06-22 15:40 UTC
Labels: dependencies

**Comment by stumpylog** [comment] 2023-06-23 21:23
If you're on a recent version of your OS, such as 22.04, gathering [the information from here](https://github.com/docker-library/python/issues/835#issuecomment-1601702601) may help confirm it's seccomp related or not.
