### ISSUE TITLE
[BUG] Skipping attachment  with content disposition

### ISSUE THREAD

**Issue by nodecentral** [paperless-ngx/paperless-ngx#1931] opened 2022-11-05 20:29 UTC
### Description

Hi, I’m trying to see if I can pull in files from my mail box, using a email rule (via admin for my gmail account) but its not working very well, and I’m seeing a lot of the following messages in the mail.log
````
[2022-11-05 20:11:22,033] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Processing mail Business & Technology and others share their thoughts on
 LinkedIn from updates-noreply@linkedin.com with 2 attachment(s)
[2022-11-05 20:11:22,035] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,036] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,162] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Processing mail 9 new jobs for 'security' from jobalerts-noreply@linkedin.com with 2 attachment(s)
[2022-11-05 20:11:22,165] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,166] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
````
There seems to be a double space between the word `attachment` and `with` which suggests that might be a placeholder for key piece of information ?

Found a very similar bug reported via paperless-ng -> https://github.com/paperless-ngx/paperless-ngx/issues/865  and https://github.com/jonaswinkler/paperless-ng/issues/1088#issuecomment-868535481 which I’m investigating, but wanted to raise this even if it’s related the logging is not surfacing the specific error in the log file.. ?

### Steps to reproduce

Use gmail as a mail filter, and look for attachments 

### Webserver logs

```bash
[2022-11-05 20:11:22,033] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Processing mail Business & Technology and others share their thoughts on
 LinkedIn from updates-noreply@linkedin.com with 2 attachment(s)
[2022-11-05 20:11:22,035] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,036] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,162] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Processing mail 9 new jobs for 'security' from jobalerts-noreply@linkedin.com with 2 attachment(s)
[2022-11-05 20:11:22,165] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,166] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
```

### Paperless-ngx version

1.9.2

### Host OS

QNAP Linux

### Installation method

Docker - official image

### Browser

Safari iOS

**Comment by shamoon** [comment] 2022-11-05 20:42
I think this is a duplicate of https://github.com/paperless-ngx/paperless-ngx/issues/865

**Closed by shamoon** 2022-11-05 20:42 UTC
Labels: bug, unconfirmed

**Comment by nodecentral** [comment] 2022-11-05 20:48
Hi @shamoon , I think so too, which is why I made sure to add that ticket ref into my submission too

If thats the case, then this bug report should still remain open as it relates to something being broken in the logging ..

It’s reporting these types of errors as this
````
[2022-11-05 20:11:22,165] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,166] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
````
When it seems it should be reporting the log entry like this..
````
[2022-11-05 20:11:22,165] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
[2022-11-05 20:11:22,166] [DEBUG] [paperless_mail] Rule myemailaddress@gmail.com.Gmails with attachments: Skipping attachment  with content disposition
````

**Comment by shamoon** [comment] 2022-11-05 20:50
I think that's just because they're inline. That thread has a solution

**Comment by nodecentral** [comment] 2022-11-05 20:51
It’s does, sorry @shamoon - if we’re missing each other - is my comment about the missed values in the log entry not an issue then ?

**Comment by shamoon** [comment] 2022-11-05 21:28
Seems like a bit of a non-issue to me, but as I said I think it’s because they’re inline.
