### ISSUE TITLE
[BUG] Consumption of PDF says its a Decompression Bomb DOS attack (example file given)

### ISSUE THREAD

**Issue by github-cli** [paperless-ngx/paperless-ngx#709] opened 2022-04-12 19:40 UTC
### Description

If the following pdf is added, it tries to ocr it for quite a while (because of its size) and eventually fails
https://zg.lehrplan.ch/container/ZG_DE_Gesamtausgabe.pdf

ZG_DE_Gesamtausgabe.pdf
DecompressionBombError: Image size (704759433 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.

### Expected behavior

no errors so the pdf gets added or at least use a fallback to not use "redo" but instead use the text already provided in the pdf
I use "redo" because my scanner does the OCR shitty but some documents are not from my scanner but official documents like this instead where there is a "perfect" OCR already.

as this issue seems to be a problem with OCRmypdf, maybe being able to increase the mentioned size would "solve" it?

### Steps to reproduce

1.) add provided file 2.) wait... 3.) check logs for the error

### Webserver logs

```bash
[2022-04-12 21:05:36,698] [DEBUG] [paperless.consumer] Parsing Lehrplan21-ZG_DE_Gesamtausgabe.pdf...

[2022-04-12 21:06:43,765] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/src/../consume/+Scans/+Name/Offizielle Schuldokumente/Lehrplan21-ZG_DE_Gesamtausgabe.pdf

[2022-04-12 21:06:43,877] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': '/usr/src/paperless/src/../consume/+Scans/+Name/Offizielle Schuldokumente/Lehrplan21-ZG_DE_Gesamtausgabe.pdf', 'output_file': '/tmp/paperless/paperless-7thyyq1x/archive.pdf', 'use_threads': True, 'jobs': 4, 'language': 'deu+eng+por', 'output_type': 'pdfa', 'progress_bar': False, 'redo_ocr': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': '/tmp/paperless/paperless-7thyyq1x/sidecar.txt'}

[2022-04-12 21:31:42,433] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-7thyyq1x

[2022-04-12 21:31:42,439] [ERROR] [paperless.consumer] Error while consuming document Lehrplan21-ZG_DE_Gesamtausgabe.pdf: DecompressionBombError: Image size (704759433 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 249, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 337, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 385, in run_pipeline

    exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 274, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 82, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 135, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 187, in exec_page_sync

    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 337, in rasterize_preview

    page_context.plugin_manager.hook.rasterize_pdf_page(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__

    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall

    return outcome.get_result()

  File "/usr/local/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result

    raise ex[1].with_traceback(ex[2])

  File "/usr/local/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall

    res = hook_impl.function(*args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/ghostscript.py", line 68, in rasterize_pdf_page

    ghostscript.rasterize_pdf(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/ghostscript.py", line 129, in rasterize_pdf

    with Image.open(BytesIO(p.stdout)) as im:

  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2994, in open

    im = _open_core(fp, filename, prefix, formats)

  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2981, in _open_core

    _decompression_bomb_check(im.size)

  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 2890, in _decompression_bomb_check

    raise DecompressionBombError(

PIL.Image.DecompressionBombError: Image size (704759433 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/consumer.py", line 245, in try_consume_file

    document_parser.parse(self.path, mime_type, self.filename)

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 301, in parse

    raise ParseError(f"{e.__class__.__name__}: {str(e)}")

documents.parsers.ParseError: DecompressionBombError: Image size (704759433 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.
```

### Paperless-ngx version

1.6.0

### Host OS

Ubuntu 20.04

### Installation method

Docker

### Browser

Chrome

**Comment by qcasey** [comment] 2022-04-12 19:45
Duplicate of #416. Is this possibly a document you can share with us?

**Closed by qcasey** 2022-04-12 19:45 UTC
Labels: bug, unconfirmed

**Comment by github-cli** [comment] 2022-04-12 20:02
awesome, yes luckily its a public document :)
PS: maybe a fallback to not "redo" in case there is text already present would help or should I post this as a separate feature request?

**Comment by qcasey** [comment] 2022-04-12 21:07
> PS: maybe a fallback to not "redo" in case there is text already present would help or should I post this as a separate feature request?

I don't know the answer to that, someone on the backend team would. A separate discussion would be good if you're wanting the answer.
