### ISSUE TITLE
[BUG] Sorting document list based on "created date" using date format dd-mm-yyyy (Medium German Date Display)

### ISSUE THREAD

**Issue by mjrcrm** [paperless-ngx/paperless-ngx#6330] opened 2024-04-08 10:28 UTC
### Description

Sorting document list based on "created date" using date format dd-mm-yyyy (Medium German Date Display) does not correctly sort the list. Screenshot attached. Switching to ISO format solves the problem.

![Screenshot 2024-04-08 120844](https://github.com/paperless-ngx/paperless-ngx/assets/25005071/cae1ad73-633b-4a0c-b19f-64ffcb79911b)

### Steps to reproduce

1. Set user preferences to German data format dd-mm-yyyy.
2. Sort a document list by created date.
3. The sort is not correct. Sorting by data by added date produces proper results.

### Webserver logs

```bash
Log does not provide any information regarding the sort.
```

### Paperless-ngx version

2.7.2

### Host OS

Synology Diskstation DSM 7.x

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

none

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by mjrcrm** [comment] 2024-04-08 10:40
Correction - ISO date format also does not sort a document list by created date correctly.

**Comment by shamoon** [comment] 2024-04-08 14:26
Sine nothing has changed with respect to sorting I'd be very surprised if it was suddenly broken. Indeed I cant reproduce this with the instructions above (see attached).

Sorting triggers the API (/api/documents/?ordering=created&page=1...) so it does not matter what format you use for the date.

You havent provided much detail, but if the view above includes a query you may need to run the [document indexer](https://docs.paperless-ngx.com/administration/#index)

Feel free to update this issue with your findings, we can always re-address, closing for now.

**Closed by shamoon** 2024-04-08 14:26 UTC
Labels: not a bug
