### ISSUE TITLE
[BUG] Created and Added Filters in Document list don't work

### ISSUE THREAD

**Issue by pippep** [paperless-ngx/paperless-ngx#2512] opened 2023-01-25 19:45 UTC
### Description

In the document list, if I use a "Created" or "Added" filter, and I select "Last 7 days", "Last month", "Last 3 months" or "Last year", I get an error "Error while loading documents: 'DateRange' object has no attribute 'subqueries'".
The filters are working fine if I use "After" and "Before".
![Screenshot paperless-ngx error](https://user-images.githubusercontent.com/29330516/214671047-1eb9e20b-558e-4cdb-b26c-9c2b7b252381.png)

### Steps to reproduce

1. Go to "Documents"
2. Click on Created or Added
3. Click on Last 7 days, or Last month, or Last 3 months, or Last year

### Webserver logs

```bash
-
```

### Paperless-ngx version

1.12.0

### Host OS

Archlinux

### Installation method

Other (please describe above)

### Browser

Firefox

### Other

Installation method: AUR package https://aur.archlinux.org/packages/paperless-ngx

**Comment by shamoon** [comment] 2023-01-25 19:47
Duplicate of #2508 #2510

**Closed by shamoon** 2023-01-25 19:47 UTC
Labels: bug, unconfirmed
