### ISSUE TITLE
[BUG] Error in log when consuming from folder

### ISSUE THREAD

**Issue by pnwbob** [paperless-ngx/paperless-ngx#4290] opened 2023-09-28 19:55 UTC
### Description

The application works, but is not updating the queues in the File Tasks area. Documents don't appear in the Failed, Complete, Started, or Queued lists.

### Steps to reproduce

Setup a docker container using the attached files
[paperlessngx.zip](https://github.com/paperless-ngx/paperless-ngx/files/12753419/paperlessngx.zip)

Place any file in the consume folder and watch the logs

### Webserver logs

```bash
[2023-09-28 12:31:59,160] [DEBUG] [paperless.management.consumer] Waiting for file /usr/src/paperless/consume/kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf to remain unmodified

[2023-09-28 12:32:04,169] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf to the task queue.

[2023-09-28 12:32:04,184] [ERROR] [paperless.handlers] Creating PaperlessTask failed

Traceback (most recent call last):

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute

    res = self._query(mogrified_query)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query

    db.query(q)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query

    _mysql.connection.query(self, query)

MySQLdb.OperationalError: (2006, 'Server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/src/paperless/src/documents/signals/handlers.py", line 537, in before_task_publish_handler

    PaperlessTask.objects.create(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 671, in create

    obj.save(force_insert=True, using=self.db)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 812, in save

    self.save_base(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 863, in save_base

    updated = self._save_table(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1006, in _save_table

    results = self._do_insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 1047, in _do_insert

    return manager._insert(

  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1791, in _insert

    return query.get_compiler(using=using).execute_sql(returning_fields)

  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1660, in execute_sql

    cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute

    return self.cursor.execute(sql, params)

  File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 75, in execute

    return self.cursor.execute(query, args)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 179, in execute

    res = self._query(mogrified_query)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/cursors.py", line 330, in _query

    db.query(q)

  File "/usr/local/lib/python3.9/site-packages/MySQLdb/connections.py", line 255, in query

    _mysql.connection.query(self, query)

django.db.utils.OperationalError: (2006, 'Server has gone away')

[2023-09-28 12:32:04,318] [INFO] [paperless.consumer] Consuming kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf

[2023-09-28 12:32:04,322] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-09-28 12:32:04,324] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-09-28 12:32:04,327] [DEBUG] [paperless.consumer] Parsing kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf...

[2023-09-28 12:32:04,554] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxrkku8ybe/kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-bes_vt6g/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-bes_vt6g/sidecar.txt')}

[2023-09-28 12:32:07,564] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2023-09-28 12:32:08,605] [DEBUG] [paperless.consumer] Generating thumbnail for kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf...

[2023-09-28 12:32:08,609] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-bes_vt6g/archive.pdf[0] /tmp/paperless/paperless-bes_vt6g/convert.webp

[2023-09-28 12:32:12,878] [DEBUG] [paperless.consumer] Saving record to database

[2023-09-28 12:32:12,879] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2021-02-20 13:39:37.817029-08:00

[2023-09-28 12:32:13,221] [INFO] [paperless.handlers] Assigning correspondent City of Kirkland to 2021-02-20 kitchenaid blender KSB5GR3 owners-manual-9704205-RevB

[2023-09-28 12:32:13,401] [INFO] [paperless.handlers] Assigning document type informational to 2021-02-20 City of Kirkland kitchenaid blender KSB5GR3 owners-manual-9704205-RevB

[2023-09-28 12:32:13,581] [INFO] [paperless.handlers] Tagging "2021-02-20 City of Kirkland kitchenaid blender KSB5GR3 owners-manual-9704205-RevB" with "Bob"

[2023-09-28 12:32:13,783] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxrkku8ybe/kitchenaid blender KSB5GR3 owners-manual-9704205-RevB.pdf

[2023-09-28 12:32:13,828] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-bes_vt6g

[2023-09-28 12:32:13,829] [INFO] [paperless.consumer] Document 2021-02-20 City of Kirkland kitchenaid blender KSB5GR3 owners-manual-9704205-RevB consumption finished

[2023-09-28 12:35:28,863] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}numPages: 50. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,864] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}extracted: 2016-11-10T09:49:44.317-05:00. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,865] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}Producer: Acrobat Distiller 5.0.5 for Macintosh. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,866] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}Author: WST24. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,866] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}sha1: b6c57a252b0ab3e2f0522157baabb17cb6c2d2a0. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,867] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}size: 802360. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,868] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}category: category:portables. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,868] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}rev: b. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,869] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}imageType: asset-type:owners-manual. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,869] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}litPartNumber: 9704205. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,870] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}modelNumber: ksb5pk4,ksb5my4,ksb5ac4,ksb5bk3,ksb5bk4,ksbs5wh3,ksb5ww4,ksb5ww3,ksb5wh4,ksb5wh3,ksb5tg4,ksb5ob4,ksb5ob3,ksb5nk4,ksb5nk3,ksb5ac3,ksb5my3,ksb5mc4,ksb5gt3,ksb5gr4,ksb5gr3,ksb5gn4,ksb5gn3,ksb5er4,ksb5er3,ksb5cr4,ksb5cr3,ksb5cp4,ksb5cp3,ksb5bu4,ksb5bu3. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,876] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}brand: {'brand:kitchenaid'}. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,928] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}numPages: 50. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,931] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}extracted: 2016-11-10T09:49:44.317-05:00. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,934] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}Producer: Acrobat Distiller 5.0.5 for Macintosh. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,935] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}Author: WST24. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,935] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}sha1: b6c57a252b0ab3e2f0522157baabb17cb6c2d2a0. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,936] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://www.day.com/dam/1.0}size: 802360. Error: 'http://www.day.com/dam/1.0'

[2023-09-28 12:35:28,936] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}category: category:portables. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,936] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}rev: b. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,937] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}imageType: asset-type:owners-manual. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,937] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}litPartNumber: 9704205. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,938] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}modelNumber: ksb5pk4,ksb5my4,ksb5ac4,ksb5bk3,ksb5bk4,ksbs5wh3,ksb5ww4,ksb5ww3,ksb5wh4,ksb5wh3,ksb5tg4,ksb5ob4,ksb5ob3,ksb5nk4,ksb5nk3,ksb5ac3,ksb5my3,ksb5mc4,ksb5gt3,ksb5gr4,ksb5gr3,ksb5gn4,ksb5gn3,ksb5er4,ksb5er3,ksb5cr4,ksb5cr3,ksb5cp4,ksb5cp3,ksb5bu4,ksb5bu3. Error: 'http://ns.whirlpool.com/wp/1.0/'

[2023-09-28 12:35:28,938] [WARNING] [paperless.parsing.tesseract] Error while reading metadata {http://ns.whirlpool.com/wp/1.0/}brand: {'brand:kitchenaid'}. Error: 'http://ns.whirlpool.com/wp/1.0/'
```

### Paperless-ngx version

1.17.4

### Host OS

Ubuntu 22.04.3 LTS

### Installation method

Other (please describe above)

### Browser

Firefox

**Comment by stumpylog** [comment] 2023-09-28 21:59
Duplicate of #4262, #1783 and #3077.  Please search before opening an issue.

**Closed by stumpylog** 2023-09-28 21:59 UTC
Labels: duplicate

**Comment by pnwbob** [comment] 2023-09-28 22:19
It is looking like this just may be the difference if you use polling instead of inotify in the consume folder. I setup a test server making everything the same except not using polling and then it worked as expected.

Removing this made this line from my environment made the difference:

PAPERLESS_CONSUMER_POLLING=20

**Comment by pnwbob** [comment] 2023-09-29 01:19
After looking into it again it wasn't the polling issue. I'm using a reverse proxy to give the paperless-ngx install a better url. Using the reverse proxied name in the environment file caused the issue. If I replaced https://my.fake.server.name with http://actual.server.name:8000 the notifications worked

**Comment by pnwbob** [comment] 2023-09-29 01:33
For clarity the variable being set was `PAPERLESS_URL`

**Comment by pnwbob** [comment] 2023-09-29 01:40
After allowing web sockets with Nginx Proxy Manager I was able to get everything to work with the custom url. This bug can be closed.
