### ISSUE TITLE
[BUG] copy text from PDF files includes extra space characters and/or non visible special characters

### ISSUE THREAD

**Issue by Profex** [paperless-ngx/paperless-ngx#512] opened 2022-03-23 16:26 UTC
**Describe the bug**
As part of my scan workflow I very often copy text out of the scanned documents, and use it e.g. for the title field of the scanned document (which is a generic name after scanning with my document scanner)
Starting paperless-ngx 1.6 I noticed a strange behaviour with this (and I do not recall I had it before with 1.5)
When copying text lines with spaces in between words to e.g. the title field, extra space characters are added between each word although not existing in the original document, Which I then manually have to delete again. And some times when deleting a "extra space" the cursor will jump to the end of the title line, which leads me to believe that sometimes the "space" is actually a non-visible special character.
The extra spaces also show up when copying the text to notepad, so I assume it is maybe related to OCR

**To Reproduce**
1. Go to any scanned PDF document which includes selectable text
2. Copy the text with CTRL-C
3. Insert the copied text in title field with CTRL-V (or to notepad, or ..)

**Expected behavior**
Text copied as in original document, with only one space character between words

**Screenshots**
![spaces](https://user-images.githubusercontent.com/1678124/159747906-73204407-6631-4e6d-96b1-f4e4c5f10a6f.png)

**Webserver logs**
Not available

**Relevant information**
 - Host OS of the machine running paperless: Synology DS918+
 - Browser Edge
 - Version 99
 - Installation method: docker
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`: changes were made but I can't see why they should have an impact on the described issue. And as far as I recall the issue did never occur before with paperless-ng 1.5, using same configuration changes

**Comment by shamoon** [comment] 2022-03-23 16:50
Yes this is an issue of OCR, which you can verify by looking in the "Content" tab. As for the title field issue I think that should be fixed already in the next release.

I will let others chime in on OCR issue but my gut tells me that just happens, sometimes.

**Comment by Profex** [comment] 2022-03-23 17:02
In the content tab the text shows up with no extra spaces, so below for above example
Extra spaces only show up when doing copy and paste directly from the PDF viewer used within paperless
If I download the PDF and do a copy / paste from Adobe Acrobat Reader or integrated PDF viewer in Edge no extra spaces show up, for the very same text

![spaces2](https://user-images.githubusercontent.com/1678124/159754318-f64d3220-30b4-4d47-a989-8660764a9c00.png)

**Comment by shamoon** [comment] 2022-03-23 17:34
Ah thanks for clarifying I though you had said the opposite.

Hmm. Are you using the "native" PDF viewer or the embedded one? (screenshot looks like embedded)

**Comment by Profex** [comment] 2022-03-23 18:25
How can I find out, or configure?
The PDFs are shown in a frame, but I currently don't know how to check what component technically renders the PDF inside that frame.
My assumption was that it is a PDF viewer component that comes with paperless, so not the one that comes with Edge itself, or standalone Acrobat Reader. But I might be of course wrong :)
That would at least explain why I don't face the issue when copy/paste from downloaded PDF from Acrobat Reader or the integrated PDF viewer in Edge (on new tab, in full screen mode)

**Comment by shamoon** [comment] 2022-03-23 18:33
Check under settings > Use PDF viewer provided by the browser

**Comment by Profex** [comment] 2022-03-23 19:27
Thanks! Overlooked that setting completely before .. 
Changed it to PDF viewer provider by browser, and issue is gone :)
No more extra spaces when copying very same text from very same PDF as before, using CTRL-C/CTRL-P

**Comment by yschroeder** [comment] 2022-03-23 21:27
Is this a regression in the PDF viewer we bundle? We updated it, right?

**Comment by shamoon** [comment] 2022-03-23 21:30
Presumably it is, yes. https://github.com/VadimDez/ng2-pdf-viewer and we're at latest version. But I cant reproduce this, I dont see it in my PDFs. So @Profex are you able to send this (or another) example PDF to take a look? At least then we can get an idea if its purely upstream issue.

**Comment by Profex** [comment] 2022-03-23 22:16
The one I tested with contains sensitive information, but will will check if I can find another one which also shows the issue, and  which I can share

**Comment by sukisoft** [comment] 2022-03-24 07:04
Can confirm this, regarding double spaces. In the browser PDF Viewer and in the one shipped with paperless. OCRed Text is definitely right.

**Comment by Profex** [comment] 2022-03-24 07:24
I have now created a PDF on my own for which I can reproduce as well (using build ghcr.io/paperless-ngx/paperless-ngx:latest)

Procedure used to create test PDF:

- Create document in Word
- Print document from Word, without saving the document first
- Scan the document using Brother iPrint&Scan, and let it save it as plain, non-searchable PDF

Result with paperless integrated PDF viewer doing copy&paste for first line
![image](https://user-images.githubusercontent.com/1678124/159863046-2b320a94-965a-4b10-b515-ff525b39dc33.png)
No issues with content recognized by OCR
![image](https://user-images.githubusercontent.com/1678124/159863413-eb58f275-d8cb-4f1e-9e6e-7f45c7ba261d.png)

Result with Edge integrated PDF viewer doing copy&paste for first line
![image](https://user-images.githubusercontent.com/1678124/159862927-ac40d41a-b18f-465c-8d6c-14059ca1b945.png)
No issues with content recognized by OCR
![image](https://user-images.githubusercontent.com/1678124/159863581-d748f7bf-1e6e-494e-ad32-022dc6737955.png)

How can I send you the PDF, so that you can also test using this one?

**Comment by shamoon** [comment] 2022-03-24 07:41
You can attach files to these comments =)

**Comment by Profex** [comment] 2022-03-24 07:50
Dooh :-) Was just checking the icons on top but I overlooked the comment at the bottom that you can drag & drop files ..
Copy of PDF below

[2022-03-24+Sonstige+ScanPC2022-03-24_081058.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8339434/2022-03-24%2BSonstige%2BScanPC2022-03-24_081058.pdf)

**Comment by shamoon** [comment] 2022-03-24 22:05
This is not proving to be an easy one to solve. I am pretty certain its an issue with the pdf viewer, which actually just uses Mozilla's pdf.js, e.g. https://github.com/mozilla/pdf.js/

That repo has 348 open issues =/

It really does seem like a bug, when I look at the text rendering event I see `textContentItemsStr` with:
```
["T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"," ","","T","h","i","s"," "," ","i","s"," "," ","a"," "," ","t","e","s","t"," "," ","f","o","r"," "," ","t","h","e"," "," ","d","o","u","b","l","e"," "," ","s","p","a","c","e"," "," ","c","h","a","r","a","c","t","e","r"," "," ","i","ss","u","e"]
```

Perhaps theres some way to hook into there and change things, but its not obvious to me.

@Profex might I suggest opening an issue in the upstream package (pdf.js)

And by the way, we *could* turn off text selection in the embedded viewer completely and just say "use the content tab" but that would be a regression for most other PDFs that dont have this issue. But as a workaround I will say, "you can just copy / paste from the content tab" =)

**Comment by Profex** [comment] 2022-03-24 22:53
Many thanks for looking further into this.
The text rendering element you included makes the issue clearly visible

But could it be that the pdf.js team is already aware, and fixed the issue in a recent version of pdf.js?
And is the fixed version of pdf.js already used by ng2-pdf-viewer?
Just found this, and the described issue sounds pretty similar: https://github.com/mozilla/pdf.js/issues/9083

And sure, I will use the content tab for now when using the paperless embedded viewer.
Or even better stay with the browser PDF viewer, which does also work realiably when doing copy & paste directly from PDF. 
And in addition the browser PDF viewer also works with password protected PDF, which is another issue I faced with the paperless embedded viewer =) (https://github.com/paperless-ngx/paperless-ngx/discussions/510#discussioncomment-2425278).

**Comment by shamoon** [comment] 2022-03-24 23:05
Good find! Somehow I missed that. 

Well, even though I dont see it in the release notes it does look like that PR was included in v2.13.216 see https://github.com/mozilla/pdf.js/commit/bbb64369f1ffa118000ae5b3be1611cd0aec8003

But actually the component we're using [is already using v2.13.216](https://github.com/VadimDez/ng2-pdf-viewer/blob/bb1063721e2ae5e40afcd595cf3d1961bd2a5649/package.json#L42) =( 

So not sure, seems that fix doesnt quite fix it? Maybe you want to let the author of that PR know?

**Comment by shamoon** [comment] 2022-06-23 14:50
Happy to say I think this is actually fixed in the current `dev` branch, see video. I checked in 3 browsers

https://user-images.githubusercontent.com/4887959/175328007-5ad020ad-19fb-4494-a2a1-7469b3b0d116.mov

**Comment by tooomm** [comment] 2022-08-07 10:02
Is this now fixed in the most recent v1.8.0 release as well and can be closed?

Or do we need to still track this and double check dependencies?

**Comment by vicegold** [comment] 2022-08-15 13:37
I got a similar issue on 1.8.0.

I usually scan my files with Abby FineReader, which also does the OCR. When I import these documents into Paperless, the content is barely usable since Paperless is putting a space between almost every character. When I download the file from Paperless and select/copy the text, I also get these spaces. When I do the same with the original Abby file, I get perfectly formatted text.

Here's an example that should make it clear on what's happening:

![CleanShot 2022-08-15 at 15 35 19](https://user-images.githubusercontent.com/3935131/184645759-9a4a7fee-11a7-4325-be62-b269c85054c8.png)
![CleanShot 2022-08-15 at 15 37 14](https://user-images.githubusercontent.com/3935131/184645794-072e59df-e89c-493c-960f-59fa03d25a81.png)

**Comment by shamoon** [comment] 2022-08-15 14:00
@vicegold your issue is similar but not the same. Yours is the OCR'd text, this Issue was for the PDF display. Im going to close this one and #1311 exists for the other one.

**Closed by shamoon** 2022-08-15 14:00 UTC
Labels: bug, help wanted, dependencies
