### ISSUE TITLE
[BUG] Cannot access bottom items on left pane

### ISSUE THREAD

**Issue by akumiszcza** [paperless-ngx/paperless-ngx#7809] opened 2024-09-30 15:30 UTC
### Description

I cannot access the bottom items on left pane (dashboard, documents, saved views, manage...). Moving the mouse circle only moves the center part with documents.

### Steps to reproduce

1. Open Paperless on any view.
2. Move mouse over the left pane.
3. Try to move the mouse wheel to access not visible part of the left pane.
4. Only the center part appears.

### Webserver logs

```bash
-
```

### Paperless-ngx version

Actually, I cannot even access this part to see the version

### Host OS

Docker on Windows 11

### Installation method

Docker - official image

### Browser

tried Brave and Edge

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-09-30 15:36
Dupe of #7785 and #7735

All closed by #7738

**Closed by shamoon** 2024-09-30 15:36 UTC
Labels: bug, unconfirmed
