### ISSUE TITLE
[BUG] /api/logs/$type/ returns 404

### ISSUE THREAD

**Issue by astubenbord** [paperless-ngx/paperless-ngx#2738] opened 2023-02-23 21:33 UTC
### Description

I have found that even though the `/api/logs/` endpoint returns `["paperless", "mail"]`, the server still sends a 404 response when calling `/api/logs/mail/`. Is this intentional?

To me it would make sense to not include `"mail"` in the response from `/api/logs/`, as this suggests that the log should exists.

### Steps to reproduce

1. GET `/api/logs/`
2. Ensure that e.g. "mail" is listed.
3. GET `/api/logs/mail/`
4. Observe 404 response

Same goes for the webclient when selecting the mail.log tab:
Browser console output: `Failed to load resource: the server responded with a status of 404 ()`

### Webserver logs

```bash
[2023-02-23 22:30:24,488] [WARNING] [django.request] Not Found: /api/logs/mail/
```

### Paperless-ngx version

Tested on 1.11.3 and 1.13.0

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment] 2023-02-23 22:07
I can't reproduce this, perhaps something is up with your install

```
Summary
URL: /api/logs/mail/
Status: 200
```

<img width="461" alt="Screenshot 2023-02-23 at 2 05 15 PM" src="https://user-images.githubusercontent.com/4887959/221041410-ca5d3a18-3e6d-4b64-a617-5b74027121f3.png">

<img width="326" alt="Screenshot 2023-02-23 at 2 05 20 PM" src="https://user-images.githubusercontent.com/4887959/221041405-161949be-e179-4860-b3cf-4291df2ecde6.png">

**Comment by astubenbord** [comment] 2023-02-23 22:11
I've tested with two instances, same result on both. One of them is a fresh dockerized instance. I don't use any mail features. Could this have to do something with this?

**Comment by shamoon** [comment] 2023-02-23 22:20
Ah, I guess I assumed you were. The log file isn't created until e.g. a mail action runs.

I mean I suppose it could be changed to not return the mail endpoint if there is no log, but that feels a bit pedantic since a 404 at the mail endpoint communicates the same idea? Is there a use case for you where getting a 404 is not enough?

**Comment by astubenbord** [comment] 2023-02-23 22:23
No, the 404 is sufficient, I guess it just didn't make much sense to me why the /logs/ endpoint would return the path to a logfile that doesn't exist, seems a bit inconsistent to me but it's not really that important.

Thanks

**Comment by shamoon** [comment] 2023-02-23 22:47
Well of course I wasn't going to be able to resist correcting this 🙃

**Comment by astubenbord** [comment] 2023-02-23 23:25
Haha thank you very much! 😄

**Comment by shamoon** [comment] 2023-02-23 23:32
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/dbea2acc8f43e56fe93d2c518378ece1737bf538

**Closed by shamoon** 2023-02-23 23:32 UTC
Labels: cant-reproduce
