### ISSUE TITLE
[BUG] PAPERLESS_OCR_DESKEW: false seems to be ignored

### ISSUE THREAD

**Issue by makuser** [paperless-ngx/paperless-ngx#8288] opened 2024-11-15 13:49 UTC
### Description

Many imported scans come out skewed in the archive, even though I set the env `PAPERLESS_OCR_DESKEW: false` in my docker compose file.

As far as I can tell, the flag is not passed to the appropriate archive creation tool.

### Steps to reproduce

Unfortunately, I don't know yet, as it does not happen on every file.

### Webserver logs

```bash
[2024-11-15 14:28:44,576] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/multipageproject.pdf to the task queue.
[2024-11-15 14:28:45,248] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[1eb1d253-48f1-4ed6-a32c-0ad2148fd1aa] received
[2024-11-15 14:28:45,922] [INFO] [paperless.matching] Document did not match Workflow: BERK Freigabe
[2024-11-15 14:28:45,924] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with: 
[2024-11-15 14:28:45,968] [INFO] [paperless.consumer] Consuming multipageproject.pdf
[2024-11-15 14:28:46,188] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
[2024-11-15 14:28:46,572] [INFO] [ocrmypdf._pipelines.ocr] Start processing 2 pages concurrently
[2024-11-15 14:28:47,879] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 6.42 - no change
[2024-11-15 14:28:48,190] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 12.47 - rotation appears correct
[2024-11-15 14:28:54,447] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2024-11-15 14:28:56,342] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2024-11-15 14:28:56,411] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2024-11-15 14:28:57,700] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.08 savings: 7.1%
[2024-11-15 14:28:57,700] [INFO] [ocrmypdf._pipeline] Total file size ratio: 8.46 savings: 88.2%
[2024-11-15 14:28:57,702] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-3B (as expected)
[2024-11-15 14:28:59,167] [INFO] [paperless.parsing] convert exited 0
[2024-11-15 14:29:00,506] [INFO] [paperless.handlers] Assigning correspondent DB Privat- und Firmenkundenbank AG to 2024-11-13 multipageproject
[2024-11-15 14:29:00,587] [INFO] [paperless.handlers] Assigning document type Beleg to 2024-11-13 DB Privat- und Firmenkundenbank AG multipageproject
[2024-11-15 14:29:01,273] [INFO] [paperless.consumer] Document 2024-11-13 DB Privat- und Firmenkundenbank AG multipageproject consumption finished
[2024-11-15 14:29:01,296] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 1042 created
[2024-11-15 14:29:01,358] [INFO] [celery.app.trace] Task documents.tasks.consume_file[1eb1d253-48f1-4ed6-a32c-0ad2148fd1aa] succeeded in 16.104061948135495s: 'Success. New document id 1042 created'
```

### Paperless-ngx version

2.13.4

### Host OS

Debian 12, Docker 27.3.1-1~debian.12~bookworm

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.13.4",
    "server_os": "Linux-6.8.8-2-pve-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 1671552434176,
        "available": 1671405371392
    },
    "database": {
        "type": "mysql",
        "url": "c035_paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0028_alter_mailaccount_password_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis:///2:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-11-15T14:39:13.341640+01:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-11-15T13:05:18.466172Z",
        "classifier_error": null
    }
}
```

### Configuration changes

```yaml
environment:
      PAPERLESS_REDIS: redis://redis:6379/2
      PAPERLESS_REDIS_PREFIX: papermak
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: mydbserver
      PAPERLESS_DBNAME: c035_paperless
      PAPERLESS_DBUSER: c035_paperless
      PAPERLESS_DBPASS: mypass
      PAPERLESS_DBPORT: 3306
      PAPERLESS_URL: https://paperlesshost
      PAPERLESS_TRUSTED_PROXIES: 10.41.14.199 172.18.0.1
      PAPERLESS_SECRET_KEY: mysecretkey
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
#      PAPERLESS_FILENAME_FORMAT: "{owner_username}/{document_type} {created_year}/{correspondent}/{title}_{created_year_short}{created_month}{created_day}"
      PAPERLESS_FILENAME_FORMAT: "{{ owner_username }}/{{ document_type }} {{ created_year }}/{{ correspondent }}/{{ title }}_{{ created_year_short }}{{ created_month }}{{ created_day }}"
      PAPERLESS_OCR_DESKEW: false
      USERMAP_UID: 1004
      USERMAP_GID: 953
```

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-11-15 14:55
1. This hasn’t changed in years and I assure you it is being passed to the ocr tool. If you include all logs you’d see that more clearly.
2. You’re probably looking for https://docs.paperless-ngx.com/configuration/#PAPERLESS_OCR_ROTATE_PAGES_THRESHOLD
3. I’m going to close this because there is almost certainly not a bug here but feel free to add more information if otherwise.

**Closed by shamoon** 2024-11-15 14:55 UTC
Labels: bug, unconfirmed

**Comment by bolsblue** [comment] 2024-12-01 10:27
I can confirm that this is in fact a bug.

```
[2024-12-01 10:19:12,487] [DEBUG] [paperless.management.consumer] Waiting for file /mnt/data/consume/scanner_20241201_101858_001193.pdf to remain unmodified
[2024-12-01 10:19:17,501] [INFO] [paperless.management.consumer] Adding /mnt/data/consume/scanner_20241201_101858_001193.pdf to the task queue.
[2024-12-01 10:19:17,633] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin
[2024-12-01 10:19:17,637] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin
[2024-12-01 10:19:17,641] [DEBUG] [paperless.barcodes] Scanning for barcodes using PYZBAR
[2024-12-01 10:19:17,646] [DEBUG] [paperless.barcodes] PDF has 2 pages
[2024-12-01 10:19:17,650] [DEBUG] [paperless.barcodes] Processing page 0
[2024-12-01 10:19:17,808] [DEBUG] [paperless.barcodes] Image is at /tmp/paperless/tmpg5b90smv/barcode5gy2v157/0e977ebb-7b1a-4d91-9035-67707cef866b-1.ppm
[2024-12-01 10:19:18,039] [DEBUG] [paperless.barcodes] Processing page 1
[2024-12-01 10:19:18,193] [DEBUG] [paperless.barcodes] Image is at /tmp/paperless/tmpg5b90smv/barcode5gy2v157/94332407-6cf0-4e88-8710-6704a39876a9-2.ppm
[2024-12-01 10:19:18,393] [INFO] [paperless.tasks] BarcodePlugin completed with no message
[2024-12-01 10:19:18,398] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin
[2024-12-01 10:19:18,407] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:
[2024-12-01 10:19:18,411] [DEBUG] [paperless.tasks] Executing plugin ConsumeTaskPlugin
[2024-12-01 10:19:18,426] [INFO] [paperless.consumer] Consuming scanner_20241201_101858_001193.pdf
[2024-12-01 10:19:18,434] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2024-12-01 10:19:18,451] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-12-01 10:19:18,465] [DEBUG] [paperless.consumer] Parsing scanner_20241201_101858_001193.pdf...
[2024-12-01 10:19:18,479] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
[2024-12-01 10:19:18,592] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngx2vj9jm4r/scanner_20241201_101858_001193.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-8xb4c5v6/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-8xb4c5v6/sidecar.txt')}
[2024-12-01 10:19:18,725] [INFO] [ocrmypdf._pipelines.ocr] Start processing 2 pages concurrently
[2024-12-01 10:19:20,123] [INFO] [ocrmypdf._pipeline] page is facing ⇦, confidence 1.25 - confidence too low to rotate
[2024-12-01 10:19:20,203] [INFO] [ocrmypdf._pipeline] page is facing ⇨, confidence 5.88 - confidence too low to rotate
[2024-12-01 10:19:33,187] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
[2024-12-01 10:19:35,461] [INFO] [ocrmypdf.optimize] Image optimization did not improve the file - optimizations will not be used
[2024-12-01 10:19:35,494] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.00 savings: -0.1%
[2024-12-01 10:19:35,498] [INFO] [ocrmypdf._pipeline] Total file size ratio: 0.55 savings: -82.3%
[2024-12-01 10:19:35,506] [INFO] [ocrmypdf._pipelines._common] Output file is a PDF/A-2B (as expected)
[2024-12-01 10:19:36,545] [WARNING] [ocrmypdf._validation] The output file size is 1.82× larger than the input file.
Possible reasons for this include:
--deskew was issued, causing transcoding.
PDF/A conversion was enabled. (Try `--output-type pdf`.)
[2024-12-01 10:19:36,554] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file
[2024-12-01 10:19:36,558] [DEBUG] [paperless.consumer] Generating thumbnail for scanner_20241201_101858_001193.pdf...
[2024-12-01 10:19:36,565] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-8xb4c5v6/archive.pdf[0] /tmp/paperless/paperless-8xb4c5v6/convert.webp
[2024-12-01 10:19:38,281] [INFO] [paperless.parsing] convert exited 0
[2024-12-01 10:19:38,647] [DEBUG] [paperless.consumer] Saving record to database
[2024-12-01 10:19:38,657] [DEBUG] [paperless.consumer] Creation date from parse_date: 2015-08-24 00:00:00+02:00
[2024-12-01 10:19:39,112] [INFO] [paperless.handlers] Assigning document type offizielles Dokument to 2015-08-24 scanner_20241201_101858_001193
[2024-12-01 10:19:39,415] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngx2vj9jm4r/scanner_20241201_101858_001193.pdf
[2024-12-01 10:19:39,426] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-8xb4c5v6
[2024-12-01 10:19:39,430] [INFO] [paperless.consumer] Document 2015-08-24 scanner_20241201_101858_001193 consumption finished
[2024-12-01 10:19:39,438] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 343 created
```

Setting `PAPERLESS_OCR_USER_ARGS={"deskew": false}` does work.

**Comment by shamoon** [comment] 2024-12-01 16:06
I can confirm it is not.

`PAPERLESS_OCR_DESKEW=false`

```
[2024-12-01 07:56:11,118] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/private/var/folders/xz/cd21y5k917zds8k3s0nk1nd00000gn/T/paperless/paperless-ngx1y3rgw94/lc_otiato.pdf'), 'output_file': PosixPath('/private/var/folders/xz/cd21y5k917zds8k3s0nk1nd00000gn/T/paperless/paperless-5jj_5h_h/archive.pdf'), 'use_threads': True, 'jobs': 24, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/private/var/folders/xz/cd21y5k917zds8k3s0nk1nd00000gn/T/paperless/paperless-5jj_5h_h/sidecar.txt')}
```

vs default:

```
[2024-12-01 07:59:59,050] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/private/var/folders/xz/cd21y5k917zds8k3s0nk1nd00000gn/T/paperless/paperless-ngx9f3ts98s/lc_otiato.pdf'), 'output_file': PosixPath('/private/var/folders/xz/cd21y5k917zds8k3s0nk1nd00000gn/T/paperless/paperless-tp2ot4p3/archive.pdf'), 'use_threads': True, 'jobs': 24, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/private/var/folders/xz/cd21y5k917zds8k3s0nk1nd00000gn/T/paperless/paperless-tp2ot4p3/sidecar.txt')}
```

The 'bug' here was that the setting isn't passed to OCRmyPDF, which you can see is false. With it set to false it is not set in the arguments. If your question is about the effect of the setting, that's a question for the OCRmyPDF docs, and not a bug.

**Comment by bolsblue** [comment] 2024-12-01 16:59
All I can say is that my installation behaves differently.

`PAPERLESS_OCR_DESKEW=false`

```
[2024-12-01 17:50:01,083] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxw6wy6kgt/test.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-jt6ybnr3/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-jt6ybnr3/sidecar.txt')}
```

I have to set `PAPERLESS_OCR_USER_ARGS={"deskew": false}` for OCRmyPDF to stop applying deskew.

```
[2024-12-01 10:52:49,112] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxx0su8ix6/scanner_20241201_105226_001201.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-q_7w2tiu/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': False, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-q_7w2tiu/sidecar.txt')}
```

**Comment by shamoon** [comment] 2024-12-01 17:01
1. Changing environment variables requires re-creating a container.
2. If you've set it via app config that takes precedence.

I assure you, your installation behaves "the same" as everyone else's 😜

**Comment by bolsblue** [comment] 2024-12-01 17:03
Gosh I'm so dumb, I indeed had it set via web GUI.
Sorry for the fuss 🙈
