### ISSUE TITLE
[BUG] PAPERLESS_IGNORE_DATES not honored

### ISSUE THREAD

**Issue by github-cli** [paperless-ngx/paperless-ngx#693] opened 2022-04-11 21:37 UTC
### Description

I have set PAPERLESS_IGNORE_DATES with several dates in the format YYYY-MM-DD,YYYY-MM-DD etc.
However those dates (dates of birth) are still being used as created date in paperless-ngx

### Expected behavior

ignore the configured dates and use some other date

### Steps to reproduce

1.) configure the variable as mentioned above
2.) upload documents containing these dates
3.) some of those documents will still have that date as created date

### Paperless-ngx version

1.6.0

### Host OS

Ubuntu 20.04

### Installation method

Docker

### Browser

not relevant

### Configuration changes

many

### Other

fresh deployment

**Comment by stumpylog** [comment] 2022-04-12 16:36
What is your configuration value for PAPERLESS_DATE_ORDER, if any?

**Comment by github-cli** [comment] 2022-04-12 18:33
PAPERLESS_FILENAME_DATE_ORDER=YMD

the created field even shows the date EXACTLY how I typed it in to ignore, YYYY-MM-DD with our birth dates
it does honor the files that were created with a date in the filename (though I might disable this as my scanner simply names them according to the scan date... or is there an option to prefer detected dates?)

**Comment by stumpylog** [comment] 2022-04-12 18:53
Hm, curious.  Do you also have the environment variable `PAPERLESS_FILENAME_DATE_ORDER` set?  I do find there's a preference for getting a date from the filename, then trying from content, which isn't really documented.

But in both cases, it looks like the ignore dates setting is applied, so I'll have to dig in more when I can

**Comment by github-cli** [comment] 2022-04-12 19:01
yes I do, see previous post.
I also noticed it takes the date from the filename which apparently works for most... personally I would prefer that to be the backup as the date might be close to the date many times but almost never is the actual created date (so if it doesnt find anything but a date in the file is present, thats still good for searches)

but yea, back to the original problem... the ignore dates setting doesnt seem to work...
if it matters at all, I use YMD as mentioned in the previous post, I personally name files YYYY-MM-DD because it makes it easier to sort by date and I also use the ISO date for display (personal preference I guess).
Of course the date format inside the actual documents vary, though its mostly DD.MM.YY or DD.MM.YYYY (and even then it seems to detect the date correctly, convert it to YYYY-MM-DD but doesnt ignore it.

PS: Maybe that could be the issue? I ignore it in the format YYYY-MM-DD, it finds it in DD.MM.YY and correctly converts it into YYYY-MM-DD but doesnt ignore it?

**Comment by stumpylog** [comment] 2022-04-12 20:49
I haven't been able to reproduce anything yet, though I am finding lots of new testing to add.

I've been assuming these are PDFs or similar (PNG, JPEG, etc), could you confirm that's the case?

**Comment by github-cli** [comment] 2022-04-12 21:09
yes, they are official documents.
like birth certificates, passports, ID, wedding documents, etc.
all scanned as PDF

**Comment by github-cli** [comment] 2022-04-12 21:35
I can confirm that if I enter the ignore date in the format that is on the document, it is ignored correctly.
e.g. document has my birthdate like 13.12.10 (DD.MM.YY) it will put 2010-12-13 as created date even though I put 2010-12-13 as one of the ignored dates.
So I would need to put all possible combinations in the ignore list, I think the behavior should be that I enter the ignored dates in a specific format and if it detects a date that it would convert to the same date, it gets ignored.

PS: If I want to change those creation dates, there is no way to "rescan" them, I would need to redo the whole import, right?

**Comment by github-cli** [comment] 2022-04-13 07:20
actually this case i just tried was a picture names passport.jpg

at this point, importing the ~350 files again over night is quicker for me than editing all dates (still have the files sorted in subfolders for "automatic" tagging")

if i have a file named with the date, with my current settings it seems it will always take the date of the filename (at least the few examples i verified).

the created date is very helpful for me in finding documents :)
i think currently it uses the first date it finds in the document that isnt ignored in the exact syntax its written in...

**Comment by stumpylog** [comment] 2022-04-13 17:55
That does help, if only to highlight how confusing dates and parsing them can be:

- the ignore dates need to be comma separated, not space separated, so that environment variable value would result in no ignored dates
- The filename date won't be parsed as it doesn't match anything we look for, there needs to be some separators (`.`, `-`, `/`, etc).  That's not clear in the docs so I'll update those
- Once this change is complete, IGNORE_DATES should be set in the same format as DATE_ORDER.  It may work otherwise, but isn't certain

**Comment by march42** [comment] 2022-04-25 20:39
> That does help, if only to highlight how confusing dates and parsing them can be:
Thanks for the clearification. I changed IGNORE_DATES to DMY order, according to your suggestions, and my issue seems to be solved. Thanks for your help.
I think about adding an error message on parsing the IGNORE_DATES, if the values fail. For me, this would have been helpful.

**Comment by qcasey** [comment] 2022-05-10 23:47
Fixed in #721

**Closed by qcasey** 2022-05-10 23:47 UTC
Labels: bug, backend
