### ISSUE TITLE
[BUG] OSError: [Errno 39] Directory not empty: '/tmp/ when mounted outside docker

### ISSUE THREAD

**Issue by miodzicho** [paperless-ngx/paperless-ngx#2639] opened 2023-02-10 10:39 UTC
### Description

I have deployed paperless-ngx un unraid using docker. Due to high consumtion of docker.img i mounted /tmp directory outside docker (pointing to local tmp directory on ssd). When adding documents 80% are failing due to OSError: [Errno 39] Directory not empty: '/tmp/

### Steps to reproduce

1. deploy paperless-ngx docker on unraid
2. configure /tmp to be mounted outside docker
3. add documents

### Webserver logs

```bash
[2023-02-10 11:31:13,328] [ERROR] [paperless.consumer] Error while consuming document kbo-Kinderzentrum.pdf: OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 332, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 393, in run_pipeline
    optimize_messages = exec_concurrent(context, executor)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 280, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 196, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 165, in make_intermediate_images
    ocr_image = preprocess(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 112, in preprocess
    image = preprocess_clean(image, page_context)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 508, in preprocess_clean
    return unpaper.clean(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 184, in clean
    run_unpaper(input_file, output_file, dpi=dpi, mode_args=unpaper_args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 149, in run_unpaper
    raise SubprocessOutputError(
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 119, in _setup_unpaper_io
    yield input_png, output_pnm, tmppath
  File "/usr/local/lib/python3.9/tempfile.py", line 830, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.9/tempfile.py", line 834, in cleanup
    self._rmtree(self.name)
  File "/usr/local/lib/python3.9/tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/local/lib/python3.9/shutil.py", line 740, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.9/shutil.py", line 738, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 379, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 379, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
documents.parsers.ParseError: OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'
[2023-02-10 11:31:13,381] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[fa155b9b-7cf2-4dc6-9280-39e04fa787d6] raised unexpected: ConsumerError("kbo-Kinderzentrum.pdf: Error while consuming document kbo-Kinderzentrum.pdf: OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'")
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 332, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 393, in run_pipeline
    optimize_messages = exec_concurrent(context, executor)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 280, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 87, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 196, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 165, in make_intermediate_images
    ocr_image = preprocess(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 112, in preprocess
    image = preprocess_clean(image, page_context)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 508, in preprocess_clean
    return unpaper.clean(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 184, in clean
    run_unpaper(input_file, output_file, dpi=dpi, mode_args=unpaper_args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 149, in run_unpaper
    raise SubprocessOutputError(
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/unpaper.py", line 119, in _setup_unpaper_io
    yield input_png, output_pnm, tmppath
  File "/usr/local/lib/python3.9/tempfile.py", line 830, in __exit__
    self.cleanup()
  File "/usr/local/lib/python3.9/tempfile.py", line 834, in cleanup
    self._rmtree(self.name)
  File "/usr/local/lib/python3.9/tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "/usr/local/lib/python3.9/shutil.py", line 740, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.9/shutil.py", line 738, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 379, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 379, in parse
    raise ParseError(f"{e.__class__.__name__}: {str(e)}") from e
documents.parsers.ParseError: OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 192, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 398, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: kbo-Kinderzentrum.pdf: Error while consuming document kbo-Kinderzentrum.pdf: OSError: [Errno 39] Directory not empty: '/tmp/tmpr33xftlh'
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected] Exception ignored in: 
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected] <finalize object at 0x15523e5fa1a0; dead>
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected] Traceback (most recent call last):
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/weakref.py", line 591, in __call__
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected]     
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected] return info.func(*info.args, **(info.kwargs or {}))
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/tempfile.py", line 820, in _cleanup
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected]     
[2023-02-10 11:31:13,383] [WARNING] [celery.redirected] cls._rmtree(name)
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/tempfile.py", line 816, in _rmtree
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected]     
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected] _shutil.rmtree(name, onerror=onerror)
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shutil.py", line 740, in rmtree
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected]     
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected] onerror(os.rmdir, path, sys.exc_info())
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected]   File "/usr/local/lib/python3.9/shutil.py", line 738, in rmtree
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected]     
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected] os.rmdir(path)
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected] OSError
[2023-02-10 11:31:13,384] [WARNING] [celery.redirected] : 
[2023-02-10 11:31:13,385] [WARNING] [celery.redirected] [Errno 39] Directory not empty: '/tmp/paperless/paperless-ngx3kcl1kke'
```

### Paperless-ngx version

1.12.2

### Host OS

docker

### Installation method

Docker - official image

**Comment by miodzicho** [comment] 2023-02-10 15:46
I would say it's second option, because when I browse into that "not empty" folder, i clearly see that is empty. As quick test, I spin up container without mapping /tmp and works just fine...but as I said docker.img is getting enormously huge.

**Comment by stumpylog** [comment] 2023-02-10 15:47
It's also inside Python's `tempfile`, which it looks like OCRMyPDF uses to generate files or folders, to then clean up after completion.  I'm not sure why one would mount `/tmp` externally anyway.  It's supposed to be ephemeral files, not something to keep

**Comment by miodzicho** [comment] 2023-02-10 15:54
> It's also inside Python's `tempfile`, which it looks like OCRMyPDF uses to generate files or folders, to then clean up after completion.  I'm not sure why one would mount `/tmp` externally anyway.  It's supposed to be ephemeral files, not something to keep

It should indeed, but after 24h docker.img was 99% full. I have allocated 30GB to docker, and paperless took half of it. I don't want to keep them, just avoid filling up docker.img file.

**Comment by stumpylog** [comment] 2023-02-10 16:33
That seems more like the bug then.  Were you consuming many files during this time?

Temporary files are created during consuming and uploads also go into temporary directories.  All these are cleaned up when finished (as can be seen in the traceback).  Nothing is creating these files while just running

**Comment by miodzicho** [comment] 2023-02-10 16:39
Yes, I have uploaded around 8k documents. But still, as you said, tmp should be emptied after successful consumption.

**Comment by stumpylog** [comment] 2023-02-10 16:52
I don't have 8000 files to test with, but with 1000 files and 6 workers, I did some testing, while running `watch tree --du -h /tmp`.

- I never saw more than a few hundred kbs in tmp in total
- Retrying with a script to force consumption to fail, everything was still cleaned up (if anything, this used less, since it never reached parsing)

Do you still have the giant folder?  What was/is in there?

**Comment by miodzicho** [comment] 2023-02-10 16:59
Not anymore, I did many reinsatallations, changes in configuration etc. But I can try to replicate this on Monday morning. And post all results.

**Comment by stumpylog** [comment] 2023-02-12 02:12
That'd be great.  Were you using barcodes to split files by any chance?  I've found the split files will remove around (at least until tmp is cleaned up)

**Comment by shamoon** [comment] 2023-02-12 16:47
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/8b3d01c49bb17cae7221d61fcd7fa0b41cebd853

**Closed by shamoon** 2023-02-12 16:47 UTC
Labels: cant-reproduce

**Comment by shamoon** [comment] 2023-02-12 16:49
Between usual tmp file cleanup and the above fix which will be in our next release hopefilly this is covered, though sounds like exact issue itself may not be reproducible. 

When you have a chance to test of course please let us know

**Comment by miodzicho** [comment] 2023-02-14 08:07
Consumed ca 5k documents, docker.img is now increased by up to 80% (was 51% when installed paperless-ngx).
`Every 2.0s: tree --du -h /tmp                                                                                                                                 ef84b2478e65: Tue Feb 14 09:07:19 2023

/tmp
├── [ 11K]  gs_2SvcQb
├── [265M]  gs_4PI5Qd
├── [   0]  gs_5AU5ka
├── [   0]  gs_AEHoK5
├── [ 16M]  gs_E9Emt5
├── [ 184]  gs_cMbx54
├── [265M]  gs_tHTAJe
├── [ 22M]  gs_xuflS5
├── [649M]  ocrmypdf.io.5pzd6zs5`

**Comment by stumpylog** [comment] 2023-02-14 14:15
Guessing from the naming "gs" is GhostScript and ocrmypdf is pretty clear.  This is likely something with that library not cleaning up after itself.  Just to be sure, in the debug log file, could you locate a few of the ocrmypdf calls and post it?
