### ISSUE TITLE
[BUG] I have tesseract-ocr-chi-sim installed, but Django checks says I don't have tesseract-ocr-chi-sim installed!

### ISSUE THREAD

**Issue by wancao-eng** [paperless-ngx/paperless-ngx#8343] opened 2024-11-24 05:18 UTC
### Description

I have tesseract-ocr-chi-sim installed, but Django checks says I don't have tesseract-ocr-chi-sim installed!
I chose to install eng+chi-sim in the install script, and apt does install tesseract-ocr-chi-sim, but Django checks says I don't have it!

### Steps to reproduce

Use the install script to install, choose to install tika and install eng+chi-sim's ocr, all other options remain unchanged.

### Webserver logs

```bash
[admin@DESKTOP-JM3IP9V paperless-ngx]$ docker compose up
[+] Running 5/5
 ✔ Container paperless-tika-1       Running                                                                                     0.0s
 ✔ Container paperless-gotenberg-1  Running                                                                                     0.0s
 ✔ Container paperless-broker-1     Running                                                                                     0.0s
 ✔ Container paperless-db-1         Running                                                                                     0.0s
 ✔ Container paperless-webserver-1  Recreated                                                                                   5.2s
Attaching to broker-1, db-1, gotenberg-1, tika-1, webserver-1
webserver-1  | Paperless-ngx docker container starting...
webserver-1  | Installing languages...
webserver-1  | Package tesseract-ocr-eng already installed!
webserver-1  | Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
webserver-1  | Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
webserver-1  | Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
webserver-1  | Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8789 kB]
webserver-1  | Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2468 B]
webserver-1  | Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [204 kB]
webserver-1  | Fetched 9250 kB in 4s (2253 kB/s)
webserver-1  | Reading package lists...
webserver-1  | Installing package tesseract-ocr-chi-sim...
webserver-1  | Installing package tesseract-ocr-chi-tra...
webserver-1  | Creating directory scratch directory /tmp/paperless
webserver-1  | mkdir: created directory '/tmp/paperless'
webserver-1  | Adjusting permissions of paperless files. This may take a while.
webserver-1  | Waiting for PostgreSQL to start...
webserver-1  | Connected to PostgreSQL
webserver-1  | Waiting for Redis...
webserver-1  | Connected to Redis broker.
webserver-1  | Apply database migrations...
webserver-1  | Operations to perform:
webserver-1  |   Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
webserver-1  | Running migrations:
webserver-1  |   No migrations to apply.
webserver-1  | Running Django checks
webserver-1  | SystemCheckError: System check identified some issues:
webserver-1  |
webserver-1  | ERRORS:
webserver-1  | ?: The selected ocr language chi-sim is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
webserver-1  |
webserver-1  | System check identified 1 issue (0 silenced).
webserver-1 exited with code 0
webserver-1  | Package tesseract-ocr-chi-sim already installed!
webserver-1  | Package tesseract-ocr-chi-tra already installed!
webserver-1  | Creating directory scratch directory /tmp/paperless
webserver-1  | Adjusting permissions of paperless files. This may take a while.
webserver-1  | Waiting for PostgreSQL to start...
webserver-1  | Connected to PostgreSQL
webserver-1  | Waiting for Redis...
webserver-1  | Connected to Redis broker.
webserver-1  | Apply database migrations...
webserver-1  | Operations to perform:
webserver-1  |   Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
webserver-1  | Running migrations:
webserver-1  |   No migrations to apply.
webserver-1  | Running Django checks
webserver-1  | SystemCheckError: System check identified some issues:
webserver-1  |
webserver-1  | ERRORS:
webserver-1  | ?: The selected ocr language chi-sim is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
webserver-1  |
webserver-1  | System check identified 1 issue (0 silenced).
webserver-1 exited with code 0
webserver-1  | Package tesseract-ocr-chi-sim already installed!
webserver-1  | Package tesseract-ocr-chi-tra already installed!
webserver-1  | Creating directory scratch directory /tmp/paperless
webserver-1  | Adjusting permissions of paperless files. This may take a while.
webserver-1  | Waiting for PostgreSQL to start...
webserver-1  | Connected to PostgreSQL
webserver-1  | Waiting for Redis...
webserver-1  | Connected to Redis broker.
webserver-1  | Apply database migrations...
webserver-1  | Operations to perform:
webserver-1  |   Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
webserver-1  | Running migrations:
webserver-1  |   No migrations to apply.
webserver-1  | Running Django checks
webserver-1  | SystemCheckError: System check identified some issues:
webserver-1  |
webserver-1  | ERRORS:
webserver-1  | ?: The selected ocr language chi-sim is not installed. Paperless cannot OCR your documents without it. Please fix PAPERLESS_OCR_LANGUAGE.
webserver-1  |
webserver-1  | System check identified 1 issue (0 silenced).
webserver-1 exited with code 1
```

### Paperless-ngx version

2.13.5

### Host OS

Archlinux

### Installation method

Docker - official image

### Browser

Microsoft Edge

### Configuration changes

None

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-11-24 05:37
#4320

This is also basically a duplicate of your previous one

**Closed by shamoon** 2024-11-24 05:37 UTC
Labels: bug, unconfirmed
