### ISSUE TITLE
[BUG] Leave Website? popup

### ISSUE THREAD

**Issue by r2ixuz** [paperless-ngx/paperless-ngx#1366] opened 2022-08-06 09:17 UTC
### Description

The "Leave Website?" Pop-up appears in Chrome when you try to close the browser tab even all documents in Paperless are closed and no other unsaved changes exist.

<img width="502" alt="Bildschirmfoto 2022-08-06 um 11 14 14" src="https://user-images.githubusercontent.com/15087554/183242807-a77fb2c0-42c7-4593-b14d-5744af95799d.png">

### Steps to reproduce

Open the Edit view in Paperless for a document. Do not change anything and close the document in Paperless. Try to close the browser tab.

### Paperless-ngx version

1.8.0

### Host OS

gentoo x86_64

### Installation method

Docker - official image

### Browser

Chrome

**Comment by shamoon** [comment] 2022-08-06 15:00
I cant reproduce this, perhaps there are some more steps needed to reproduce?

Until you make changes in a document the Discard / Save buttons should be disabled. Can you tell me if they get enabled for you even without doing anything?

**Comment by shamoon** [comment] 2022-08-06 15:11
Actually, what I can reproduce is that the "unsaved changes" state doesnt seem to properly clear e.g. if I open a document, make some changes but dont save them using the close document popup, it still shows me this prompt. Either thats different than what youre seeing or its just a little more specific, please let us know

**Comment by r2ixuz** [comment] 2022-08-06 15:22
Hmm, I think you are right. This does only happens if one made changes and do not saved them. I imagine just open and close a document is sufficient to show this popup. But you are right I guess.

**Comment by shamoon** [comment] 2022-08-07 22:44
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/ef0080b0a9b861a71412ffaa6f088477a6bbfc50

**Closed by shamoon** 2022-08-07 22:44 UTC
Labels: bug, frontend, fixed in next release
