### ISSUE TITLE
[BUG] auditlog not part of export manifest.json

### ISSUE THREAD

**Issue by trunneml** [paperless-ngx/paperless-ngx#6247] opened 2024-04-01 20:14 UTC
### Description

The created `manifest.json` from `docker compose exec webserver document_exporter ../export` doesn't contain the audit log activated with `PAPERLESS_AUDIT_LOG_ENABLED`

### Steps to reproduce

1. Activate `PAPERLESS_AUDIT_LOG_ENABLED`
2. Modify some document
3. export data with `docker compose exec webserver document_exporter ../export`
4. view manifest.json

### Webserver logs

```bash
None
```

### Paperless-ngx version

v2.6.3

### Host OS

debian

### Installation method

Docker - official image

### Configuration changes

PAPERLESS_AUDIT_LOG_ENABLED

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-04-01 20:32
Feel free to create a PR.

**Comment by shamoon** [comment] 2024-04-01 21:13
Closing as a duplicate of #6244, they go together (as would any fix)

**Closed by shamoon** 2024-04-01 21:13 UTC
Labels: bug, unconfirmed
