### ISSUE TITLE
[BUG] All document upload fail after setting up paperless-ngx with install script

### ISSUE THREAD

**Issue by am93** [paperless-ngx/paperless-ngx#3216] opened 2023-04-27 17:52 UTC
### Description

I have setup my paperless on Ubuntu 20.04 using provided install script. Most of the configs were left as default as seen on script summary below:

```
Summary
=======

Target folder: /home/amedved/Software/paperless-ngx
Consume folder: /home/amedved/Software/paperless-ngx/consume
Media folder: /home/amedved/Software/paperless-ngx/documentstorage
Data folder: /home/amedved/Software/paperless-ngx/documentindex
Database folder: /home/amedved/Software/paperless-ngx/documentdb

URL:
Port: 4242
Database: postgres
Tika enabled: yes
OCR language: slv+eng
User id: 1000
Group id: 1000

Paperless username: amedved
Paperless email: #############@gmail.com

Press any key to install
```

I checked the UID and GID of current user on the machine and it matched. Additionaly I added `chmod a+w` on all folders used by paperless.

I successfully logged in the WEB UI, but when I try to upload any PDF I always get failed task with reason: `Content type for given perms and klass differs` 

![image](https://user-images.githubusercontent.com/9057292/234947923-c82bab87-3c0f-4944-9dec-cc14e480edfb.png)

I tried to solve the issue by adding all rights to my current user:
![image](https://user-images.githubusercontent.com/9057292/234948716-025eb415-fe77-42dd-aa6b-5f102de193b1.png)
![image](https://user-images.githubusercontent.com/9057292/234948857-053ece34-1a7b-4d79-9398-ec80aa5293ea.png)

### Steps to reproduce

1. Install paperless-ngx using provided install script
2. Use configs as shown in the summary above
3. Login into WEB UI
4. Try to upload PDF via main dashboard

### Webserver logs

```bash
[2023-04-27 19:48:17,169] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[d94b9d62-b66e-492f-8dfc-3e13887e33f3] received
[2023-04-27 19:48:17,196] [INFO] [paperless.consumer] Consuming Racun.pdf
[2023-04-27 19:48:17,650] [ERROR] [ocrmypdf._exec.ghostscript]    **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.

[2023-04-27 19:48:18,342] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 14.62 - rotation appears correct
[2023-04-27 19:48:18,782] [ERROR] [ocrmypdf._exec.ghostscript]    **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.
   **** Error: stream operator isn't terminated by valid EOL.
               Output may be incorrect.

[2023-04-27 19:48:24,945] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:48:25,505] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.23 savings: 18.5%
[2023-04-27 19:48:25,506] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
[2023-04-27 19:48:28,465] [ERROR] [paperless.consumer] The following error occurred while consuming Racun.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:48:28,476] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[d94b9d62-b66e-492f-8dfc-3e13887e33f3] raised unexpected: ConsumerError('Racun.pdf: The following error occurred while consuming Racun.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: Racun.pdf: The following error occurred while consuming Racun.pdf: Content type for given perms and klass differs
[2023-04-27 19:49:36,836] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[bd44246c-a213-4296-9672-9188d66736d2] received
[2023-04-27 19:49:36,863] [INFO] [paperless.consumer] Consuming 07. GP_Informatika.pdf
[2023-04-27 19:49:37,411] [INFO] [ocrmypdf._sync] Start processing 12 pages concurrently
[2023-04-27 19:49:37,462] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,463] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,464] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,465] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,465] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
[2023-04-27 19:49:37,487] [INFO] [ocrmypdf._sync] Postprocessing...
[2023-04-27 19:49:38,571] [WARNING] [ocrmypdf._pipeline] Some input metadata could not be copied because it is not permitted in PDF/A. You may wish to examine the output PDF's XMP metadata.
[2023-04-27 19:49:38,722] [INFO] [ocrmypdf._pipeline] Optimize ratio: 1.00 savings: 0.5%
[2023-04-27 19:49:38,727] [INFO] [ocrmypdf._sync] Output file is a PDF/A-2B (as expected)
[2023-04-27 19:49:39,791] [ERROR] [paperless.consumer] The following error occurred while consuming 07. GP_Informatika.pdf: Content type for given perms and klass differs
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs
[2023-04-27 19:49:39,801] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[bd44246c-a213-4296-9672-9188d66736d2] raised unexpected: ConsumerError('07. GP_Informatika.pdf: The following error occurred while consuming 07. GP_Informatika.pdf: Content type for given perms and klass differs')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/asgiref/sync.py", line 302, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 434, in try_consume_file
    document_consumption_finished.send(
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/src/paperless/src/documents/signals/handlers.py", line 38, in add_inbox_tags
    tags = get_objects_for_user_owner_aware(
  File "/usr/src/paperless/src/documents/permissions.py", line 111, in get_objects_for_user_owner_aware
    objects_with_perms = get_objects_for_user(
  File "/usr/local/lib/python3.9/site-packages/guardian/shortcuts.py", line 534, in get_objects_for_user
    raise MixedContentTypeError("Content type for given perms and "
guardian.exceptions.MixedContentTypeError: Content type for given perms and klass differs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 190, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 493, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 96, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 07. GP_Informatika.pdf: The following error occurred while consuming 07. GP_Informatika.pdf: Content type for given perms and klass differs
```

### Paperless-ngx version

1.14.1

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Edge and Chrome

### Configuration changes

None

### Other

None

**Comment by stumpylog** [comment] 2023-04-27 17:53
Duplicate of #3213

**Closed by stumpylog** 2023-04-27 17:53 UTC
Labels: bug, unconfirmed
