### ISSUE TITLE
[BUG] PDF consumation fails with SubprocessOutputError, calling ocrmypdf works

### ISSUE THREAD

**Issue by jjarolim** [paperless-ngx/paperless-ngx#4440] opened 2023-10-25 09:48 UTC
### Description

Hi!

I'm running paperless-ngx as docker-composer bundle. 
Paperless tries to consume a PDF and stops with the following error log:

`[2023-10-25 09:16:18,470] [ERROR] [paperless.consumer] Error occurred while consuming document 20231024_155647_v2.pdf: SubprocessOutputError: . See logs for more information.`

As [recommended here](https://github.com/paperless-ngx/paperless-ngx/issues/4317), I tried to start the OCR process manually directly in the container:

`ocrmypdf --verbose --redo-ocr --rotate-pages --rotate-pages-threshold 12 --clean --output-type pdfa-3 --language deu+eng /usr/src/paperless/consume/20231024_155647.pdf /tmp/paperless/test.pdf`

That worked flawlessly.

### Steps to reproduce

1. Put file in consumer folder
2. 

### Webserver logs

```bash
[2023-10-25 09:15:52,809] [INFO] [paperless.consumer] Consuming 20231024_155647_v2.pdf
[2023-10-25 09:15:52,870] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2023-10-25 09:15:52,872] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2023-10-25 09:15:52,876] [DEBUG] [paperless.consumer] Parsing 20231024_155647_v2.pdf...
[2023-10-25 09:15:53,004] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxztlv2zj0/20231024_155647_v2.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-tospf2ke/archive.pdf'), 'use_threads': True, 'jobs': 8, 'language': 'eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-tospf2ke/sidecar.txt')}
[2023-10-25 09:16:18,470] [ERROR] [paperless.consumer] Error occurred while consuming document 20231024_155647_v2.pdf: SubprocessOutputError: . See logs for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 220, in get_deskew
    p = run(args_tesseract, stdout=PIPE, stderr=STDOUT, timeout=timeout, check=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/subprocess/__init__.py", line 62, in run
    proc = subprocess_run(args, env=env, check=check, **kwargs)
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['tesseract', '-l', 'eng', '--psm', '2', '/tmp/ocrmypdf.io.ypm22njv/000010_rasterize.png', 'stdout']' returned non-zero exit status 1.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse
    ocrmypdf.ocr(**args)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 347, in ocr
    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 391, in run_pipeline
    optimize_messages = exec_concurrent(context, executor)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 279, in exec_concurrent
    executor(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 85, in __call__
    self._execute(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute
    result = future.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 196, in exec_page_sync
    ocr_image, preprocess_out = make_intermediate_images(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 139, in make_intermediate_images
    preprocess_out = preprocess(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 110, in preprocess
    image = preprocess_deskew(image, page_context)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 530, in preprocess_deskew
    deskew_angle_degrees = ocr_engine.get_deskew(input_file, page_context.options)
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/tesseract_ocr.py", line 227, in get_deskew
    return tesseract.get_deskew(
  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_exec/tesseract.py", line 231, in get_deskew
    raise SubprocessOutputError() from e
ocrmypdf.exceptions.SubprocessOutputError
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/documents/consumer.py", line 425, in try_consume_file
    document_parser.parse(self.path, mime_type, self.filename)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 344, in parse
    raise ParseError(
documents.parsers.ParseError: SubprocessOutputError: . See logs for more information.
```

### Paperless-ngx version

1.17.4

### Host OS

Debian GNU/Linux 10 (buster), x86_64

### Installation method

Docker - official image

### Browser

chrome

### Configuration changes

nothing really

**Comment by stumpylog** [comment] 2023-10-25 13:21
The command you are running does not match what paperless is running.

**Comment by stumpylog** [comment] 2023-10-25 14:03
Yes, looking at the traceback from a larger screen, this is just a duplicate of #4317.  You can disable deskew, either for this file or in general, since that appears to be where Tesseract is failing.  There's nothing more that paperless can do.

**Closed by stumpylog** 2023-10-25 14:03 UTC
Labels: cant-reproduce
