### ISSUE TITLE
[BUG] Can't upload PDF because of pixel limitation

### ISSUE THREAD

**Issue by bramvdzee** [paperless-ngx/paperless-ngx#4270] opened 2023-09-26 16:03 UTC
### Description

Paperless is not able to upload my PDF because of of pixel limitation:
`DecompressionBombError: Image size (1994056098 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.`

Upping the limitation and timeout parameters just makes it crash because of memory issues.

### Steps to reproduce

1. Go to paperless
2. Upload a complex PDF (for example: schematic drawings)
3. Wait for error to occur

### Webserver logs

```bash
documents.parsers.ParseError: DecompressionBombError: Image size (1994056098 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.

[2023-09-26 17:46:08,494] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[168e0dc2-44a1-4185-9586-ff28f88c7692] raised unexpected: ConsumerError('name.pdf: Error occurred while consuming document name.pdf: DecompressionBombError: Image size (1994056098 pixels) exceeds limit of 500000000 pixels, could be decompression bomb DOS attack.')

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 321, in parse

    ocrmypdf.ocr(**args)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/api.py", line 347, in ocr

    return run_pipeline(options=options, plugin_manager=plugin_manager, api=True)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 391, in run_pipeline

    optimize_messages = exec_concurrent(context, executor)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 279, in exec_concurrent

    executor(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_concurrent.py", line 85, in __call__

    self._execute(

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/builtin_plugins/concurrency.py", line 141, in _execute

    result = future.result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result

    return self.__get_result()

  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result

    raise self._exception

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_sync.py", line 191, in exec_page_sync

    rasterize_preview_out = rasterize_preview(page_context.origin, page_context)

  File "/usr/local/lib/python3.9/site-packages/ocrmypdf/_pipeline.py", line 363, in rasterize_preview

    page_context.plugin_manager.hook.rasterize_pdf_page(

  File "/usr/local/lib/python3.9/site-packages/pluggy/_hooks.py", line 433, in __call__

    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)

  File "/usr/local/lib/python3.9/site-packages/pluggy/_manager.py", line 112, in _hookexec

    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
```

### Browser logs

```bash
-
```

### Paperless-ngx version

1.17.4

### Host OS

Ubuntu 20.04

### Installation method

Docker - official image

### Browser

Firefox

**Comment by shamoon** [comment] 2023-09-26 16:17
Duplicate of https://github.com/paperless-ngx/paperless-ngx/issues/416 https://github.com/paperless-ngx/paperless-ngx/issues/709 https://github.com/paperless-ngx/paperless-ngx/issues/3022

The conclusion then was this isn't something we can handle on the p-ngx side

If others have different thoughts this can be readdressed

**Closed by shamoon** 2023-09-26 16:17 UTC
Labels: bug, unconfirmed

**Comment by stumpylog** [comment] 2023-09-26 16:55
That's not a memory issue.  It's a setting from PIL which OCRMyPdf also respects.  It's already configurable: https://docs.paperless-ngx.com/configuration/#PAPERLESS_OCR_MAX_IMAGE_PIXELS
