### ISSUE TITLE
[BUG] install-paperless-ngx.sh -> line 318: head --bytes 64 failing on alpine linux due to lack of coreutils

### ISSUE THREAD

**Issue by scherddel** [paperless-ngx/paperless-ngx#5411] opened 2024-01-15 18:35 UTC
### Description

When installing paperless-ngx in alpine linux with docker it seems the installation script which is curled is failing on line 318 due to the lack of coreutils and the minimal implementation of "head".

### Steps to reproduce

1. Install Alpine Linux (in my case 3.18)
2. Install docker and docker-compose
3. Run bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/main/install-paperless-ngx.sh)"

### Webserver logs

```bash
-
```

### Paperless-ngx version

latest

### Host OS

Alpine Linux

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-01-15 19:11
Feel free to submit a pull request to update anything alpine needs.  But I don't think we're going to try and support this in some special way

**Comment by scherddel** [comment] 2024-01-15 19:17
I dont think some special way is needed, just replace command head with dd:
SECRET_KEY=$(LC_ALL=C tr -dc 'a-zA-Z0-9!"#$%&'\''()*+,-./:;<=>?@[\]^_`{|}~' < /dev/urandom | dd bs=1 count=64 2>/dev/null)

Should work on all other linux distributions... Didnt want to make a huge drama out of it ;-) The rest is working fine

**Comment by stumpylog** [comment] 2024-01-16 02:28
If you can make a PR, that would be great

**Comment by shamoon** [comment] 2024-01-23 20:33
Well, in the interest of moving this along I tried making a branch for this ( fix/5411 ) and confirmed it works for me in macOS and my Ubuntu machine at least

@scherddel Can you test it out? bash -c "$(curl --location --silent --show-error https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/7cfa0966edfbc33432248dc4f26f94d26e1eeff7/install-paperless-ngx.sh)"

**Closed** 2024-01-23 22:25 UTC
Labels: bug, deployment
