### ISSUE TITLE
[BUG] (2.0.0-RC-1) "'NoneType' object is not iterable" when POSTing a document with tags

### ISSUE THREAD

**Issue by LeoKlaus** [paperless-ngx/paperless-ngx#4666] opened 2023-11-23 14:15 UTC
### Description

The consumer fails with error "'NoneType' object is not iterable", whenever one or more tags are supplied in the request.

### Steps to reproduce

Post a document to the /api/documents/post_document/ endpoint and include a tag.
Example:
``` bash
curl --request POST \
  --url https://my.server/api/documents/post_document/ \
  --header 'Authorization: Basic Z****************g==' \
  --header 'Content-Type: multipart/form-data' \
  --form tags=8 \
  --form document=@/path/to/sample.pdf
```

### Webserver logs

```bash
[2023-11-23 15:13:28,839] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[785c1a27-66e3-4123-bf7c-e69aca8b1e8b] received
[2023-11-23 15:13:28,887] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[785c1a27-66e3-4123-bf7c-e69aca8b1e8b] raised unexpected: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/tasks.py", line 164, in consume_file
    overrides.update(template_overrides)
  File "/usr/src/paperless/src/documents/data_models.py", line 56, in update
    self.tag_ids.extend(other.tag_ids)
TypeError: 'NoneType' object is not iterable
```

### Paperless-ngx version

Paperless-ngx 2.0.0-beta.rc1

### Host OS

Ubuntu 22.04 ARM

### Installation method

Docker - official image

**Comment by stumpylog** [comment] 2023-11-23 15:09
Duplicate of #4593

**Closed by stumpylog** 2023-11-23 15:09 UTC
Labels: bug, unconfirmed

**Comment by shamoon** [comment] 2023-11-23 15:11
Seems like a duplicate of #4593 (see #4598), before I check, are you certain you're still seeing this in the most recent `beta` image, 6b6fba741044ee1d45c6329795171880ad3c1663976bd4f551f82bbbdf31c6c0 ?

**Comment by LeoKlaus** [comment] 2023-11-23 15:23
Yup, fixed after switching to the beta tag, sorry. 
Thank you for all the work and quick reply!
