### ISSUE TITLE
[BUG] Guicorn not starting when IPv6 is disabled

### ISSUE THREAD

**Issue by KenADev** [paperless-ngx/paperless-ngx#1455] opened 2022-08-24 11:11 UTC
### Description

Using the Docker-Images, I tried to upgrade from v1.7.1 to v1.8.0 today.
Migrations worked, but guicorn does not come up anymore and shows this error in the logs:
`Guicorn Cant connect to ('::', '8000')`

It seems to me that guicorn crashes because it can't build a connection via IPv6, which is disabled on my host.

### Steps to reproduce

1. Try to run the 1.8.0 Docker-Container on a Host with IPv6 disabled

### Webserver logs

```bash
--
```

### Paperless-ngx version

v1.8.0

### Host OS

Ubuntu 20.04 LTS

### Installation method

Docker - official image

### Browser

--

### Configuration changes

Update from v1.7.1 to 1.8.0 with docker-compose pull

**Comment by shamoon** [comment] 2022-08-24 11:20
Duplicate of #1356 and #1386
Wil be fixed in next release

**Closed by shamoon** 2022-08-24 11:20 UTC
Labels: bug, unconfirmed
