### ISSUE TITLE
[BUG] Tags cannot be set or unset

### ISSUE THREAD

**Issue by fantasticle** [paperless-ngx/paperless-ngx#2300] opened 2023-01-01 11:05 UTC
### Description

I added documents that are automatically tagged by the ML algorithm. When trying to edit them in my views I can neither set nor unset tags. They are not pre-selected. When I try to add them manually nothing happens.

This seems to be only a problem in the views (.../view/1) or document overview (.../documents). When I edit the document one by one (.../documents/1234) setting or unsetting works just fine.

<img width="660" alt="Bildschirm­foto 2023-01-01 um 11 58 17" src="https://user-images.githubusercontent.com/84633558/210168394-c73c4b26-708d-4643-ae0d-4678976d17f2.png">

### Steps to reproduce

1. Upload document.
2. Select it and try to set tags via the dropdown in your views or document overview.

### Paperless-ngx version

1.11.2

### Host OS

Ubuntu 20.04 LTS

### Installation method

Docker - official image

### Browser

Chrome, Firefox

### Configuration changes

None that matter

**Comment by OddSquirrel** [comment] 2023-01-01 12:38
The maintainer is aware of it, 1.11.3 is supposed to address it. 

https://github.com/paperless-ngx/paperless-ngx/discussions/2288#discussioncomment-4560939

**Comment by shamoon** [comment] 2023-01-01 15:25
Dupe of https://github.com/paperless-ngx/paperless-ngx/discussions/2286 https://github.com/paperless-ngx/paperless-ngx/issues/2287 https://github.com/paperless-ngx/paperless-ngx/discussions/2288 https://github.com/paperless-ngx/paperless-ngx/issues/2291 #2297 —> https://github.com/paperless-ngx/paperless-ngx/pull/2292

**Closed by shamoon** 2023-01-01 15:25 UTC
Labels: bug, unconfirmed
