### ISSUE TITLE
[BUG] 404 after saving document with wrong date

### ISSUE THREAD

**Issue by CodeBrauer** [paperless-ngx/paperless-ngx#1004] opened 2022-05-22 10:36 UTC
### Description

When copying from a document with a space and pasting it into the date field, the date field does not trim the whitespace and parses the date wrong.

Example: `05.10.2020` gets `10.05.0202`

<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/2059754/169690141-91ab8767-c992-459d-a180-7d8854054df8.png">
</details>

After saving this document and trying to reopen/edit paperless shows 404 and undefined it the browser title. 

### Steps to reproduce

1. Upload the document [demo.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8749204/demo.pdf)
2. Edit the document
3. Copy the date from the document from the preview with a leading space
4. paste it to the date field
5. save it
6. try to open/edit it.
7. browser show 404

After this, the document can be fixed using the Administration view (/admin). Just edit the date to the correct date and save it.

### Webserver logs

```bash
No log entries available
```

### Paperless-ngx version

1.7.1

### Host OS

DietPi v8.4.2

### Installation method

Docker

### Browser

Chrome

**Comment by shamoon** [comment] 2022-05-22 15:46
Well theres a character limit on that field to help with keyboard input, when you enter `05 .10.2020` it actually sees only `05 .10.202` so it is correctly stripping the whitespace but then seeing the year to `202`. But what Im not seeing is the 404, see video. Are you certain you're on 1.7.1? There was a fix in that version that probably prevented the 404 issue.

As for the date parsing, we can detect paste and improve this a bit. I'll open a PR later.

https://user-images.githubusercontent.com/4887959/169703938-fc6a4846-2de9-4633-8043-8ec9c695c526.mov

**Comment by CodeBrauer** [comment] 2022-05-25 08:10
In my case, the value was ` 05.10.2020` (leading space)
My date settings are:
<img width="458" alt="Bildschirmfoto 2022-05-25 um 10 09 43" src="https://user-images.githubusercontent.com/2059754/170213782-0496e739-5a9e-45a0-888a-58ca4c48fe0f.png">

**Comment by shamoon** [comment] 2022-05-25 20:48
Yea, oddly I still cant reproduce the 404 issue on 1.7.1, anyway I hope the pr above will help the pasting issue and once its released we can always see if the issue persists for you.

**Comment by qcasey** [comment] 2022-05-26 15:51
The pasting issue is fixed as of #1007. Please comment on next release if the 404s still occur and we can reopen.

**Closed by qcasey** 2022-05-26 15:51 UTC
Labels: bug, frontend

**Comment by Cantello** [comment] 2022-06-23 06:37
Same here with the 404. One document apparently had a wrong date entered (1009 instead of 2009, at least that's what is stored in the filename) and now I get the same 404 as above when trying to access the file. In the frontend, the date is shown as not set (can provide videos/screenshots if needed).
Any idea how I could get the document back into the system? The sanity_checker does not report anything unusual and simply renaming the file does (of course) not work.

**Comment by CodeBrauer** [comment] 2022-06-23 07:09
@Cantello I was able to successfully find and change the document via the backend (`/admin`). After that the frontend showed the document just fine.

**Comment by Cantello** [comment] 2022-06-23 07:11
> @Cantello I was able to successfully find and change the document via the backend (`/admin`). After that the frontend showed the document just fine.

You are right, I am always forgetting that you can change metadata there as well - thanks!
