### ISSUE TITLE
[BUG] Searching with added since does not work anymore with 1.12.0

### ISSUE THREAD

**Issue by chrisonline** [paperless-ngx/paperless-ngx#2514] opened 2023-01-25 20:27 UTC
### Description

I can't search for added since for example 7 days anymore.  

Error Message:  
Fehler beim Laden des Dokuments: 'DateRange' object has no attribute 'subqueries'

In console:  
'DateRange' object has no attribute 'subqueries'

![image](https://user-images.githubusercontent.com/2077218/214682586-7a7a0309-25f2-4347-bc91-9b27f7cb3100.png)

### Steps to reproduce

1. Go to documemts
2. Click on the button "Date Added" and select for example 7 days

### Webserver logs

```bash
main.js:3 WebSocket connection to 'wss://xx.xxx.at/ws/status/' failed: 
connect @ main.js:3
api/documents/?page=1&page_size=10&ordering=-added&query=added:%5B-1%20week%20to%20now%5D:1          Failed to load resource: the server responded with a status of 400 ()
main.js:3 ERROR iw
handleError @ main.js:3
DevTools failed to load source map: Could not load content for chrome-extension://kjacjjdnoddnpbbcjilcajfhhbdhkpgk/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
polyfills.js:1          GET https://xxx.xxxx.at/api/documents/?page=1&page_size=50&ordering=-added&truncate_content=true&query=added:%5B-1%20week%20to%20now%5D 400
z @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMacroTask @ polyfills.js:1
Me @ polyfills.js:1
(anonymous) @ polyfills.js:1
o.<computed> @ polyfills.js:1
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
K @ main.js:3
x @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
Br @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
reload @ main.js:3
set filterRules @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
next @ main.js:3
updateRules @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
next @ main.js:3
emit @ main.js:3
onChange @ main.js:3
setRelativeDate @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
(anonymous) @ main.js:3
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:3
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
F @ polyfills.js:1
polyfills.js:1          GET https://paperless.chrisonline.at/api/documents/?page=1&page_size=50&ordering=-added&truncate_content=true&query=added:%5B-1%20month%20to%20now%5D 400
z @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMacroTask @ polyfills.js:1
Me @ polyfills.js:1
(anonymous) @ polyfills.js:1
o.<computed> @ polyfills.js:1
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
K @ main.js:3
x @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
Br @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
reload @ main.js:3
set filterRules @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
next @ main.js:3
updateRules @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
next @ main.js:3
emit @ main.js:3
onChange @ main.js:3
setRelativeDate @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
(anonymous) @ main.js:3
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:3
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
F @ polyfills.js:1
polyfills.js:1          GET https://paperless.chrisonline.at/api/documents/?page=1&page_size=50&ordering=-added&truncate_content=true&query=added:%5B-1%20week%20to%20now%5D 400
z @ polyfills.js:1
scheduleTask @ polyfills.js:1
onScheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleTask @ polyfills.js:1
scheduleMacroTask @ polyfills.js:1
Me @ polyfills.js:1
(anonymous) @ polyfills.js:1
o.<computed> @ polyfills.js:1
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
K @ main.js:3
x @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
_trySubscribe @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
Br @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
subscribe @ main.js:3
reload @ main.js:3
set filterRules @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
next @ main.js:3
updateRules @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
next @ main.js:3
_next @ main.js:3
next @ main.js:3
(anonymous) @ main.js:3
H @ main.js:3
next @ main.js:3
emit @ main.js:3
onChange @ main.js:3
setRelativeDate @ main.js:3
(anonymous) @ main.js:3
Wb @ main.js:3
r @ main.js:3
(anonymous) @ main.js:3
invokeTask @ polyfills.js:1
onInvokeTask @ main.js:3
invokeTask @ polyfills.js:1
runTask @ polyfills.js:1
invokeTask @ polyfills.js:1
Z @ polyfills.js:1
N @ polyfills.js:1
F @ polyfills.js:1
```

### Paperless-ngx version

1.12.0

### Host OS

Synology NAS

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment] 2023-01-25 20:29
Duplicate of #2511

**Closed by stumpylog** 2023-01-25 20:29 UTC
Labels: bug, unconfirmed
