### ISSUE TITLE
[BUG] Authentication requires libpq version 10 or above

### ISSUE THREAD

**Issue by jhoogstraat** [paperless-ngx/paperless-ngx#266] opened 2022-03-11 11:34 UTC
**Describe the bug**
The following error is reported when starting paperless on my Raspberry Pi:
`ERROR SCRAM authentication requires libpq version 10 or above`
This results in a Server Error 500 after logging in.

**To Reproduce**
1. `docker-compose.yml`:
```
version: "3.4"

networks:
  default:
    external: true
    name: ${CADDY_NETWORK}

services:
  broker:
    image: redis:6.0
    volumes:
      - ./redis:/data
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    restart: unless-stopped

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: ${CONTAINER_NAME_PAPERLESS}
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      USERMAP_UID: 1001
      USERMAP_GID: 1001
      PAPERLESS_TIME_ZONE: ${TZ}
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    restart: unless-stopped
    depends_on:
      - db
      - broker
      - gotenberg
      - tika

  gotenberg:
    image: gotenberg/gotenberg:7
    environment:
      CHROMIUM_DISABLE_ROUTES: 1
    restart: unless-stopped

  tika:
    image: iwishiwasaneagle/apache-tika-arm
    restart: unless-stopped
```
2. `docker compose run --rm paperless createsuperuser`
3. `docker compose down && docker compose up -d`

**Expected behavior**
Paperless should start correctly.

**Webserver logs**
```
12:19:59 [Q] ERROR Failed [louisiana-uncle-magnesium-eleven] - SCRAM authentication requires libpq version 10 or above
 : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: SCRAM authentication requires libpq version 10 or above


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/src/paperless/src/paperless_mail/tasks.py", line 12, in process_mail_accounts
    for account in MailAccount.objects.all():
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 280, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: SCRAM authentication requires libpq version 10 or above


12:20:00 [Q] INFO recycled worker Process-1:2
12:20:00 [Q] INFO Process-1:6 ready for work at 85
12:21:00 [Q] ERROR SCRAM authentication requires libpq version 10 or above
```

**Relevant information**
 - Host OS of the machine running paperless: Raspberry Pi OS (64bit)
 - Version: 1.6.0
 - Installation method: docker

**Comment by stumpylog** [comment] 2022-03-11 23:07
Inside the paperless container, could you run `dpkg -l | grep libpq`?

Maybe related: psycopg/psycopg2#1396

The `Pipfile` includes psycopg2-binary.  The seeming solution above is we'll need to build this from source like we do pikepdf and some others.  psycopg2 actually suggests building from source for production as well.

**Comment by stumpylog** [comment] 2022-03-12 00:11
That's what I figured.  There is some ongoing work to build certain packages from source.  This is probably going to be one that also needs to be included in there.  Thanks for gathering that information for me.

The root cause:
1. psycopg2 builds its aarch64 wheels using manylinux_2_24 ([ref 1](https://github.com/psycopg/psycopg2/blob/c34bf2f2f90fbbe65e8c4c2650734aa151ddd6ed/.github/workflows/packages.yml#L62))
2. manylinux_2_24 is based on Debian 9 ([ref 2](https://github.com/pypa/manylinux#manylinux_2_24-debian-9-based))
3. Debian 9 includes libpq-dev 9.6.24 (ie 90624).  ([ref 3](https://packages.debian.org/stretch/libpq-dev)

**Comment by stumpylog** [comment] 2022-03-12 03:03
It can probably be done as part of that. We're already going to build more wheels for armv7 and aarch64.  I'd leave the final say up to @schnuffle

**Comment by schnuffle** [comment] 2022-03-14 11:55
I'll have a look into it as soon as I've been able to get my workflow stable and squished out all small problems.

For the moment I'm going even deeper into the rabid whole  as I decided the cleanest route is to backport packages. That gives me all debian build checks/tests.
I'm nearly at it, in the end only a minor patch to the control file of pikepdf has been necessary ( build depends: python3-sphinx-panels, which doesn't exist non bullseye but a manual install with removing the build deps seems to work )

Regards
Schnuffle

**Comment by schnuffle** [comment] 2022-03-15 22:26
I  finally have an image I think should work as base for armv7 and arm64.
Adding psycopg2 has been copy paste so added the psycopg2 build into it as well.

I will create a paperless image manually, to see if that holds true when running it.
 When that is sucessfull. we might start to think about how and what parts we want to integrate into the paperless-ngx workflow

Regards

Schnuffle

**Comment by shamoon** [comment] 2022-04-04 17:54
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/9737e4a24d9bd2378204fd67e3458e543fe3ed1c

**Closed by shamoon** 2022-04-04 17:54 UTC
Labels: backend
