### ISSUE TITLE
[BUG] Date picker not correct

### ISSUE THREAD

**Issue by gdh2024-gdh** [paperless-ngx/paperless-ngx#7552] opened 2024-08-27 01:53 UTC
### Description

The date piker in paperless-ngx is not correct.  when clicking on Date and clicking the calendar icon to pick the date, the days are off by one day.  For example if picking Aug 26, 2024 it will show in the calendar as Sunday and not Monday

<img width="227" alt="Screenshot 2024-08-26 214715" src="https://github.com/user-attachments/assets/d89a2525-ff96-4340-b438-a745a0e66167">

### Steps to reproduce

1. Click on "Date"
2. Click the calendar icon for either After or Before
3. Notice today is  Monday 26 Aug 2024 but 26 on the calendar shows under the S column for Sunday.

### Webserver logs

```bash
No log collected
```

### Paperless-ngx version

2.11.6

### Host OS

Ubuntu

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-08-27 02:10
A quick search would easily find this is a duplicate of #7410

**Closed by stumpylog** 2024-08-27 02:10 UTC
Labels: bug, unconfirmed

**Comment by gdh2024-gdh** [comment] 2024-08-27 02:17
Seems from looking at https://ng-bootstrap.github.io/#/components/datepicker/overview the issue is fixed there but not in paperless-ngx 2.11.6.

**Comment by gdh2024-gdh** [comment] 2024-08-27 02:35
> Hi @stumpylog Seems from looking at https://ng-bootstrap.github.io/#/components/datepicker/overview the issue is fixed there but not in paperless-ngx 2.11.6. Maybe I'm missing something. :)

Digging deeper it seems maybe the folks working on datepicker component have yet to fully fix it.  Not good for people depending on it.  Hopefully it gets fixed soon.  :)
