### ISSUE TITLE
[BUG] Can't import document paperless-ngx

### ISSUE THREAD

**Issue by Nautilus34** [paperless-ngx/paperless-ngx#6651] opened 2024-05-09 10:38 UTC
### Description

Hello, 

It's impossible to import documents because of a conversion error between UTF8 and SQL_ASCII.

### Steps to reproduce

I followed the bare-metal procedure to install Paperless-ngx with Postgres DB on debian.

### Webserver logs

```bash
[2024-05-07 22:30:24,723] [ERROR] [paperless.consumer] The following error occurred while storing document XXX.pdf after parsing: conversion between UTF8 and SQL_ASCII is not supported
```

### Paperless-ngx version

Paperless-ngx 2.8.1

### Host OS

Debian 12

### Installation method

Bare metal

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by Nautilus34** [comment] 2024-05-09 10:46
Hello, 

I find a solution to fix this problem, It is necessary to recreate a PostgreSQL DB that accepts UTF8 instead of SQL_ASCII.

**- Close connexion to the DB** 

1. sudo -u postgres psql -c "SELECT pid, usename, datname, client_addr, state FROM pg_stat_activity WHERE datname = 'paperlessdb';"
2. sudo -u postgres psql -c "SELECT pg_terminate_backend(1234);"

**- Create a backup** 

1. sudo -u postgres pg_dump -Fc paperlessdb > paperlessdb_backup.dump

**- Delete the DB**

1. sudo -u postgres dropdb paperlessdb

**- Create a db with UTF8 encoding**

1. sudo -u postgres createdb --template=template0 --encoding='UTF8' --locale='en_US.UTF-8' paperlessdb

**- Restore the backup** 

1. sudo -u postgres pg_restore -d paperlessdb paperlessdb_backup.dump

Now you can import documents in paperless without issue.

**Comment by stumpylog** [comment] 2024-05-09 13:07
Duplicate of several other issues that I'm not going to find on mobile.  Utf8; is the only supported database encoding and is the default encoding.

**Closed by stumpylog** 2024-05-09 13:07 UTC
Labels: bug, unconfirmed

**Comment by Nautilus34** [comment] 2024-05-09 16:40
Hello @stumpylog , 

Thank you, but it seems that a warning should perhaps be added to the bare metal install documentation, because when I installed PostgreSQL, it used SQL_ASCII encoding instead of UTF-8, so I had to find the solution myself because i didn't solution in the documentation.

Have a good day.

**Comment by shamoon** [comment] 2024-05-09 17:45
Anyone is free to PR the documentation or the project in general

**Comment by JesperDramsch** [comment] 2024-05-09 20:47
Thank you so much. I am using the Proxmox helper script for my paperless-ngx install, which seems to be using the bare metal install. The comment by @Nautilus34 solved my issue by re-encoding the database!

I even had PNGs failing in the ingestion:

```
01-ticket-400.png: The following error occurred while storing document 01-ticket-400.png after parsing: conversion between UTF8 and SQL_ASCII is not supported
LINE 1: ...46', 46, '2024-01-17 01-ticket-400', NULL, 0, '', '{"notes":...
                                                             ^
```

(Leaving this comment for Goole-ability, honestly.)

**Comment by Nautilus34** [comment] 2024-05-10 00:47
Hello @JesperDramsch, 

I'am glad my comment could help you.

Have a good day.
