### ISSUE TITLE
[BUG] regex._regex_core.error: bad escape \d at position 7

### ISSUE THREAD

**Issue by JuliusLongmind** [paperless-ngx/paperless-ngx#1684] opened 2022-09-28 21:32 UTC
### Description

Document cannot be uploaded, due gathering date stuck.

### Steps to reproduce

Upload doc ...

### Webserver logs

```bash
bad escape \d at position 7 : Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/django_q/cluster.py", line 432, in worker
    res = f(*task["args"], **task["kwargs"])
  File "/usr/share/paperless/src/documents/tasks.py", line 154, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/share/paperless/src/documents/consumer.py", line 334, in try_consume_file
    date = parse_date(self.filename, text)
  File "/usr/share/paperless/src/documents/parsers.py", line 221, in parse_date
    return next(parse_date_generator(filename, text), None)
  File "/usr/share/paperless/src/documents/parsers.py", line 280, in parse_date_generator
    yield from __process_content(text, settings.DATE_ORDER)
  File "/usr/share/paperless/src/documents/parsers.py", line 271, in __process_content
    date = __process_match(m, date_order)
  File "/usr/share/paperless/src/documents/parsers.py", line 262, in __process_match
    date = __parser(date_string, date_order)
  File "/usr/share/paperless/src/documents/parsers.py", line 235, in __parser
    return dateparser.parse(
  File "/usr/lib/python3.10/site-packages/dateparser/conf.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/dateparser/__init__.py", line 61, in parse
    data = parser.get_date_data(date_string, date_formats)
  File "/usr/lib/python3.10/site-packages/dateparser/date.py", line 428, in get_date_data
    parsed_date = _DateLocaleParser.parse(
  File "/usr/lib/python3.10/site-packages/dateparser/date.py", line 178, in parse
    return instance._parse()
  File "/usr/lib/python3.10/site-packages/dateparser/date.py", line 182, in _parse
    date_data = self._parsers[parser_name]()
  File "/usr/lib/python3.10/site-packages/dateparser/date.py", line 196, in _try_freshness_parser
    return freshness_date_parser.get_date_data(self._get_translated_date(), self._settings)
  File "/usr/lib/python3.10/site-packages/dateparser/date.py", line 234, in _get_translated_date
    self._translated_date = self.locale.translate(
  File "/usr/lib/python3.10/site-packages/dateparser/languages/locale.py", line 131, in translate
    relative_translations = self._get_relative_translations(settings=settings)
  File "/usr/lib/python3.10/site-packages/dateparser/languages/locale.py", line 158, in _get_relative_translations
    self._generate_relative_translations(normalize=True))
  File "/usr/lib/python3.10/site-packages/dateparser/languages/locale.py", line 172, in _generate_relative_translations
    pattern = DIGIT_GROUP_PATTERN.sub(r'?P<n>\d+', pattern)
  File "/usr/lib/python3.10/site-packages/regex/regex.py", line 710, in _compile_replacement_helper
    is_group, items = _compile_replacement(source, pattern, is_unicode)
  File "/usr/lib/python3.10/site-packages/regex/_regex_core.py", line 1737, in _compile_replacement
    raise error("bad escape \\%s" % ch, source.string, source.pos)
regex._regex_core.error: bad escape \d at position 7
```

### Paperless-ngx version

1.9.2

### Host OS

ArchLinux ARM

### Installation method

Bare metal

### Browser

Firefox

**Comment by shamoon** [comment] 2022-09-28 23:47
Can you provide a file? Without something to test with Im unclear how we can reproduce (/ solve) this, it doesnt seem to be a widespread issue.

**Comment by stumpylog** [comment] 2022-09-29 00:46
This is almost always an issue with the Arch packaging.  Please confirm the regex package is at 2022.3.2.

**Comment by stumpylog** [comment] 2022-09-29 00:50
See also #1188

**Comment by stumpylog** [comment] 2022-09-29 20:39
Duplicate of #1188.  

Looking at it not from my phone, it's more clear this is the same traceback.  I don't know how Arch works, but you'll need to have `regex==2022.3.2`, either in the system or a virtual environment.  Or you could switch to using the Docker image.

**Closed by stumpylog** 2022-09-29 20:39 UTC
Labels: bug, cant-reproduce
