### ISSUE TITLE
[BUG] Document count on tag wrong

### ISSUE THREAD

**Issue by derolli1976** [paperless-ngx/paperless-ngx#7154] opened 2024-07-03 05:48 UTC
### Description

On the "Tags" page the document counter for the Tag ID 2 ("INBOX") is showing 4 documents, but only one single document is found when clicking on the "documents" button for theses tagged docs.
![image](https://github.com/paperless-ngx/paperless-ngx/assets/6522123/0b6270af-c8a5-4f7a-95b9-c8f974c257c8)
![image](https://github.com/paperless-ngx/paperless-ngx/assets/6522123/2ac9918f-8483-44ba-a98a-e6ab48b1c63d)

### Steps to reproduce

No way of reproducing found

### Webserver logs

```bash
Nothing in the logs
```

### Paperless-ngx version

2.10.2

### Host OS

Ubuntu Server 23.10 x86_64

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.10.2",
    "server_os": "Linux-6.5.0-41-generic-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 210779168768,
        "available": 102033432576
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-07-02T09:11:56.902710+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-07-02T12:05:02.885422Z",
        "classifier_error": null
    }
}
```

### Browser

Edge

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-07-03 06:38
I assume this is a duplicate of #7108 but feel free to let us know if otherwise

**Closed by shamoon** 2024-07-03 06:38 UTC
Labels: bug, unconfirmed
