### ISSUE TITLE
[BUG] ASN from QR code is not added to document metadata although barcode is read successfully

### ISSUE THREAD

**Issue by TeamEinstein** [paperless-ngx/paperless-ngx#5772] opened 2024-02-15 10:20 UTC
### Description

When I scan a document with an ASN barcode/QR code, the ASN is not added to the document metadata, even though the logs show that the code has been read. This happens on single documents as well as multiple documents split via PATCHT pages. It does not matter whether the ASN is already in the database or not. Detection of the QR codes and recognition as ASN and insertion of the ASN into the document metadata worked fine before the update from 2.5.1 to 2.5.2 (with the exception of the error fixed in [5745](https://github.com/paperless-ngx/paperless-ngx/pull/5745).

I would be expecting some additional lines in the log (from 2.5.1 last night) that show that the barcode was not only read, but recognized as an ASN:

[2024-02-14 20:56:23,657] [DEBUG] [paperless.barcodes] Found ASN Barcode: ASN0000015

[2024-02-14 20:56:23,658] [INFO] [paperless.barcodes] Found ASN in barcode: 15

But these do not show up.

### Steps to reproduce

1. Add a scanned pdf with a ASN QR code to the consume folder.
2. Document is consumed
3. Document in inbox does not have its ASN set in metadata.
4. Logs show the barcode was read, but does not show recognition as an ASN. Duplicate ASNs are not detected, either.

### Webserver logs

```bash
[2024-02-15 10:57:25,933] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-02-15 10:57:25,934] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin

[2024-02-15 10:57:25,934] [DEBUG] [paperless.barcodes] Scanning for barcodes using ZXING

[2024-02-15 10:57:26,841] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.QRCode found: ASN0000022

[2024-02-15 10:57:26,844] [INFO] [paperless.tasks] BarcodePlugin completed with: No pages to split on!

[2024-02-15 10:57:26,850] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-02-15 10:57:26,853] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with no message

[2024-02-15 10:57:26,876] [INFO] [paperless.consumer] Consuming 2024-02-15.105714 scan_ocr.pdf

[2024-02-15 10:57:26,880] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-02-15 10:57:26,891] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-02-15 10:57:26,896] [DEBUG] [paperless.consumer] Parsing 2024-02-15.105714 scan_ocr.pdf...

[2024-02-15 10:57:27,243] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxafs4pekd/2024-02-15.105714 scan_ocr.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-nv1oe3ig/archive.pdf'), 'use_threads': True, 'jobs': 2, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-nv1oe3ig/sidecar.txt'), 'continue_on_soft_render_error': True, 'invalidate_digital_signatures': True}

[2024-02-15 10:57:48,347] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2024-02-15 10:57:48,347] [DEBUG] [paperless.consumer] Generating thumbnail for 2024-02-15.105714 scan_ocr.pdf...

[2024-02-15 10:57:48,352] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-nv1oe3ig/archive.pdf[0] /tmp/paperless/paperless-nv1oe3ig/convert.webp

[2024-02-15 10:57:51,260] [DEBUG] [paperless.consumer] Saving record to database

[2024-02-15 10:57:51,261] [DEBUG] [paperless.consumer] Creation date from parse_date: 2024-02-15 00:00:00+01:00

[2024-02-15 10:57:52,229] [INFO] [paperless.handlers] Assigning correspondent XXXXX to 2024-02-15 2024-02-15.105714 scan_ocr

[2024-02-15 10:57:52,243] [INFO] [paperless.handlers] Assigning document type XXXXX to 2024-02-15 XXXXX 2024-02-15.105714 scan_ocr

[2024-02-15 10:57:52,268] [INFO] [paperless.handlers] Tagging "2024-02-15 XXXXX 2024-02-15.105714 scan_ocr" with "XXXXX, XXXXX, 2022, XXXXX"

[2024-02-15 10:57:52,585] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxafs4pekd/2024-02-15.105714 scan_ocr.pdf

[2024-02-15 10:57:52,620] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-nv1oe3ig

[2024-02-15 10:57:52,621] [INFO] [paperless.consumer] Document 2024-02-15 XXXXX 2024-02-15.105714 scan_ocr consumption finished
```

### Paperless-ngx version

2.5.2

### Host OS

Ubuntu 22.04, x86_64

### Installation method

Docker - official image

### Browser

Firefox

### Configuration changes

docker-compose.env: PAPERLESS_URL=http://xxxx USERMAP_UID=xxxx USERMAP_GID=xxxx PAPERLESS_TIME_ZONE=Europe/Berlin PAPERLESS_OCR_LANGUAGE=deu+eng PAPERLESS_OCR_USER_ARGS='{"continue_on_soft_render_error": true, "invalidate_digital_signatures": true}' PAPERLESS_SECRET_KEY=xxxxxxx PAPERLESS_FILENAME_FORMAT={correspondent}/{created} {title} PAPERLESS_FILENAME_FORMAT_REMOVE_NONE=True PAPERLESS_FILENAME_DATE_ORDER=YMD PAPERLESS_NUMBER_OF_SUGGESTED_DATES=5 PAPERLESS_IGNORE_DATES=xxxxx PAPERLESS_CONSUMER_RECURSIVE=true PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS=True PAPERLESS_CONSUMER_ENABLE_COLLATE_DOUBLE_SIDED=True PAPERLESS_CONSUMER_COLLATE_DOUBLE_SIDED_SUBDIR_NAME=double-sided PAPERLESS_CONSUMER_COLLATE_DOUBLE_SIDED_TIFF_SUPPORT=True PAPERLESS_CONSUMER_ENABLE_BARCODES=True PAPERLESS_CONSUMER_BARCODE_TIFF_SUPPORT=True PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE=True PAPERLESS_CONSUMER_BARCODE_SCANNER=ZXING 

docker-compose.yml: gotenberg: # image: docker.io/gotenberg/gotenberg:7.8 image: docker.io/gotenberg/gotenberg:latest restart: unless-stopped # The gotenberg chromium route is used to convert .eml files. We do not # want to allow external content like tracking pixels or even javascript. command: - "gotenberg" - "--chromium-disable-javascript=true" - "--chromium-allow-list=file:///tmp/.*" - "--api-timeout=120s"

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-02-15 14:11
Sample file?

**Comment by stumpylog** [comment] 2024-02-15 14:46
With the sample file https://github.com/paperless-ngx/paperless-ngx/blob/dev/src/documents/tests/samples/barcodes/barcode-39-asn-123.pdf I cannot reproduce this.  The ASN is read an assigned as expected.

**Comment by Miicki** [comment] 2024-02-15 15:11
I have the same problem. I tried the test file and it did not work. The ASN was not transferred, but was recognized according to the log.

```
[2024-02-15 15:07:05,759] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/barcode-39-asn-123.pdf to the task queue.

[2024-02-15 15:07:07,042] [DEBUG] [paperless.tasks] Skipping plugin CollatePlugin

[2024-02-15 15:07:07,043] [DEBUG] [paperless.tasks] Executing plugin BarcodePlugin

[2024-02-15 15:07:07,044] [DEBUG] [paperless.barcodes] Scanning for barcodes using ZXING

[2024-02-15 15:07:07,818] [DEBUG] [paperless.barcodes] Barcode of type BarcodeFormat.Code39 found: ASN00123

[2024-02-15 15:07:07,822] [INFO] [paperless.tasks] BarcodePlugin completed with: No pages to split on!

[2024-02-15 15:07:07,829] [DEBUG] [paperless.tasks] Executing plugin WorkflowTriggerPlugin

[2024-02-15 15:07:07,833] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with no message

[2024-02-15 15:07:07,847] [INFO] [paperless.consumer] Consuming barcode-39-asn-123.pdf

[2024-02-15 15:07:07,850] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2024-02-15 15:07:07,867] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2024-02-15 15:07:07,874] [DEBUG] [paperless.consumer] Parsing barcode-39-asn-123.pdf...

[2024-02-15 15:07:08,269] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxkg3rgpj8/barcode-39-asn-123.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-iqr08ed4/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-iqr08ed4/sidecar.txt')}

[2024-02-15 15:07:09,522] [DEBUG] [paperless.parsing.tesseract] Incomplete sidecar file: discarding.

[2024-02-15 15:07:09,577] [DEBUG] [paperless.consumer] Generating thumbnail for barcode-39-asn-123.pdf...

[2024-02-15 15:07:09,585] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-iqr08ed4/archive.pdf[0] /tmp/paperless/paperless-iqr08ed4/convert.webp

[2024-02-15 15:07:11,522] [DEBUG] [paperless.consumer] Saving record to database

[2024-02-15 15:07:11,523] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2024-02-15 15:06:30.067983+00:00

[2024-02-15 15:07:12,514] [INFO] [paperless.handlers] Assigning correspondent Peter Winter GmbH to 2024-02-15 barcode-39-asn-123

[2024-02-15 15:07:12,523] [INFO] [paperless.handlers] Assigning document type Korrespondenz to 2024-02-15 Peter Winter GmbH barcode-39-asn-123

[2024-02-15 15:07:12,542] [INFO] [paperless.handlers] Tagging "2024-02-15 Peter Winter GmbH barcode-39-asn-123" with "Steuern 2023, Haus"

[2024-02-15 15:07:12,768] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxkg3rgpj8/barcode-39-asn-123.pdf

[2024-02-15 15:07:13,314] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-iqr08ed4

[2024-02-15 15:07:13,316] [INFO] [paperless.consumer] Document 2024-02-15 Peter Winter GmbH barcode-39-asn-123 consumption finished
```

**Comment by shamoon** [comment] 2024-02-15 15:13
I think a fix is already in progress

**Closed** 2024-02-15 17:33 UTC
Labels: bug, backend

**Comment by TeamEinstein** [comment] 2024-02-15 19:24
Wow, you guys are fast!

Just to complete the picture: I tried the test file and it shows the same error (barcode is read, but not recocnized as ASN and the ASN is not set in the document metadata.

**Comment by TeamEinstein** [comment] 2024-02-16 09:02
Just a quick update: 

I upgraded to 2.5.3 this morning and tested splitting and ASN detection extensively. It now works as expected: Documents are split by a PATCHT page as well as an ASN QR code. The QR code is read and the ASN detected, and added to the document metadata. Duplicate ASNs are rejected, as expected.

Great work, @stumpylog! Thanks for finding and resolving this so quickly!

**Comment by Miicki** [comment] 2024-02-16 12:27
It works for me again. Many thanks for the quick solution!
