### ISSUE TITLE
[BUG] Tag selector on the documents page isn't working

### ISSUE THREAD

**Issue by hspe98** [paperless-ngx/paperless-ngx#2291] opened 2022-12-31 15:29 UTC
### Description

In 1.10 I had selected the tags for a bunch of documents on the documents page with the tag selector.

Since the update to 1.11.2 this isnt working anymore: The selector does not show the current tags.
![error_tags](https://user-images.githubusercontent.com/7887268/210141576-1ba14f46-9a3e-4f5f-881f-14097c546fe8.png)
_in < 1.11.2 there was a tick in front of the current given tags._

### Steps to reproduce

1. Updated paperless-ngx from 1.10.2 to 1.11.2
2. Frontend doesn't work as intended

### Webserver logs

```bash
no log related to issue
```

### Browser logs

```bash
no log related to issue
```

### Paperless-ngx version

1.11.2

### Host OS

Raspberry Pi arm64

### Installation method

Docker - official image

### Browser

Chrome, Edge, Firefox

### Configuration changes

-

**Comment by shamoon** [comment] 2022-12-31 15:32
Duplicate of #2287, #2288 and #2286, I’ll look into it

**Comment by shamoon** [comment] 2022-12-31 18:28
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/40323158516b6c0b1ce69f366beb8ee093d90460

**Closed by shamoon** 2022-12-31 18:28 UTC
Labels: bug, frontend
