### ISSUE TITLE
[BUG] Settings are not preserved

### ISSUE THREAD

**Issue by asitemade4u** [paperless-ngx/paperless-ngx#347] opened 2022-03-14 15:44 UTC
**Describe the bug**
I change settings of Paperlkess-ngx, notably the ones dealing with Confirmations and Notifications. Those changes are not preserved between sessions.

**To Reproduce**
1. Go to Settings
2. Change settings, eg. Notification settings
3. Save
4. Log out of Paperless-ngx
5. Log in
6. The settings are not preserved

**Expected behavior**
The settings should be saved between sessions

**Relevant information**
 - Ubuntu Server 20.04
 - Firefox, last version on Debian 11
 - Last version (using WatchTower and `latest`)
 - last version of docker + Portainer BE
 - The database is Postgres on the same host

**Comment by shamoon** [comment] 2022-03-14 15:47
Dupe of #300

**Closed by shamoon** 2022-03-14 15:47 UTC
