### ISSUE TITLE
[BUG] PRE_CONSUME script may trigger second consume task which fails with "File not found"

### ISSUE THREAD

**Issue by amannsbart** [paperless-ngx/paperless-ngx#2462] opened 2023-01-18 12:38 UTC
### Description

When combining the barcode splitting feature with the [example preconsume script ](https://github.com/paperless-ngx/paperless-ngx/wiki/Pre-Consume-Script-Examples) paperless adds split documents to the task queue twice. The preconsume script, however, works flawlessly when used on its own. (i.e. it does not cause a inotify move_to/close_write event).

### Steps to reproduce

1. Add the [example preconsume script ](https://github.com/paperless-ngx/paperless-ngx/wiki/Pre-Consume-Script-Examples) to your setup
2. Enable the barcode splitting feature
3. Upload this [test file](https://we.tl/t-UsuSpxhYXi)

### Webserver logs

```bash
[2023-01-18 13:04:31,842] [DEBUG] [paperless.barcodes] Detected mime type: application/pdf

[2023-01-18 13:04:32,454] [DEBUG] [paperless.barcodes] Barcode of type CODE39 found: PATCHT

[2023-01-18 13:04:32,785] [DEBUG] [paperless.tasks] Pages with separators found in: /tmp/paperless/paperless-upload-0v80fcgm

[2023-01-18 13:04:32,787] [DEBUG] [paperless.barcodes] Starting new document at idx 1

[2023-01-18 13:04:32,787] [DEBUG] [paperless.barcodes] Split into 2 new documents

[2023-01-18 13:04:32,789] [DEBUG] [paperless.barcodes] pdf no:0 has 1 pages

[2023-01-18 13:04:32,791] [DEBUG] [paperless.barcodes] pdf no:1 has 1 pages

[2023-01-18 13:04:32,794] [DEBUG] [paperless.barcodes] moving /usr/src/paperless/consume/paperless-upload-0v80fcgm_document_0.pdf to /usr/src/paperless/consume/0_test.pdf

[2023-01-18 13:04:32,795] [DEBUG] [paperless.barcodes] moving /usr/src/paperless/consume/paperless-upload-0v80fcgm_document_1.pdf to /usr/src/paperless/consume/1_test.pdf

[2023-01-18 13:04:33,296] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/0_test.pdf to the task queue.

[2023-01-18 13:04:33,301] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/1_test.pdf to the task queue.

[2023-01-18 13:04:33,330] [DEBUG] [paperless.barcodes] Detected mime type: application/pdf

[2023-01-18 13:04:33,680] [INFO] [paperless.consumer] Consuming 0_test.pdf

[2023-01-18 13:04:33,681] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-01-18 13:04:33,682] [INFO] [paperless.consumer] Executing pre-consume script /scripts/remove-blank-pages.sh

[2023-01-18 13:04:34,048] [INFO] [paperless.consumer] /scripts/remove-blank-pages.sh exited 0

[2023-01-18 13:04:34,050] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-01-18 13:04:34,055] [DEBUG] [paperless.consumer] Parsing 0_test.pdf...

[2023-01-18 13:04:34,090] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/consume/0_test.pdf

[2023-01-18 13:04:34,547] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/0_test.pdf to the task queue.

[2023-01-18 13:04:34,576] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 140, in extract_text

    lang = detect(stripped)

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector_factory.py", line 130, in detect

    return detector.detect()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 136, in detect

    probabilities = self.get_probabilities()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 143, in get_probabilities

    self._detect_block()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 150, in _detect_block

    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')

langdetect.lang_detect_exception.LangDetectException: No features in text.

[2023-01-18 13:04:34,658] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/usr/src/paperless/consume/0_test.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-etjxz4c0/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-etjxz4c0/sidecar.txt')}

[2023-01-18 13:04:59,060] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2023-01-18 13:04:59,061] [DEBUG] [paperless.consumer] Generating thumbnail for 0_test.pdf...

[2023-01-18 13:04:59,069] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-etjxz4c0/archive.pdf[0] /tmp/paperless/paperless-etjxz4c0/convert.webp

[2023-01-18 13:05:01,395] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-01-18 13:05:01,406] [DEBUG] [paperless.consumer] Saving record to database

[2023-01-18 13:05:01,407] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2023-01-18 13:04:34.041623+01:00

[2023-01-18 13:05:01,477] [DEBUG] [paperless.consumer] Deleting file /usr/src/paperless/consume/0_test.pdf

[2023-01-18 13:05:01,480] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-etjxz4c0

[2023-01-18 13:05:01,484] [INFO] [paperless.consumer] Document 2023-01-18 0_test consumption finished

[2023-01-18 13:05:01,710] [DEBUG] [paperless.barcodes] Detected mime type: application/pdf

[2023-01-18 13:05:02,110] [INFO] [paperless.consumer] Consuming 1_test.pdf

[2023-01-18 13:05:02,112] [DEBUG] [paperless.consumer] Detected mime type: application/pdf

[2023-01-18 13:05:02,113] [INFO] [paperless.consumer] Executing pre-consume script /scripts/remove-blank-pages.sh

[2023-01-18 13:05:02,483] [INFO] [paperless.consumer] /scripts/remove-blank-pages.sh exited 0

[2023-01-18 13:05:02,486] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser

[2023-01-18 13:05:02,492] [DEBUG] [paperless.consumer] Parsing 1_test.pdf...

[2023-01-18 13:05:02,526] [DEBUG] [paperless.parsing.tesseract] Extracted text from PDF file /usr/src/paperless/consume/1_test.pdf

[2023-01-18 13:05:02,983] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/1_test.pdf to the task queue.

[2023-01-18 13:05:03,088] [WARNING] [paperless.parsing.tesseract] Error while getting text from PDF document with pdfminer.six

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 140, in extract_text

    lang = detect(stripped)

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector_factory.py", line 130, in detect

    return detector.detect()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 136, in detect

    probabilities = self.get_probabilities()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 143, in get_probabilities

    self._detect_block()

  File "/usr/local/lib/python3.9/site-packages/langdetect/detector.py", line 150, in _detect_block

    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')

langdetect.lang_detect_exception.LangDetectException: No features in text.

[2023-01-18 13:05:03,195] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/usr/src/paperless/consume/1_test.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-67zp_j1e/archive.pdf'), 'use_threads': True, 'jobs': 4, 'language': 'deu+eng', 'output_type': 'pdfa', 'progress_bar': False, 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-67zp_j1e/sidecar.txt')}

[2023-01-18 13:05:27,652] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file

[2023-01-18 13:05:27,653] [DEBUG] [paperless.consumer] Generating thumbnail for 1_test.pdf...

[2023-01-18 13:05:27,662] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient /tmp/paperless/paperless-67zp_j1e/archive.pdf[0] /tmp/paperless/paperless-67zp_j1e/convert.webp

[2023-01-18 13:05:30,016] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.

[2023-01-18 13:05:30,021] [DEBUG] [paperless.consumer] Saving record to database

[2023-01-18 13:05:30,023] [DEBUG] [paperless.consumer] Creation date from st_mtime: 2023-01-18 13:05:02.478487+01:00

[2023-01-18 13:05:30,139] [DEBUG] [paperless.consumer] Deleting file /usr/src/paperless/consume/1_test.pdf

[2023-01-18 13:05:30,142] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-67zp_j1e
```

### Paperless-ngx version

 1.11.3

### Host OS

Debian GNU/Linux 11 (bullseye)

### Installation method

Docker - official image

**Comment by amannsbart** [comment] 2023-01-18 14:56
possibly related to https://github.com/paperless-ngx/paperless-ngx/discussions/668#discussioncomment-4699294

**Comment by stumpylog** [comment] 2023-01-18 15:50
Well, pre consume script isn't executed differently in any way, everything goes through the same code path, so presumably the script is generating a inotify event somehow.  

The other option would be the copy hasn't yet completed.  What happens if PAPERLESS_CONSUMER_INOTIFY_DELAY is set to a larger value?

**Comment by stumpylog** [comment] 2023-01-18 17:51
That would do it.  It appears to be doing a sort of safe replace, saving the original and then replacing it with the modified version.

Obviously the `MOVED_TO` event needs to still be listened for.  Scripts should do an open and write from a temporary file when modifying the original to avoid this.

**Comment by amannsbart** [comment] 2023-01-18 19:33
Thanks for the feedback! I don't think an open and write would work here either. This would trigger a close_write event for the original file when the write is completed - which would also be picked up by a consumer.

**Comment by stumpylog** [comment] 2023-01-18 20:54
Hm, it does listen for that event too.  This is basically a duplicate of #2422, where scripts that modify the incoming document will likely trigger a second consume, as the file is still in the consume directory at the time the script is run.

**Comment by stumpylog** [comment] 2023-01-29 16:39
The consumer now copies the incoming file to a temporary location where it is safe to modify with a pre-consume script, as it won't trigger a second consume.  This temporary file is what will be used for all following work.

Scripts will need to be updated to modify the correct file.  Both the original path and the working copy are now provided to the pre-consume script.

**Closed by stumpylog** 2023-01-29 16:39 UTC
Labels: bug, backend
