### ISSUE TITLE
[BUG] Dash shows ## in Inbox - when no documents tagged "inbox"

### ISSUE THREAD

**Issue by CDNHammer012** [paperless-ngx/paperless-ngx#6339] opened 2024-04-08 20:32 UTC
### Description

A number of files were uploaded as a batch. They were later manually tagged. The inbox tag was removed but the counter is still showing them in the inbox while in the Dashboard, but there are no documents tagged with 'inbox'.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/80215063/3473789c-3b83-42b6-a721-dce68be378d4)

![image](https://github.com/paperless-ngx/paperless-ngx/assets/80215063/484cbf14-ac21-4eb7-ae57-5202ab615312)

### Steps to reproduce

1. unable to reproduce

### Webserver logs

```bash
Unable to reproduce
```

### Paperless-ngx version

2.6.1

### Host OS

Docker on Synology

### Installation method

Docker - official image

### Browser

Brave, Firefox

### Other

Started last week, has survived reboots.

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-04-08 20:39
So you are unable to reproduce it? Neither are we.

Its possible you have e.g. more than one inbox tag, what happens when you click on that item in the stats box?

**Comment by shamoon** [comment] 2024-04-08 20:57
Closing as above, please update the thread here if theres something else going on

**Closed by shamoon** 2024-04-08 20:57 UTC
Labels: cant-reproduce

**Comment by CDNHammer012** [comment] 2024-04-08 21:49
I appreciate your response, as well as the difficulty in reproducing something that the end user also can't figure out how to reproduce. 
You were correct in your assumption about multiple tags being marked as 'inbox tag'.  This did turn out to be user error and not a bug, but could open a discussion around discoverability of the inbox tag vs the number of items listed as in the inbox.
Thank you for your time, it is appreciated, as is the work your group have done with this software.

**Comment by shamoon** [comment] 2024-04-08 21:51
Yes feel free to open a discussion if you have more thoughts
