### ISSUE TITLE
[BUG] Save not Content matching algorithm and Content matching pattern

### ISSUE THREAD

**Issue by DanielSchiffer** [paperless-ngx/paperless-ngx#5305] opened 2024-01-07 20:21 UTC
### Description

If i Create a new Workflow was the Content matching algorithm not saved:

<img width="1006" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/61264324/c7e7ce4b-3a56-44c5-8984-1e4097aa575c">
 after Saving and again open the Worflow shows:
 
<img width="846" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/61264324/322ff567-666f-4563-bb9e-507e744ef230">

### Steps to reproduce

1. Click Add Workflow
2. Tpye on Name: Test
3.  Type on Sort Order: 1
4. Click Triggers
5. Click Add Triggers
6. Change TriggerType to 'Document Added'
7. Change 'Content matching algorithm' to 'Excact: Document contains the String'
8. Type in'Content matching pattern': test
9. Click on Actions
10. click Add Action
11. Click Assignment
12. Type in Assign Title: test
13. Click on Save
14.  Click on Edit
15. Click on Triggers
16. Open Document Added Trigger
17. Contenmaching algrorythm ist : None: Disable matching and Conten matching pattern is empty:
18. 
<img width="667" alt="image" src="https://github.com/paperless-ngx/paperless-ngx/assets/61264324/92fcbeba-18a1-4647-9d48-18d78871ad10">

### Webserver logs

```bash
[2024-01-07 18:05:01,888] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-01-07 18:05:02,301] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-01-07 19:05:01,325] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-01-07 19:05:01,731] [DEBUG] [paperless.tasks] Training data unchanged.

[2024-01-07 20:18:05,132] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume

[2024-01-07 20:18:07,839] [DEBUG] [paperless.classifier] Gathering data from database...

[2024-01-07 20:18:08,339] [DEBUG] [paperless.tasks] Training data unchanged.
```

### Paperless-ngx version

1.23

### Host OS

linux

### Installation method

Docker - official image

### Browser

Chrome

### Configuration changes

-

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-01-07 20:23
Duplicate of #5290

**Closed by shamoon** 2024-01-07 20:23 UTC
Labels: bug, unconfirmed

**Comment by DanielSchiffer** [comment] 2024-01-07 20:31
> Duplicate of #5290

Sorry!

**Comment by shamoon** [comment] 2024-01-07 21:21
No worries, not an easy thing to search for. We’re ironing out some bugs with workflows which were only released a few days ago. This one will be fixed in our next release.
