### ISSUE TITLE
[BUG] API filtering not working with custom_fields

### ISSUE THREAD

**Issue by zlovatt** [paperless-ngx/paperless-ngx#5256] opened 2024-01-05 18:46 UTC
### Description

When accessing API endpoints (either through the browser or by script/cli), you're able to use django queries to filter the response.

For example:
- `http://localhost:port/api/correspondents/` returns all correspondents, whereas
- `http://localhost:port/api/correspondents/?name__iexact=corrname` filters the results to only find the correspond whose name matches `corrname`.

This is great and useful!

However– no queries seem to actually filter the data when accessing `http://localhost:port/api/custom_fields/` – no matter what filter is tried, the endpoint _always_ returns all custom fields.

Broadly new to Paperless, Django, REST, etc. but don't know enough after several hours of digging to figure out whether this is user error or a bug on the project's side.

### Steps to reproduce

1. Go to `http://localhost:port/api/correspondent/`
2. You'll see all of your correspondents
3. Go to `http://localhost:port/api/correspondent/?name__iexact=Client` (replace `Client` with the name of a correspondent)
4. You'll see only that one correspondent
5. Repeat steps above with `http://localhost:port/api/custom_fields/`

Expected result:
`name__iexact=` (or `data_type__iexact=` or `name__contains=` etc) properly returns only filtered records from custom_fields

Actual result:
All queries always return all custom_fields

### Webserver logs

```bash
n/a; this is viewable from a browser and doesn't leave logs
```

### Paperless-ngx version

2.2.1

### Host OS

Synology NAS / x86_64

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-01-05 19:01
Duplicate of #4783

**Closed by stumpylog** 2024-01-05 19:01 UTC
Labels: duplicate, not a bug

**Comment by shamoon** [comment] 2024-01-05 19:06
This is a little different than that one, but it's still not a bug, what youre talking about is filtering the list of custom fields, which just isnt implemented. Im curious what your use-case is for that? To be clear, this would just filter the list of available custom fields, it has nothing do with documents or values of the fields, etc. You can of course open a FR if interested.

If you open up the API in a browser you'll see some helpful buttons for filters, and note that `/api/custom_fields/` doesnt have these (whereas e.g. correspondents does).

<img width="362" alt="Screenshot 2024-01-05 at 11 03 21 AM" src="https://github.com/paperless-ngx/paperless-ngx/assets/4887959/d55cf0a6-2645-4bb0-b3b8-a5c0c53b4b5a">

**Comment by zlovatt** [comment] 2024-01-05 19:34
@shamoon I didn't notice that button, & didn't think to check the discussion board for related FRs vs issues tracker– sorry for the triage clutter!

I'm not familiar enough to know whether this was a bug ("filtering works for everything except custom_fields, therefore something's broken") or whether filtering required specific implementation. But correct, the goal is to get a list of existing custom fields & their IDs.


## Use case

Exploring post-consumption script workflows that work with custom fields, though it's also just an inconsistency that stood out.

The goal is to, in a post-consumption script:
- Check whether a custom field exists, by name
  - If so, retrieve its ID
  - If not, create a new custom field
- Assign that custom field to the consumed document with a specified value.

Currently I've been [taking advantage of the fact that you can filter during the API requests (for other endpoints)](https://gist.github.com/zlovatt/3664bf0c01292b9ae78d272548411b9d/6438ec1f42e1cc018b8131aba8c00fb733267a18#file-post-consumption-py-L138), so that you can parse the response and know whether you've found a match– but this workflow falls apart since custom_fields doesn't allow filtering.

The workaround would be to ignore the request filtering and instead move that logic into the script itself– which is very doable! It just moves where the work is taking place from the API to the script itself.

**Comment by shamoon** [comment] 2024-01-05 20:01
Since its so trivial to do: #5257

But yea, in general there are a lot of notes in the "bug report" template about using discussions etc. so please try to check them in the future. Thanks for your understanding.

**Comment by zlovatt** [comment] 2024-01-06 19:41
Thank you, & all understood!
