### ISSUE TITLE
[BUG] PDF Rotation 180 degree problem

### ISSUE THREAD

**Issue by GuillaumeHullin** [paperless-ngx/paperless-ngx#8177] opened 2024-11-03 23:37 UTC
### Description

Rotating a PDF to 180 degree does not work.
When trying to rotate a PDF to 90, it works (after waiting and reopening the document).

### Steps to reproduce

1. Open a document
2. Click Actions > Rotate
3. Rotate to 180 degree
4. Click Proceed
5. Wait... wait... and nothing and no error

### Webserver logs

```bash
No error logs found...
```

### Paperless-ngx version

2.13.4

### Host OS

Debian 12

### Installation method

Docker - official image

### Browser

Safari

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-11-04 00:37
I can't reproduce this and rotation is handled by lower level tools, https://pikepdf.readthedocs.io/en/latest/api/models.html#pikepdf.Page.rotate which uses https://github.com/qpdf/qpdf so I'd be a bit surprised if it doesn't actually work.

I'm going to close this because this has been out for a while and hasnt changed lately.

<img width="1921" alt="Screenshot 2024-11-03 at 4 34 18 PM" src="https://github.com/user-attachments/assets/af4764f7-4985-4e8c-bcf5-189b8c40a1d6">
<img width="2367" alt="Screenshot 2024-11-03 at 4 37 09 PM" src="https://github.com/user-attachments/assets/6c5025b0-cf1b-43dd-a66c-c8d22cc92e4c">

**Closed by shamoon** 2024-11-04 00:37 UTC
Labels: cant-reproduce

**Comment by shamoon** [comment] 2024-11-04 00:43
The entirety of the code is

https://github.com/paperless-ngx/paperless-ngx/blob/695967cbb28f3f75f6e468d25685bab270e06179/src/documents/bulk_edit.py#L209-L238

So you should see something like 

```
[2024-11-03 16:35:53,342] [INFO] [paperless.bulk_edit] Attempting to rotate 1 documents by 180 degrees.
[2024-11-03 16:35:53,430] [INFO] [paperless.bulk_edit] Rotated document 215 by 180 degrees
```

followed by logs for re-processing of the archive file

**Comment by GuillaumeHullin** [comment] 2024-11-04 11:15
Ok found the "problem"... the OCR processing "think" it's ups and down... so it's not a problem of the tool (just a weird format of my document)
```
[2024-11-04 12:05:46,659] [INFO] [ocrmypdf._pipeline] with existing rotation ⇩, page is facing ⇩, confidence 13.13 - will rotate ↻
[2024-11-04 12:05:46,709] [INFO] [ocrmypdf._pipeline] with existing rotation ⇩, page is facing ⇩, confidence 14.74 - will rotate ↻
[2024-11-04 12:05:46,790] [INFO] [ocrmypdf._pipeline] with existing rotation ⇩, page is facing ⇩, confidence 4.92 - will rotate ↻
```

Thanks for your help :)

**Comment by shamoon** [comment] 2024-11-04 15:45
Oh I see thanks for clarifying. I guess an improvement could be to reprocess without autorotate

**Comment by GuillaumeHullin** [comment] 2024-11-04 15:53
Yes I agree, that would be great.
