### ISSUE TITLE
[BUG] Gunicorn startup fails on version 1.8 of paperless ngx. Version 1.7 works correctly.

### ISSUE THREAD

**Issue by ptr33** [paperless-ngx/paperless-ngx#1386] opened 2022-08-09 21:14 UTC
### Description

Startup of paperless ngx fails with repeated restart of gunicorn only for version 1.8.  When using version 1.7 (see commented image name below) all works.

Docker compose file
```  
  broker:
    image: docker.io/library/redis:6.0
    container_name: ppl_broker
    restart: unless-stopped
    volumes:
      - redisdata:/data
    logging:
       driver: "json-file"
       options:                         # limit logging to 5 x 10 MBytes
         max-file: "5"
         max-size: "10m"

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx
#    image: ghcr.io/paperless-ngx/paperless-ngx:1.7
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - broker
      - gotenberg
      - tika
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - ./paperless/consume:/usr/src/paperless/consume
    env_file: docker-compose-paperless.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    logging:
       driver: "json-file"
       options:                         # limit logging to 5 x 10 MBytes
         max-file: "5"
         max-size: "10m"

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.4
    container_name: ppl_gotenberg
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
    logging:
       driver: "json-file"
       options:                         # limit logging to 5 x 10 MBytes
         max-file: "5"
         max-size: "10m"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    container_name: ppl_tika
    restart: unless-stopped
    logging:
       driver: "json-file"
       options:                         # limit logging to 5 x 10 MBytes
         max-file: "5"
         max-size: "10m"

volumes:
  data:
  media:
  redisdata:
```

docker-compose-paperless.env file:
```
PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}{created_month}{created_day}_{title}
COMPOSE_PROJECT_NAME=paperless
```

### Steps to reproduce

1. installation using above configuration
2. creating default user according to documentation
3. docker-compose up -d
4. see logs with docker logs paperless

### Webserver logs

```bash
Waiting for Redis: redis://broker:6379
Connected to Redis broker: redis://broker:6379
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_q, documents, paperless_mail, sessions
Running migrations:
  No migrations to apply.
Executing /usr/local/bin/paperless_cmd.sh
2022-08-09 20:40:36,882 INFO Set uid to user 0 succeeded
2022-08-09 20:40:36,884 INFO supervisord started with pid 41
2022-08-09 20:40:37,886 INFO spawned: 'consumer' with pid 42
2022-08-09 20:40:37,888 INFO spawned: 'gunicorn' with pid 43
2022-08-09 20:40:37,890 INFO spawned: 'scheduler' with pid 44
[2022-08-09 20:40:38 +0000] [43] [INFO] Starting gunicorn 20.1.0
[2022-08-09 20:40:38 +0000] [43] [ERROR] Retrying in 1 second.
[2022-08-09 20:40:38,731] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
20:40:38 [Q] INFO Q Cluster monkey-tango-ceiling-cup starting.
20:40:38 [Q] INFO Process-1:1 ready for work at 60
20:40:38 [Q] INFO Process-1:2 monitoring at 61
20:40:38 [Q] INFO Process-1 guarding cluster monkey-tango-ceiling-cup
20:40:38 [Q] INFO Process-1:3 pushing tasks at 62
20:40:38 [Q] INFO Q Cluster monkey-tango-ceiling-cup running.
[2022-08-09 20:40:39 +0000] [43] [ERROR] Retrying in 1 second.
2022-08-09 20:40:39,262 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-08-09 20:40:39,262 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-08-09 20:40:39,262 INFO success: scheduler entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
[2022-08-09 20:40:40 +0000] [43] [ERROR] Retrying in 1 second.
[2022-08-09 20:40:41 +0000] [43] [ERROR] Retrying in 1 second.
[2022-08-09 20:40:42 +0000] [43] [ERROR] Retrying in 1 second.
[2022-08-09 20:40:43 +0000] [43] [ERROR] Can't connect to ('::', 8000)
2022-08-09 20:40:43,350 INFO exited: gunicorn (exit status 1; not expected)
2022-08-09 20:40:44,354 INFO spawned: 'gunicorn' with pid 63
```

### Paperless-ngx version

1.8

### Host OS

Ubuntu 20.04 amd64

### Installation method

Docker - official image

### Browser

Tested on Firefox and Chrome

### Configuration changes

see files in above description

**Comment by stumpylog** [comment] 2022-08-09 21:23
This is a duplicate of #1356 and will be fixed in the next release.

**Closed** 2022-08-09 21:26 UTC
Labels: bug, unconfirmed
