### ISSUE TITLE
[BUG] Automatic e-mail processing doesn't work if the subject uses a non-English character

### ISSUE THREAD

**Issue by DimitriDR** [paperless-ngx/paperless-ngx#6030] opened 2024-03-06 18:58 UTC
### Description

Paperless is unable to process e-mails if you want to filter by a subject and this subject contains a non-English character. I want to get e-mails with the subject ("Reçu") (receipt in English), this letter "ç" seems to cause trouble. Then, if I replace this letter by its closest equivalent, "c", it works without problem.

![image](https://github.com/paperless-ngx/paperless-ngx/assets/56969769/9bd1057a-1f82-473e-b0e2-4909502b0757)

In this screesnhot, at 19:52, the error is raised when I still had "ç" in the rule. When I replaced by "c", the next round, at 19:54 works without an error.

### Steps to reproduce

1. Configure an e-mail rule with the letter "ç"
2. Wait for Paperless to raise the error

### Webserver logs

```bash
[2024-03-06 19:52:01,082] [ERROR] [paperless_mail] Rule Google.Recu: Error while processing rule: UID command error: BAD [b'Could not parse command']

Traceback (most recent call last):

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 514, in handle_mail_account

    total_processed_files += self._handle_mail_rule(

                             ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/paperless/src/paperless_mail/mail.py", line 582, in _handle_mail_rule

    for message in messages:

  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 160, in fetch

    uids = tuple((reversed if reverse else iter)(self.uids(criteria, charset)))[limit_range]

                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/imap_tools/mailbox.py", line 119, in uids

    uid_result = self.client.uid('SEARCH', 'CHARSET', charset, encoded_criteria)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/imaplib.py", line 890, in uid

    typ, dat = self._simple_command(name, command, *args)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/imaplib.py", line 1230, in _simple_command

    return self._command_complete(name, self._command(name, *args))

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/imaplib.py", line 1055, in _command_complete

    raise self.error('%s command error: %s %s' % (name, typ, data))

imaplib.IMAP4.error: UID command error: BAD [b'Could not parse command']
```

### Paperless-ngx version

2.6.1

### Host OS

Debian

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-03-06 19:01
Duplicate of #5953 and several others.

**Closed by stumpylog** 2024-03-06 19:01 UTC
Labels: bug, unconfirmed
