### ISSUE TITLE
[BUG] 1.7.0 release broke all documents that have a creation date before 10 March 1911, making the Correspondents and Documents pages unusable

### ISSUE THREAD

**Issue by wblondel** [paperless-ngx/paperless-ngx#818] opened 2022-04-27 14:48 UTC
### Description

Hi,

Since I upgraded to version 1.7.0, my Paperless is unusable. I'm using Paperless for my genealogy research, I'm saving records of civil registers (like birth certificates, death certificates, etc).

As a result, most of my documents have old creation date, including dates before 1911.

I noticed that I cannot access any document that has a creation date of 10 March 1911 or before, Paperless just shows a 404 Page.
![image](https://user-images.githubusercontent.com/7508531/165545439-1ab8ab21-cc7a-45a1-85dc-a4c33f597e89.png)

The Correspondents page breaks as soon as it meets such date:
![image](https://user-images.githubusercontent.com/7508531/165545629-2de68bb8-69ad-423e-a668-e0c2d53f69b7.png)

Same with the Documents page:
![image](https://user-images.githubusercontent.com/7508531/165545758-41bc8889-5efb-45ac-95ac-5e09322dcf30.png)

I know how dealing with old dates can be troublesome, and I would like to know if it is a thought-of drop of support or a simple bug.

### Steps to reproduce

1. Create a new document with a creation date of 10 March 1911 or before
2. Cannot access it anymore

### Screenshots

Errors in the browser console:
![image](https://user-images.githubusercontent.com/7508531/165548343-d98d1de1-39b0-4ada-b37e-ee0e08af956c.png)

### Paperless-ngx version

1.7.0

### Host OS

Unraid 6.9.2

### Installation method

Docker

### Browser

Chrome 100

**Comment by shamoon** [comment] 2022-04-27 15:25
Is there anything in the browser console or logs? I will take a look at this later

**Comment by wblondel** [comment] 2022-04-27 15:33
Hi, yes I included a screenshot of the errors showing in the browser console.

**Comment by shamoon** [comment] 2022-04-27 16:11
Hmm, I cant reproduce this, screenshots below. I tried in French too =) Those errors dont provide much of a hint, I wonder if there are more specific steps to recreate?

<img width="1639" alt="Screen Shot 2022-04-27 at 9 08 47 AM" src="https://user-images.githubusercontent.com/4887959/165563544-3c036516-7ce6-4928-8322-849162121979.png">
<img width="1639" alt="Screen Shot 2022-04-27 at 9 07 27 AM" src="https://user-images.githubusercontent.com/4887959/165563563-ea27c886-6655-4756-a94b-36a685849533.png">
<img width="1639" alt="Screen Shot 2022-04-27 at 9 07 18 AM" src="https://user-images.githubusercontent.com/4887959/165563572-1aff7fbb-6066-4647-8db6-5adbe7eb291f.png">
<img width="1639" alt="Screen Shot 2022-04-27 at 9 07 12 AM" src="https://user-images.githubusercontent.com/4887959/165563575-6a879d4b-dce2-48b7-a140-03b9f1f6826e.png">
<img width="1639" alt="Screen Shot 2022-04-27 at 9 07 06 AM" src="https://user-images.githubusercontent.com/4887959/165563580-56f64c70-dd27-4cd0-b768-f09a0817000b.png">

**Comment by qcasey** [comment] 2022-04-27 16:14
I know you mentioned the nature of your documents, but is it possible there is a document exhibiting this issue you can share with us?

**Comment by wblondel** [comment] 2022-04-27 16:58
Mmmh. I just tested with a jpg file, this file being a screenshot of my screen.

I put 09/03/1911 as the creation date. And I could reproduce the issue. I can reproduce the issue with any document, new or existing.

Maybe the "limit date" isn't the same on every system? Does a year like 1750 work for you?

**Comment by wblondel** [comment] 2022-04-27 17:02
This view works for me too, but clicking on the edit button takes me to a 404 page

**Comment by qcasey** [comment] 2022-04-27 17:04
> Maybe the "limit date" isn't the same on every system? Does a year like 1750 work for you?

Good suggestion, 1650 broke it for me. I'll start digging for logs.

![Screenshot from 2022-04-27 10-04-07](https://user-images.githubusercontent.com/1429672/165580722-61ae7bb7-19ba-4f48-837b-db044e111361.png)

**Comment by wblondel** [comment] 2022-04-27 17:13
Just to make it clear, the issue is only on the UI, on the browser side. Because the dates are correctly stored in Postgres and I can edit them just fine in the admin interface.

**Comment by qcasey** [comment] 2022-04-27 17:24
@shamoon I dug a little deeper, this only occurred when I explicitly set `PAPERLESS_TIME_ZONE=America/Los_Angeles`. With it undefined I could set date to any value and it would work fine.

**Comment by qcasey** [comment] 2022-04-27 17:26
The actual debug error:

```
ERROR Error: NG02100: InvalidPipeArgument: 'Unable to convert "0950-04-27T10:22:00-07:52:58" into a date' for pipe 'DatePipe'
    Angular 3
    transform custom-date.pipe.ts:39
    Angular 2
    DocumentCardSmallComponent_ng_template_21_Template document-card-small.component.html:43
    Angular 12
    RxJS 6
    Angular 20
    observeTriggers ng-bootstrap.mjs:7412
    observeTriggers ng-bootstrap.mjs:7407
    RxJS 49
    listenToTriggers ng-bootstrap.mjs:7452
    ngOnInit ng-bootstrap.mjs:8910
    Angular 5
    DocumentCardSmallComponent_Template document-card-small.component.html:54
    Angular 23
core.mjs:6485:12
```

**Comment by shamoon** [comment] 2022-04-27 17:27
Yes I see it now, OK lemme look into it!

**Comment by shamoon** [comment] 2022-04-27 18:00
Well this is quite the esoteric bug. Im a little unclear if we need to handle this on the frontend or its actually a backend issue. For dates that old its returning a weird offset:
`"created": "1650-03-09T20:48:50-07:52:58"` (note the `07:52:58` as opposed to `07:00`). So obviously the frontend can be changed to handle that but can anyone from @paperless-ngx/backend confirm whether that is actually correct? I dont think it is

To be clear, value in my database is just `1650-03-10 04:41:48`

**Comment by qcasey** [comment] 2022-04-27 18:32
Agreed, it should be fixed in the backend because this would also affect any apps or scripts using the API.

```bash
$ http -f http://192.168.1.8:8010/api/documents/406/
{
...
    "correspondent": null,
    "created": "1650-02-20T00:00:00-07:52:58",
    "document_type": null,
    "id": 406,
    "modified": "2022-04-27T10:03:16.400852-07:00",
    "original_file_name": "1650-02-20 sample.pdf",
    "tags": [],
    "title": "sample"
...
}
```

**Comment by shamoon** [comment] 2022-04-27 18:41
FWIW I have a frontend fix too, but it does feel like a work-around, will defer to backend folks

**Comment by wblondel** [comment] 2022-04-27 19:38
> Just to make it clear, the issue is only on the user UI, on the browser side. Because the dates are correctly stored in Postgres and I can edit them just fine in the admin interface.

Modifying what I said. The dates stored in Postgres aren't correct for old ones. The weird offset is also stored.
![image](https://user-images.githubusercontent.com/7508531/165609804-b2735563-ed54-4e43-870b-165b6e5a643a.png)

**Comment by shamoon** [comment] 2022-04-27 20:03
Is that true (the weird offset) for any of your pre-existing documents or only ones that you’ve edited via the UI?

**Comment by wblondel** [comment] 2022-04-27 20:18
I have this weird timezone only when I put a date of 10 March 1911 or before. 

"Normal" dates have my correct timezone.

![image](https://user-images.githubusercontent.com/7508531/165623888-79870519-6f51-47dc-8037-a6962e392593.png)

**Comment by qcasey** [comment] 2022-05-01 01:56
This appears to be very repeatable:

```python3
import dateparser

print(dateparser.parse(
    "1901-12-12T00:00:00",
    settings={
        "RETURN_AS_TIMEZONE_AWARE": True,
        "TIMEZONE": "America/Los_Angeles",
    },
))
``` 

Could someone else confirm that this returns `-07:53` as the offset, while changing the year to `1902` returns the proper `-08:00`? I may open a bug upstream if so.

What I'm curious about now is why this is a 1.7.0 issue. The above behavior exists on `dateparser` versions all the way to `1.0.0`, which we've been using long before `-ngx`.

**Comment by wblondel** [comment] 2022-05-01 01:59
> This appears to be very repeatable:
> 
> ```python
> import dateparser
> 
> print(dateparser.parse(
>     "1901-12-12T00:00:00",
>     settings={
>         "RETURN_AS_TIMEZONE_AWARE": True,
>         "TIMEZONE": "America/Los_Angeles",
>     },
> ))
> ```
> 
> Could someone else confirm that this returns `-07:53` as the offset, while changing the year to `1902` returns the proper `-08:00`? I may open a bug upstream if so.
> 
> What I'm curious about now is why this is a 1.7.0 issue. The above behavior exists on `dateparser` versions all the way to `1.0.0`, which we've been using long before `-ngx`.

I confirm this. Same -07:53 offset.

**Comment by qcasey** [comment] 2022-05-01 02:45
Thanks for confirming that. I should have checked earlier, but the response from Paperless' API has also not changed from `jonaswinkler/paperless:latest`. Turns out this particular behavior is intentional: https://github.com/dateutil/dateutil/issues/878

I now feel lucky I don't deal with dates on a daily basis. Anyway @shamoon, if you don't mind, could we apply that frontend fix and then close this? :) that should be all we need.

**Comment by shamoon** [comment] 2022-05-01 03:03
I love this weird deep dive into history meets software! Sounds good!

**Comment by wblondel** [comment] 2022-05-01 03:14
If the backend always returned this weird timezone, what changes from 1.6.0 to 1.7.0 created the issue? Just out of curiosity

**Comment by shamoon** [comment] 2022-05-01 04:50
> If the backend always returned this weird timezone, what changes from 1.6.0 to 1.7.0 created the issue? Just out of curiosity

Its because of https://github.com/paperless-ngx/paperless-ngx/pull/654 which fixed the fact that the frontend was erasing time data, which in this case was actually preventing this issue. Ha! =)

**Comment by shamoon** [comment] 2022-05-01 20:37
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/7ae31def4f022e454634507cf190a36e7863827f

**Closed by shamoon** 2022-05-01 20:37 UTC
Labels: bug, backend
