### ISSUE TITLE
[BUG] Insufficient Permission Error when deleting correspondent by selection

### ISSUE THREAD

**Issue by Finkman** [paperless-ngx/paperless-ngx#7360] opened 2024-08-01 07:08 UTC
### Description

I was editing the correspondents and tried to delete multiple correspondents and delete them. Then, this appears:
 
![Bildschirmfoto vom 2024-08-01 08-56-01](https://github.com/user-attachments/assets/b93c889d-c492-40c9-a8ca-547c77047dbc)

This even comes up when I select only one and trying to delete.

The workaround is deleting the entries one by one or using the admin account.

### Steps to reproduce

1. Login as a User with given rights see picture below.
2. Take paperless 2.11.2
3. Select a correspondent
4. Press delete at the trash bin icon top right

The user rights:

![image](https://github.com/user-attachments/assets/4c14ea0d-c7af-4986-9b49-223424457cbb)

### Webserver logs

```bash
-- currently no access to the server logs --

I guess, you need the output of the docker stdout in my case, right?
```

### Paperless-ngx version

2.11.2

### Host OS

Synology OS

### Installation method

Docker - official image

### System status

```json
{
    "pngx_version": "2.11.2",
    "server_os": "Linux-3.10.108-x86_64-with-glibc2.36",
    "install_type": "docker",
    "storage": {
        "total": 8915941834752,
        "available": 2135326994432
    },
    "database": {
        "type": "postgresql",
        "url": "paperless",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://broker:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-08-01T08:54:24.644162+02:00",
        "index_error": null,
        "classifier_status": "OK",
        "classifier_last_trained": "2024-08-01T06:05:04.194939Z",
        "classifier_error": null
    }
}
```

### Browser

Edge

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by homberger** [comment] 2024-08-01 10:10
I am unable to reproduce this error.
Please do a hard refresh of the correspondents page (on most browsers Ctrl + R or Ctrl + Shift + R) to rule out cached scripts of an older version of paperless and try again.

If the error persists, add more details and gather corresponding log entries, please. 

Please also add screenshots of the permissions of the correspondents you are trying to delete.

**Comment by Finkman** [comment] 2024-08-01 10:33
I used a - never used before - FireFox for my latest test.

Error Details:

```json
{"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"OK","url":"https://paperless.hauswg.diskstation.me/api/bulk_edit_objects/","ok":false,"name":"HttpErrorResponse","message":"Http failure response for https://paperless.hauswg.diskstation.me/api/bulk_edit_objects/: 400 OK","error":{"non_field_errors":["Some ids in objects don't exist or were specified twice."]}}
```

What I did:
[Bildschirmaufzeichnung vom 01.08.2024, 12:29:59.webm](https://github.com/user-attachments/assets/b272a981-cc6b-42c5-828b-d58dded24076)

**Comment by shamoon** [comment] 2024-08-01 13:07
I’m not clear which was the error but I can’t reproduce that either and presumably now that you’ve deleted them you can’t either. The second error is a different one.

I’m going to close this out, not aware of any issues here

**Closed by shamoon** 2024-08-01 13:07 UTC
Labels: bug, unconfirmed
