### ISSUE TITLE
Paperless-ngx 2.8.1 django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported

### ISSUE THREAD

**Issue by Kunibert-007** [paperless-ngx/paperless-ngx#6593] opened 2024-05-07 06:20 UTC
### Description

After upgrading to Paperless 2.8.0/2.8.1 the docker container won`t start and I have an error in my log:

File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported
Paperless-ngx docker container starting...
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = "de_DE.UTF-8",
	LC_ALL = (unset),
	LANG = "de_DE.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
  Applying auditlog.0015_alter_logentry_changes...Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.FeatureNotSupported: conversion between UTF8 and SQL_ASCII is not supported
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 831, in alter_field
    self._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 288, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 1056, in _alter_field
    self.execute(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported

=======================================================================

This is my docker config:
{
   "CapAdd" : [
      "AUDIT_WRITE",
      "CHOWN",
      "DAC_OVERRIDE",
      "FOWNER",
      "FSETID",
      "KILL",
      "MKNOD",
      "NET_BIND_SERVICE",
      "NET_RAW",
      "SETFCAP",
      "SETGID",
      "SETPCAP",
      "SETUID",
      "SYS_CHROOT"
   ],
   "CapDrop" : [
      "AUDIT_CONTROL",
      "BLOCK_SUSPEND",
      "DAC_READ_SEARCH",
      "IPC_LOCK",
      "IPC_OWNER",
      "LEASE",
      "LINUX_IMMUTABLE",
      "MAC_ADMIN",
      "MAC_OVERRIDE",
      "NET_ADMIN",
      "NET_BROADCAST",
      "SYSLOG",
      "SYS_ADMIN",
      "SYS_BOOT",
      "SYS_MODULE",
      "SYS_NICE",
      "SYS_PACCT",
      "SYS_PTRACE",
      "SYS_RAWIO",
      "SYS_RESOURCE",
      "SYS_TIME",
      "SYS_TTY_CONFIG",
      "WAKE_ALARM"
   ],
   "cmd" : "/usr/local/bin/paperless_cmd.sh",
   "cpu_priority" : 50,
   "enable_publish_all_ports" : false,
   "enable_restart_policy" : false,
   "enabled" : false,
   "env_variables" : [
      {
         "key" : "PATH",
         "value" : "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      },
      {
         "key" : "LANG",
         "value" : "de_DE.UTF-8"
      },
      {
         "key" : "GPG_KEY",
         "value" : "A035C8C19219BA821ECEA86B64E628F8D684696D"
      },
      {
         "key" : "PYTHON_VERSION",
         "value" : "3.11.9"
      },
      {
         "key" : "PYTHON_PIP_VERSION",
         "value" : "24.0"
      },
      {
         "key" : "PYTHON_SETUPTOOLS_VERSION",
         "value" : "65.5.1"
      },
      {
         "key" : "PYTHON_GET_PIP_URL",
         "value" : "https://github.com/pypa/get-pip/raw/dbf0c85f76fb6e1ab42aa672ffca6f0a675d9ee4/public/get-pip.py"
      },
      {
         "key" : "PYTHON_GET_PIP_SHA256",
         "value" : "dfe9fd5c28dc98b5ac17979a953ea550cec37ae1b47a5116007395bfacff2ab9"
      },
      {
         "key" : "PYTHONDONTWRITEBYTECODE",
         "value" : "1"
      },
      {
         "key" : "PYTHONUNBUFFERED",
         "value" : "1"
      },
      {
         "key" : "PYTHONWARNINGS",
         "value" : "ignore:::django.http.response:517"
      },
      {
         "key" : "PNGX_CONTAINERIZED",
         "value" : "1"
      },
      {
         "key" : "PAPERLESS_ADMIN_USER",
         "value" : "XXX"
      },
      {
         "key" : "PAPERLESS_ADMIN_PASSWORD",
         "value" : "YYY"
      },
      {
         "key" : "PAPERLESS_TIKA_ENABLED",
         "value" : "1"
      },
      {
         "key" : "PAPERLESS_TIKA_GOTENBERG_ENDPOINT",
         "value" : "http://localhost:3005"
      },
      {
         "key" : "PAPERLESS_TIKA_ENDPOINT",
         "value" : "http://localhost:9998"
      },
      {
         "key" : "USERMAP_UID",
         "value" : "1024"
      },
      {
         "key" : "USERMAP_GID",
         "value" : "100"
      },
      {
         "key" : "TZ",
         "value" : "Europe/Berlin"
      },
      {
         "key" : "LANGUAGE",
         "value" : "de_DE.UTF-8"
      },
      {
         "key" : "PAPERLESS_CONSUMPTION_DIR",
         "value" : "/consume"
      },
      {
         "key" : "PAPERLESS_CSRF_TRUSTED_ORIGINS",
         "value" : "https://EXAMPLE.COM"
      },
      {
         "key" : "PAPERLESS_ALLOWED_HOSTS",
         "value" : "example.com,localhost,192.168.0.3"
      },
      {
         "key" : "PAPERLESS_CORS_ALLOWED_HOSTS",
         "value" : "https://example.com,http://localhost:8000,http://192.168.0.3:8000"
      },
      {
         "key" : "PAPERLESS_OCR_LANGUAGE",
         "value" : "deu"
      },
      {
         "key" : "PAPERLESS_DBHOST",
         "value" : "localhost"
      },
      {
         "key" : "PAPERLESS_DBPORT",
         "value" : "5430"
      },
      {
         "key" : "PAPERLESS_DBNAME",
         "value" : "paperless"
      },
      {
         "key" : "PAPERLESS_DBUSER",
         "value" : "paperless"
      },
      {
         "key" : "PAPERLESS_DBPASS",
         "value" : "paperless"
      },
      {
         "key" : "PAPERLESS_DBSSLMODE",
         "value" : "disable"
      }
   ],
   "exporting" : false,
   "id" : "a1c2c330a2046abf39c7a80e5896f3447d34d3709b0809c734adc2889fe92c17",
   "image" : "ghcr.io/paperless-ngx/paperless-ngx:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "labels" : {
      "com.centurylinklabs.watchtower.enable" : "true",
      "org.opencontainers.image.authors" : "paperless-ngx team <hello@paperless-ngx.com>",
      "org.opencontainers.image.created" : "2023-06-27T22:58:03.360Z",
      "org.opencontainers.image.description" : "A community-supported supercharged version of paperless: scan, index and archive all your physical documents",
      "org.opencontainers.image.documentation" : "https://docs.paperless-ngx.com/",
      "org.opencontainers.image.licenses" : "GPL-3.0",
      "org.opencontainers.image.revision" : "37e0c2667b7acdb054ecbe2b57474df5ecbbd11f",
      "org.opencontainers.image.source" : "https://github.com/paperless-ngx/paperless-ngx",
      "org.opencontainers.image.title" : "paperless-ngx",
      "org.opencontainers.image.url" : "https://github.com/paperless-ngx/paperless-ngx",
      "org.opencontainers.image.version" : "1.16.5"
   },
   "links" : [],
   "memory_limit" : 0,
   "name" : "paperless-ngx",
   "network" : [
      {
         "driver" : "host",
         "name" : "host"
      }
   ],
   "network_mode" : "host",
   "port_bindings" : [],
   "privileged" : false,
   "shortcut" : {
      "enable_shortcut" : false,
      "enable_status_page" : false,
      "enable_web_page" : false,
      "web_page_url" : ""
   },
   "use_host_network" : true,
   "version" : 2,
   "volume_bindings" : [
      {
         "host_volume_file" : "/docker/paperless",
         "is_directory" : true,
         "mount_point" : "/usr/src/paperless/media",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/paperless",
         "is_directory" : true,
         "mount_point" : "/usr/src/paperless/data",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/paperless_consume",
         "is_directory" : true,
         "mount_point" : "/consume",
         "type" : "rw"
      },
      {
         "host_volume_file" : "/docker/paperless_export",
         "is_directory" : true,
         "mount_point" : "/usr/src/paperless/export",
         "type" : "rw"
      },
      {
         "host_absolute_path" : "2b25d009fff170891c3325710313dca55c135f6db3f7471597bb109236f5782e",
         "mount_point" : "/usr/src/paperless/consume",
         "type" : "rw"
      }
   ]
}

================================================================

I use a docker Postgres-Container. In the Postgres-Container are also errors:

PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-05-07 05:30:00.806 UTC [1] LOG:  starting PostgreSQL 14.11 (Debian 14.11-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-05-07 05:30:00.807 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-05-07 05:30:00.807 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-05-07 05:30:02.222 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-05-07 05:30:05.009 UTC [27] LOG:  database system was shut down at 2024-05-07 05:29:44 UTC
2024-05-07 05:30:05.193 UTC [1] LOG:  database system is ready to accept connections
2024-05-07 05:42:22.564 UTC [47] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:42:22.564 UTC [47] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:42:38.662 UTC [49] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:42:38.662 UTC [49] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:42:56.775 UTC [51] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:42:56.775 UTC [51] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:43:16.630 UTC [54] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:43:16.630 UTC [54] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:43:30.682 UTC [56] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:43:30.682 UTC [56] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:44:00.847 UTC [58] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:44:00.847 UTC [58] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:45:16.889 UTC [62] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 05:45:16.889 UTC [62] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 05:57:28.158 UTC [1] LOG:  received fast shutdown request
2024-05-07 05:57:28.414 UTC [1] LOG:  aborting any active transactions
2024-05-07 05:57:28.416 UTC [1] LOG:  background worker "logical replication launcher" (PID 33) exited with exit code 1
2024-05-07 05:57:28.416 UTC [28] LOG:  shutting down
2024-05-07 05:57:29.259 UTC [1] LOG:  database system is shut down
PostgreSQL Database directory appears to contain a database; Skipping initialization
2024-05-07 05:57:50.256 UTC [1] LOG:  starting PostgreSQL 14.11 (Debian 14.11-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-05-07 05:57:50.256 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-05-07 05:57:50.256 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-05-07 05:57:54.645 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-05-07 05:57:57.339 UTC [27] LOG:  database system was shut down at 2024-05-07 05:57:29 UTC
2024-05-07 05:57:58.079 UTC [1] LOG:  database system is ready to accept connections
2024-05-07 06:02:06.968 UTC [39] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 06:02:06.968 UTC [39] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 06:04:57.048 UTC [43] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 06:04:57.048 UTC [43] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL
2024-05-07 06:05:25.636 UTC [46] ERROR:  conversion between UTF8 and SQL_ASCII is not supported
2024-05-07 06:05:25.636 UTC [46] STATEMENT:  ALTER TABLE "auditlog_logentry" ALTER COLUMN "changes" TYPE jsonb USING "changes"::jsonb, ALTER COLUMN "changes" DROP NOT NULL

============================================================
Has some an idea how to fix it?

### Steps to reproduce

1. I created are new container with manual shifting of the settings
2. Every time I try to start the Paperless docker-container it stops with the db-errors
3. Below Version 2.8.0/2.8.1 there was no error

### Webserver logs

```bash
see Description
```

### Paperless-ngx version

2.8.1

### Host OS

Docker on Synolgy NAS

### Installation method

Docker - official image

### Browser

Edge/Chrome

### Configuration changes

see Description

### Other

see Description

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-05-07 06:21
Duplicate of #6586

**Closed by shamoon** 2024-05-07 06:21 UTC
Labels: bug, unconfirmed
