### ISSUE TITLE
Having exact same issue as #216 with latest version.

### ISSUE THREAD

**Issue by Budman1758** [paperless-ngx/paperless-ngx#2497] opened 2023-01-24 04:28 UTC
### Description

I am using the newest version of this software and am experiencing the exact same issue as the [above referenced issue](https://github.com/paperless-ngx/paperless-ngx/issues/216).
New install using docker compose. Basically a bone stock install.
New to paperless.

This is happening A LOT. Thought I was losing my mind.....
Using Edge for browser.

### Steps to reproduce

See referenced issue

### Webserver logs

```bash
Nothing relevant shows in the log
```

### Paperless-ngx version

Latest release

### Host OS

Proxmox VE Host.  Ubuntu 20.04 Container.

### Installation method

Docker - official image

### Browser

Edge

### Configuration changes

timezone

**Comment by shamoon** [comment] 2023-01-24 04:34
Does this only happen in Edge? I cannot re-create... (video)


https://user-images.githubusercontent.com/4887959/214212797-d6bbe655-6af7-4915-baa1-899e379b1597.mov

**Comment by Budman1758** [comment] 2023-01-24 05:58
I have not tried with any other browser. 
I seem to notice it the most when I am typing something at the same moment that the "Title" area just above where you type is updating. Its a split second thing. Hard to catch when looking for it. In your video there are no updates to the title until you stop typing. It seems like it is a collision when title updates at the same instant you type something.

Hope that makes sense. Its pretty hard to duplicate here also when you actually want it to.

**Comment by shamoon** [comment] 2023-01-24 06:26
Er, yea thats tough, just sounds like your server is slowing down under load, not necessarily a true 'bug'...

**Comment by clemensrieder** [comment] 2023-01-24 11:48
I guess you could limit the CPU cores that are used and see if the issue is still occurring?

**Comment by r2ixuz** [comment] 2023-01-25 09:59
No it is not a ressource issue. Got the same behaviour sometimes with an idling host system. But to be fair it is a really really rare occasion.

It leads to wrong document titles which you don't notice sometimes immediately - not so good... :-)

Why is it needed to save the title after a period of time not typing? Is it not possible to save the title only, if the text box is not highlighted (no blinking cursor) anymore? Or just save it when you hit the save button?

**Comment by clemensrieder** [comment] 2023-01-25 10:01
> > I guess you could limit the CPU cores that are used and see if the issue is still occurring?
> 
> Computer is an AMD A10 7850K 8 core CPU 16Gigs of ram The box is running Proxmox VE and 1 container called Paperless....:) Paperless container is 6 Cores, 8gig of memory and 8gigs of swap. Currently consuming a 40meg pdf file. I don't think its a resource issue.
> 
> ![image](https://user-images.githubusercontent.com/6570134/214387113-2552a276-94b1-49da-9fa0-19688ebde7ff.png)

I can see how this is totally not a resource issue 😆

**Comment by Budman1758** [comment] 2023-01-25 18:05
`Why is it needed to save the title after a period of time not typing? Is it not possible to save the title only, if the text box is not highlighted (no blinking cursor) anymore? Or just save it when you hit the save button?`

What's actually happening is keystrokes when typing in the title box are either registered incorrectly or not at all. For instance, sometimes while renaming the title you could be somewhere in the middle of the string of characters, hit the space bar and next thing you know you are at the end of the string as if you hit the "end" key. Also, frequently I will type something like "#3-12" and I look up at the title and its "312". (minus the quotes)

In the process of archiving 90 year's worth of magazine .pdf files. This is a very frequent occurrence.

**Comment by shamoon** [comment] 2023-01-25 18:23
Agree its not perfect, if you mess around in the text field sometimes I see what youre describing, though honestly its pretty rare and doesnt come up for me in usual use. I will have a think about whether theres a way to improve this but to answer your question there is a 'debounce' (the delay thing) on that field because as you'll notice editing a document is dynamically aware of unsaved changes ("dirty") and it would be detrimental to have to check for this with every single keystroke, so there is a delay (currently 1s) after which the user is assumed to have stopped typing and we can go ahead and check if anything has changed.

Yes, we could have it only register the change when the field loses focus but overall I think thats a worse experience, most users dont seem run into this much if at all...

Again I'll have a think on it

**Comment by Budman1758** [comment] 2023-01-25 18:28
I understand. I have adjusted a bit to compensate so I can manage.

Side note. Where is the best place for feature requests?

**Comment by shamoon** [comment] 2023-01-25 19:12
Hey, I had an idea that might help. If you have some time try out the docker container tagged `feature-improved-title-debounce` and let me know if that helps. This would be safe to use over a 1.12 installation or obviously testing separately.

**Comment by r2ixuz** [comment] 2023-01-26 09:16
I tried to test this with my test instance which is couple month old but the webserver container cannot start due to this:

```
Creating pltest-webserver ... done
Paperless-ngx docker container starting...
Creating directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, django_celery_results, documents, paperless_mail, sessions
Running migrations:
  Applying django_celery_results.0001_initial... OK
  Applying django_celery_results.0002_add_task_name_args_kwargs... OK
  Applying django_celery_results.0003_auto_20181106_1101... OK
  Applying django_celery_results.0004_auto_20190516_0412... OK
  Applying django_celery_results.0005_taskresult_worker... OK
  Applying django_celery_results.0006_taskresult_date_created... OK
  Applying django_celery_results.0007_remove_taskresult_hidden... OK
  Applying django_celery_results.0008_chordcounter... OK
  Applying django_celery_results.0009_groupresult... OK
  Applying django_celery_results.0010_remove_duplicate_indices... OK
  Applying django_celery_results.0011_taskresult_periodic_task_name... OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "documents_paperlesstask" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 402, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 448, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 96, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 349, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/migration.py", line 130, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 447, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 199, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "documents_paperlesstask" already exists
```

**Comment by shamoon** [comment] 2023-01-26 14:44
> I tried to test this with my test instance which is couple month old but the webserver container cannot start due to this:

Well your migrations are probably out-of-sync, I would just recreate the test instance, but that’s kind of besides the point here :)

**Comment by r2ixuz** [comment] 2023-01-26 16:21
Ofc, just thought there is one command I could use to fix this instead to copy my whole production instance again ;-)

So I tried now this improved title debounce tag but could not find any difference. I guess this is normal as I don't know how to reproduce this behaviour reliable. What did you change in this dev tag?

**Comment by shamoon** [comment] 2023-01-26 17:01
If you can’t recreate the issue that’d be a good thing, no? The change is not something youd be able to see but was trying to see if we can prevent this issue

**Comment by shamoon** [comment] 2023-01-27 20:24
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/94ad290e14a6d5213e3f54705d4a14b34b833d47

**Closed by shamoon** 2023-01-27 20:24 UTC
Labels: cant-reproduce

**Comment by Budman1758** [comment] 2023-01-27 20:44
How does one go about integrating this fix? Docker pull?

**Comment by shamoon** [comment] 2023-01-27 20:55
It will be in our next release or you can try it in `dev` (but be warned, `dev` is not always stable... )

**Comment by Budman1758** [comment] 2023-02-01 05:30
It would seem that this issue is resolved. Nice work.
