### ISSUE TITLE
[BUG] Bidirectional linking getting lost, if already opened document is saved

### ISSUE THREAD

**Issue by pustekuchen91** [paperless-ngx/paperless-ngx#5364] opened 2024-01-12 15:56 UTC
### Description

This is a follow-up of https://github.com/paperless-ngx/paperless-ngx/issues/5172, because my initial problem was not solved.

I updated to 2.3.2 and scanned 3 new documents today, which i wanted to link together.

I expect that if i add a link in Document 1 to Document 2 that if i open document 2 a link to document 1 is also created.

I did not add the custom field in document (ID 2) manually. I expect that this happens automatically.

### Steps to reproduce

1. add custom field with type doc-linking
2. Go to a document (ID: 1)
3. add custom field
4. link to another document (ID 2)
5. follow the link to the document of the new linked document

customfield is missing at document ID: 2, no link exists

### Webserver logs

```bash
No Errors
```

### Paperless-ngx version

2.3.2

### Host OS

GNU/Linux synology_braswell_216

### Installation method

Docker - official image

### Browser

Firefox

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-01-12 16:15
I can't reproduce this.  Links are bi-directional and the field will be added if it does not already exist on the destination document.

**Comment by shamoon** [comment] 2024-01-12 16:17
Yea, perhaps you had the document open already and need to close it and re-open it

**Comment by pustekuchen91** [comment] 2024-01-12 22:34
> Yea, perhaps you had the document open already and need to close it and re-open it

Ohh yeah, this is the problem! I think this isnt really user friendly. Is it possible to trigger a reload of the linked document? 

It gets even worse, if the linked document is open and will be changed after linking, then the linking get lost.

### Steps to reproduce

1. add custom field with type doc-linking
2. Open document (ID: 1)
3. Open document (ID: 2)
4. add custom field to document (ID: 1)
5. in document 1 add a link to document (ID 2)
6. follow the link to the already opened document (ID2) and change e.g. the title
7. save document (ID 2)

The linking is lost / overwritten

**Comment by shamoon** [comment] 2024-01-12 23:13
Not really no. And it has been this way for a long time. The reason is the user could be intentionally editing a document and we don’t want to lose the changes.

**Closed by shamoon** 2024-01-12 23:13 UTC
Labels: not a bug

**Comment by pustekuchen91** [comment] 2024-01-12 23:14
Maybe force the user to close a document, before a link can be added?

**Comment by shamoon** [comment] 2024-01-12 23:20
there isn’t a way to do that currently, ie “tell the difference” between a user editing a document (you removed that link) vs a document that changed in the backend while you had it open for editing.

I will say I think with some of the new features weve added recently people are probably noticing this more than before. Maybe it’d be nice to somehow get notified if you have a doc open or something like that (FR), but again no idea how you’d do that. Maybe something with comparing timestamps

**Comment by pustekuchen91** [comment] 2024-01-12 23:38
Okay, I understand the problem. In most cases this is actually no problem, because i think the most users never work at one document at the same time. A simple check in the frontend would only prevent data-loss for changes by the user itself (But probably only if you work in a browser tab)

To ensure data loss-free operation, a lock mechanism must be implemented, to prevent changes from the backend or another user.

My idea for the frontend check would be:

- If a user is adding a new link
- Check if the document is open (Frontend)  / compare the id of the linked document with the opened documents
- show the user a message box with an error "The link can not be added, because the linked document is currently opened. Please close the document XYZ first"

This is no guarantee for other data-loss of changes done in the backend, but better than nothing?

**Comment by pustekuchen91** [comment] 2024-01-13 20:47
thanks @shamoon for providing a solution that fast. It looks fantastic :)

**Comment by shamoon** [comment] 2024-01-13 21:24
> thanks @shamoon for providing a solution that fast. It looks fantastic :)

Welcome! I guess I'm a sucker for UI improvements 😅
