### ISSUE TITLE
[BUG] Blocked duplicate consumption causing system stall

### ISSUE THREAD

**Issue by AlexKalopsia** [paperless-ngx/paperless-ngx#3474] opened 2023-05-27 21:31 UTC
### Description

Today I noticed that my entire machine (Synology DS918+ 16Gb RAM) was tanking. By using `htop` I noticed that at the top of the volume utilization was paperless

![image](https://github.com/paperless-ngx/paperless-ngx/assets/706110/990b5dfe-1c97-4405-97f5-59b199324000)

I opened paperless, and noticed that the log was full of:

```
[2023-05-27 23:01:17,491] [ERROR] [paperless.consumer] Not consuming Epson_03022018172651.pdf: It is a duplicate of Modulo Identificazione Personale (#85)
````

This error would print literally every 10 seconds. 

I proceeded to delete the file manually, and this resulted in a crazy amount of tasks being generated, they are all relative to this file

![image](https://github.com/paperless-ngx/paperless-ngx/assets/706110/d6337f26-ea1f-4b7e-af9c-fe3fc6769975)

If it helps, this is what the logs ended up looking like: https://hastebin.com/share/ahihasimin.kotlin

I was on version 1.13.0, so I decided to `docker-compose down` and upgrade to latest. As you can see below, there was a massive resource "release" once I nuked the container. 

![image](https://github.com/paperless-ngx/paperless-ngx/assets/706110/1c9262be-ce32-4aad-82c3-ab7e8304a132)

Unfortunately I don't have any idea whether upgrading to the latest version did anything, my assumption is that just the consumption of a duplicate document was stalling my entire machine. *All the tasks are still there*

I am reporting all of this not because I need help fixing, but because I thought maybe this could be useful information and perhaps there is still some form of issue related to this. 

Thanks for taking such good care of paperless.

DISCLAIMER: Had this issue on 1.13.0

### Steps to reproduce

- Upload a document
- Put a duplicate of the file in the consumption folder

### Webserver logs

https://hastebin.com/share/ahihasimin.kotlin

### Paperless-ngx version

1.13.0

### Host OS

Synology DSM

### Installation method

Docker - official image

**Comment by shamoon** [comment] 2023-05-28 02:46
Thanks for the detailed report. Yea it’s not something I can reproduce in basic usage nor do I think it’s been reported before. And yea, it’s an older version of -ngx

That said, there are others here who are much more versed in how the software handles tasks etc so I’ll hold off on closing this for a second in case they can glean anything else from the info.

thanks again

**Comment by stumpylog** [comment] 2023-05-29 22:33
It seems likely that celery got a little stuck and kept sending the same task again and again.  It's something we've seen from time to time and hopefully something they fix in their next release.  It wasn't a new consume each time, since that would produce a clear log of a new task being added to the queue.

You could have also likely cleared the problem by clearing all Redis data.

In all, I don't see anything we can do at this time about it.  I'm tracking the 5.3 celery release, so we'll  be sure and upgrade when it (or a point release) are out.

**Closed by stumpylog** 2023-05-29 22:33 UTC
Labels: cant-reproduce
