### ISSUE TITLE
[BUG] Text on document not displayed correctly

### ISSUE THREAD

**Issue by amo13** [paperless-ngx/paperless-ngx#1427] opened 2022-08-16 06:26 UTC
### Description

As you can see in the screenshot, the text on my document is not displayed correctly. This is odd because a) the document is displayed correctly if downloaded and opened on the system, and b) the document text has been OCRed and parsed correctly.

I see the same results in both firefox and chromium.

![Screenshot from 2022-08-16 08-14-58](https://user-images.githubusercontent.com/6617661/184811695-98eb5838-6873-40d7-8800-002a902d6948.png)

### Steps to reproduce

I can thankfully provide the original pdf to anyone willing to help investigate, but I'd like to avoid publishing it openly.

### Paperless-ngx version

1.8.0

### Host OS

Archlinux

### Installation method

Bare metal

### Browser

Chromium and Firefox

**Comment by shamoon** [comment] 2022-08-16 06:30
If you switch to the native PDF viewer (under settings) does it look ok?

**Comment by amo13** [comment] 2022-08-16 06:35
No, I just tried. The thumbnail is ok though.
Damn, I guess this is an issue with my system. I just noticed that it does look ok on safari with an ipad.
Do you have an idea which part of my system might be the culprit?
Thanks

**Comment by amo13** [comment] 2022-08-16 06:36
Oh wait, it does break on the ipad safari also if I untick "Use PDF viewer provided by the browser"...

**Comment by shamoon** [comment] 2022-08-31 16:33
So, to clarify:

- Generated PDF looks incorrect in every browser, using both "native" viewer and the built-in paperless viewer?
- If you view the same PDF in the system PDF viewer it looks OK?
- Any differences of archive vs original version?

**Comment by amo13** [comment] 2022-09-01 07:35
>     * Generated PDF looks incorrect in every browser, using both "native" viewer and the built-in paperless viewer?
No. On the paperless document edit page, 
* in Chromium and Safari the PDF look alright using the PDF viewer provided by the browser, but looks broken using the built-in paperless viewer.
* in Firefox the PDF looks broken with both the browser-provided and the paperless-built-in browser

>     * If you view the same PDF in the system PDF viewer it looks OK?
Yes, both original and archive PDF look alright in the system viewer outside the browser.

>     * Any differences of archive vs original version?
Yes, if I download the original version and open it in the browser, it looks alright, whereas the archive version does not.

Thanks for investigating

**Comment by shamoon** [comment] 2022-09-01 13:59
Great thank you. So this pretty clearly points to the pdf viewer being the issue, as I originally suspected. Our project uses https://github.com/VadimDez/ng2-pdf-viewer which itself uses https://github.com/mozilla/pdf.js , which of course forms the basis for the "built-in" PDF renderer in Firefox, so I would bet thats where the issue is. Especially if the OCR is correct, its likely just rendering incorrectly. Also note that ng2-pdf-viewer currently ships with pdf.js v2.14.305 which is a few versions behind. pdf.js is pretty actively being developed.

I suggest you open an issue with pdf.js and supply the pdf. Im going to close this here since its not something we can really control, also seems fairly rare.

**Closed by shamoon** 2022-09-01 13:59 UTC
Labels: bug, unconfirmed

**Comment by amo13** [comment] 2022-09-03 15:21
Wow, your diagnosis was very accurate :)
Some tests revealed to me that the issue was fixed in pdfjs 2.16.105.

**Comment by shamoon** [comment] 2022-09-03 16:09
Thank you for confirming that. It take a few more steps (the viewer updates pdf.js, we update the viewer etc) but hopefully shouldn’t be too long

**Comment by shamoon** [comment] 2022-09-05 20:43
Tracking https://github.com/VadimDez/ng2-pdf-viewer/pull/924
