### ISSUE TITLE
Docker compose - tried to run web service on port other than 8000

### ISSUE THREAD

**Issue by marlemion** [paperless-ngx/paperless-ngx#3801] opened 2023-07-14 13:11 UTC
### Description

Used the docker-compose file from git repository.

Ser port forwarding to 9111:8000

{"log":"2023-07-14 13:02:52,765 INFO success: gunicorn entered RUNNING state, process has stayed up for \u003e than 1 seconds (startsecs)\n","stream":"stdout","time":"2023-07-14T13:02:52.765842836Z"}
{"log":"[2023-07-14 13:02:52 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:52.772287079Z"}
{"log":"[2023-07-14 13:02:53 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:53.779637984Z"}
{"log":"[2023-07-14 13:02:54 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:54.787106739Z"}
{"log":"[2023-07-14 13:02:55 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:55.794589476Z"}
{"log":"[2023-07-14 13:02:56 +0000] [752] [ERROR] Can't connect to ('::', 8000)\n","stream":"stderr","time":"2023-07-14T13:02:56.796845322Z"}

Fiddled around with PAPERLESS_PORT / changing the port requests in the docker compose file from 8000 9111

Nothing worked so far. The docker solution should be working on other ports than 8000 (I have other services running thereon and other users might have that as well).

### Steps to reproduce

download docker compose file
change 8000:8000 to 9111:8000
start docker compose

### Webserver logs

```bash
{"log":"2023-07-14 13:02:52,765 INFO success: gunicorn entered RUNNING state, process has stayed up for \u003e than 1 seconds (startsecs)\n","stream":"stdout","time":"2023-07-14T13:02:52.765842836Z"}
{"log":"[2023-07-14 13:02:52 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:52.772287079Z"}
{"log":"[2023-07-14 13:02:53 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:53.779637984Z"}
{"log":"[2023-07-14 13:02:54 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:54.787106739Z"}
{"log":"[2023-07-14 13:02:55 +0000] [752] [ERROR] Retrying in 1 second.\n","stream":"stderr","time":"2023-07-14T13:02:55.794589476Z"}
{"log":"[2023-07-14 13:02:56 +0000] [752] [ERROR] Can't connect to ('::', 8000)\n","stream":"stderr","time":"2023-07-14T13:02:56.796845322Z"}
```

### Browser logs

```bash
doesnt matter
```

### Paperless-ngx version

latest

### Host OS

arch

### Installation method

Docker - official image

### Browser

doesnt matter

**Comment by ruedigerp** [comment] 2023-07-14 15:30
ENV:
PAPERLESS_BIND_ADDR
PAPERLESS_PORT
set this in docker-compose.env and restart with docker-compose.

**Comment by shamoon** [comment] 2023-07-14 16:07
Duplicate of #1765

**Closed by shamoon** 2023-07-14 16:07 UTC
Labels: bug, unconfirmed

**Comment by marlemion** [comment] 2023-07-17 11:15
I cannot confirm that setting PAPERLESS_BIND_ADDR to 0.0.0.0 changes anything. The problem persists.
