### ISSUE TITLE
[BUG] Paperless-NGX destroys electronically qualified signature in PDF's

### ISSUE THREAD

**Issue by sledzik1984** [paperless-ngx/paperless-ngx#2960] opened 2023-03-26 20:46 UTC
### Description

After uploading electronically signed document (qualified signature) - paperless destroys that signature. 

Digital signature is commonly used and ability to archive signed PDF's is a must. 

If paperless discovers that PDF file has signatures embedded should not change a bit in a file.

[after_paperless_processing.pdf](https://github.com/paperless-ngx/paperless-ngx/files/11073030/after_paperless_processing.pdf)
[Paperless-qualified-test-signed-before-paperless.pdf](https://github.com/paperless-ngx/paperless-ngx/files/11073031/Paperless-qualified-test-signed-before-paperless.pdf)

### Steps to reproduce

1. Digitally sign the PDF
2. Upload signed PDF to Paperless-NGX
3. Download PDF from Paperless-NGX 

Right now signatures vanished. 

### Webserver logs

```bash
None
```

### Paperless-ngx version

1.13.0

### Host OS

Debian

### Installation method

Docker - official image

### Browser

Chrome

**Comment by stumpylog** [comment] 2023-03-27 00:37
Duplicate of #1304

As discussed there, the original file is not changed by paperless and is always available for download.

**Closed by stumpylog** 2023-03-27 00:37 UTC
Labels: bug, unconfirmed
