### ISSUE TITLE
[BUG] Save Views dont respect selected fields and field ordering

### ISSUE THREAD

**Issue by soernt-poppe** [paperless-ngx/paperless-ngx#6596] opened 2024-05-07 07:01 UTC
### Description

I have some custom fields which I would like to get displayed within a grid.

### Steps to reproduce

 At the Settings->Saved Views page, I defined the columns which I would like to get displayed. When I now select a view, defined fields are not getting displayed. Within the "Show" drop down menue, they are selected for displaying. Atfer I unselect and relselect a field, it gets display within the grid.

### Webserver logs

```bash
paperless-gotenberg  |
paperless-gotenberg  |   _____     __           __
paperless-gotenberg  |  / ___/__  / /____ ___  / /  ___ _______ _
paperless-gotenberg  | / (_ / _ \/ __/ -_) _ \/ _ \/ -_) __/ _ '/
paperless-gotenberg  | \___/\___/\__/\__/_//_/_.__/\__/_/  \_, /
paperless-gotenberg  |                                    /___/
paperless-gotenberg  |
paperless-gotenberg  | A Docker-powered stateless API for PDF files.
paperless-gotenberg  | Version: 7.10.2
paperless-gotenberg  | -------------------------------------------------------
paperless-gotenberg  | [SYSTEM] modules: api chromium libreoffice libreoffice-api libreoffice-pdfengine logging pdfcpu pdfengines pdftk prometheus qpdf webhook
paperless-gotenberg  | [SYSTEM] libreoffice-api: LibreOffice ready to start
paperless-gotenberg  | [SYSTEM] pdfengines: libreoffice-pdfengine pdfcpu pdftk qpdf
paperless-gotenberg  | [SYSTEM] prometheus: collecting metrics
paperless-gotenberg  | [SYSTEM] chromium: Chromium ready to start
paperless-gotenberg  | [SYSTEM] api: server listening on port 3000
paperless-redis      | 1:C 07 May 2024 06:59:18.900 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
paperless-redis      | 1:C 07 May 2024 06:59:18.900 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
paperless-redis      | 1:C 07 May 2024 06:59:18.900 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=1, just started
paperless-redis      | 1:C 07 May 2024 06:59:18.900 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
paperless-redis      | 1:M 07 May 2024 06:59:18.900 * monotonic clock: POSIX clock_gettime
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * Running mode=standalone, port=6379.
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * Server initialized
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * Loading RDB produced by version 7.2.4
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * RDB age 17 seconds
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * RDB memory usage when created 1.39 Mb
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * Done loading RDB, keys loaded: 4, keys expired: 0.
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * DB loaded from disk: 0.000 seconds
paperless-redis      | 1:M 07 May 2024 06:59:18.901 * Ready to accept connections tcp
paperless-postgres   |
paperless-postgres   | PostgreSQL Database directory appears to contain a database; Skipping initialization
paperless-postgres   |
paperless-postgres   | 2024-05-07 06:59:18.992 UTC [1] LOG:  starting PostgreSQL 15.5 (Debian 15.5-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
paperless-postgres   | 2024-05-07 06:59:18.992 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
paperless-postgres   | 2024-05-07 06:59:18.992 UTC [1] LOG:  listening on IPv6 address "::", port 5432
paperless-postgres   | 2024-05-07 06:59:18.998 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
paperless-postgres   | 2024-05-07 06:59:19.026 UTC [30] LOG:  database system was shut down at 2024-05-07 06:59:01 UTC
paperless-postgres   | 2024-05-07 06:59:19.032 UTC [1] LOG:  database system is ready to accept connections
paperless-ngx        | Paperless-ngx docker container starting...
paperless-ngx        | Mapping UID and GID for paperless:paperless to 1000:1001
paperless-ngx        | usermod: no changes
paperless-ngx        | Creating directory scratch directory /tmp/paperless
paperless-ngx        | Adjusting permissions of paperless files. This may take a while.
paperless-ngx        | Waiting for PostgreSQL to start...
paperless-ngx        | Waiting for Redis...
paperless-ngx        | Connected to Redis broker.
paperless-ngx        | Apply database migrations...
paperless-tika       | INFO  [main] 06:59:20,431 org.apache.tika.server.core.TikaServerProcess Starting Apache Tika 2.9.0 server
paperless-tika       | INFO  [main] 06:59:20,542 org.apache.tika.server.core.TikaServerProcess loading resource from SPI: class org.apache.tika.server.standard.resource.XMPMetadataResource
paperless-tika       | May 07, 2024 6:59:20 AM org.apache.cxf.endpoint.ServerImpl initDestination
paperless-tika       | INFO: Setting the server's publish address to be http://0.0.0.0:9998/
paperless-tika       | INFO  [main] 06:59:20,720 org.eclipse.jetty.util.log Logging initialized @1279ms to org.eclipse.jetty.util.log.Slf4jLog
paperless-tika       | INFO  [main] 06:59:20,752 org.eclipse.jetty.server.Server jetty-9.4.51.v20230217; built: 2023-02-17T08:19:37.309Z; git: b45c405e4544384de066f814ed42ae3dceacdd49; jvm 17.0.9+9-Ubuntu-122.04
paperless-tika       | INFO  [main] 06:59:20,778 org.eclipse.jetty.server.AbstractConnector Started ServerConnector@2bc12da{HTTP/1.1, (http/1.1)}{0.0.0.0:9998}
paperless-tika       | INFO  [main] 06:59:20,778 org.eclipse.jetty.server.Server Started @1338ms
paperless-tika       | WARN  [main] 06:59:20,782 org.eclipse.jetty.server.handler.ContextHandler Empty contextPath
paperless-tika       | INFO  [main] 06:59:20,790 org.eclipse.jetty.server.handler.ContextHandler Started o.e.j.s.h.ContextHandler@4650a407{/,null,AVAILABLE}
paperless-tika       | INFO  [main] 06:59:20,798 org.apache.tika.server.core.TikaServerProcess Started Apache Tika server 35cd2d81-bd50-46a1-859a-d0a881a93b03 at http://0.0.0.0:9998/
paperless-ngx        | Operations to perform:
paperless-ngx        |   Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
paperless-ngx        | Running migrations:
paperless-ngx        |   No migrations to apply.
paperless-ngx        | Running Django checks
paperless-ngx        | System check identified no issues (0 silenced).
paperless-ngx        | Executing /usr/local/bin/paperless_cmd.sh
paperless-ngx        | 2024-05-07 06:59:24,554 INFO Set uid to user 0 succeeded
paperless-ngx        | 2024-05-07 06:59:24,555 INFO supervisord started with pid 1
paperless-ngx        | 2024-05-07 06:59:25,557 INFO spawned: 'gunicorn' with pid 103
paperless-ngx        | 2024-05-07 06:59:25,558 INFO spawned: 'celery' with pid 104
paperless-ngx        | 2024-05-07 06:59:25,559 INFO spawned: 'celery-beat' with pid 105
paperless-ngx        | 2024-05-07 06:59:25,560 INFO spawned: 'consumer' with pid 106
paperless-ngx        | 2024-05-07 06:59:25,561 INFO spawned: 'celery-flower' with pid 107
paperless-ngx        | Checking if we should start flower...
paperless-ngx        | Not starting flower
paperless-ngx        | 2024-05-07 06:59:25,566 INFO success: celery-flower entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
paperless-ngx        | 2024-05-07 06:59:25,566 INFO exited: celery-flower (exit status 0; expected)
paperless-ngx        | celery beat v5.4.0 (opalescent) is starting.
paperless-ngx        | 2024-05-07 06:59:27,419 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless-ngx        | 2024-05-07 06:59:27,419 INFO success: celery entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless-ngx        | 2024-05-07 06:59:27,419 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless-ngx        | 2024-05-07 06:59:27,419 INFO success: consumer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
paperless-ngx        | [2024-05-07 08:59:27 +0200] [103] [INFO] Starting gunicorn 22.0.0
paperless-ngx        | [2024-05-07 08:59:27 +0200] [103] [INFO] Listening at: http://[::]:8000 (103)
paperless-ngx        | [2024-05-07 08:59:27 +0200] [103] [INFO] Using worker: paperless.workers.ConfigurableWorker
paperless-ngx        | [2024-05-07 08:59:27 +0200] [103] [INFO] Server is ready. Spawning workers
paperless-ngx        | [2024-05-07 08:59:27,747] [WARNING] [paperless.management.consumer] Not consuming file /usr/src/paperless/consume/.streams/C3/D4/1AFD00000000000004003D0100000000/:Zone.Identifier:$DATA: Unknown file extension.
paperless-ngx        | [2024-05-07 08:59:27,747] [INFO] [paperless.management.consumer] Using inotify to watch directory for changes: /usr/src/paperless/consume
paperless-ngx        | __    -    ... __   -        _
paperless-ngx        | LocalTime -> 2024-05-07 08:59:27
paperless-ngx        | Configuration ->
paperless-ngx        |     . broker -> redis://broker:6379//
paperless-ngx        |     . loader -> celery.loaders.app.AppLoader
paperless-ngx        |     . scheduler -> celery.beat.PersistentScheduler
paperless-ngx        |     . db -> /usr/src/paperless/data/celerybeat-schedule.db
paperless-ngx        |     . logfile -> [stderr]@%INFO
paperless-ngx        |     . maxinterval -> 5.00 minutes (300s)
paperless-ngx        | [2024-05-07 08:59:27,778] [INFO] [celery.beat] beat: Starting...
paperless-ngx        | [2024-05-07 08:59:27,802] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
paperless-ngx        |
paperless-ngx        |  -------------- celery@d63ac3d04d24 v5.4.0 (opalescent)
paperless-ngx        | --- ***** -----
paperless-ngx        | -- ******* ---- Linux-5.10.60-qnap-x86_64-with-glibc2.36 2024-05-07 08:59:27
paperless-ngx        | - *** --- * ---
paperless-ngx        | - ** ---------- [config]
paperless-ngx        | - ** ---------- .> app:         paperless:0x7f71e3127950
paperless-ngx        | - ** ---------- .> transport:   redis://broker:6379//
paperless-ngx        | - ** ---------- .> results:
paperless-ngx        | - *** --- * --- .> concurrency: 1 (prefork)
paperless-ngx        | -- ******* ---- .> task events: ON
paperless-ngx        | --- ***** -----
paperless-ngx        |  -------------- [queues]
paperless-ngx        |                 .> celery           exchange=celery(direct) key=celery
paperless-ngx        |
paperless-ngx        |
paperless-ngx        | [tasks]
paperless-ngx        |   . documents.tasks.bulk_update_documents
paperless-ngx        |   . documents.tasks.consume_file
paperless-ngx        |   . documents.tasks.index_optimize
paperless-ngx        |   . documents.tasks.sanity_check
paperless-ngx        |   . documents.tasks.train_classifier
paperless-ngx        |   . documents.tasks.update_document_archive_file
paperless-ngx        |   . paperless_mail.mail.apply_mail_action
paperless-ngx        |   . paperless_mail.mail.error_callback
paperless-ngx        |   . paperless_mail.tasks.process_mail_accounts
paperless-ngx        |
paperless-ngx        | [2024-05-07 08:59:27,942] [INFO] [celery.worker.consumer.connection] Connected to redis://broker:6379//
paperless-ngx        | [2024-05-07 08:59:27,952] [INFO] [celery.apps.worker] celery@d63ac3d04d24 ready.
paperless-ngx        | [2024-05-07 08:59:27,954] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[989349cb-19cc-464a-8b04-eaa163b1985b] received
paperless-ngx        | [2024-05-07 08:59:28,721] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[989349cb-19cc-464a-8b04-eaa163b1985b] succeeded in 0.7544753830006812s: 'No new documents were added.'
paperless-ngx        | [2024-05-07 09:00:00,000] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
paperless-ngx        | [2024-05-07 09:00:00,002] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[349fc6c6-5357-424a-abce-cf94a61f0673] received
paperless-ngx        | [2024-05-07 09:00:00,765] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[349fc6c6-5357-424a-abce-cf94a61f0673] succeeded in 0.7607843349996983s: 'No new documents were added.'
paperless-ngx        | [2024-05-07 09:01:00,000] [INFO] [celery.beat] Scheduler: Sending due task Check all e-mail accounts (paperless_mail.tasks.process_mail_accounts)
paperless-ngx        | [2024-05-07 09:01:00,003] [INFO] [celery.worker.strategy] Task paperless_mail.tasks.process_mail_accounts[7e0c7736-1282-4787-8bbc-48a3df0ba19f] received
paperless-ngx        | [2024-05-07 09:01:00,745] [INFO] [celery.app.trace] Task paperless_mail.tasks.process_mail_accounts[7e0c7736-1282-4787-8bbc-48a3df0ba19f] succeeded in 0.7407436009998491s: 'No new documents were added.'
```

### Paperless-ngx version

2.8.1

### Host OS

Docker Image

### Installation method

Docker - official image

### Browser

Chrome

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-05-07 07:03
Thanks. This sounds like a duplicate of #6592

**Comment by shamoon** [comment] 2024-05-07 07:04
Make sure you have the current 2.8.1 docker image

**Closed by shamoon** 2024-05-07 07:03 UTC
Labels: bug, unconfirmed

**Comment by soernt-poppe** [comment] 2024-05-07 07:15
Thank you very much. The fields now gets displayed. But the field ordering ist not what I defined within the Settings->Saved Views page. It the field ordering not supported?

**Comment by shamoon** [comment] 2024-05-07 07:17
Ordering only applies to the dashboard

**Comment by soernt-poppe** [comment] 2024-05-07 07:30
The "display field" issue still exists within the default "Documents" view.
It is selected for display, but did not get displayed until I unselect and reselect the field.

**Comment by shamoon** [comment] 2024-05-07 07:38
Ah, for tables again yes. I'll sort it out.
