### ISSUE TITLE
[BUG] document_exporter does not export the storage paths

### ISSUE THREAD

**Issue by ThomasMuenster** [paperless-ngx/paperless-ngx#1618] opened 2022-09-20 18:12 UTC
### Description

The document exporter does not export the storage groups. These are missing in the manifest.json. 

The Importer cannot import the exported data. It fails with this messages: 

root:/usr/src/paperless/src# document_importer ../export
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_importer.py", line 112, in handle
    call_command("loaddata", manifest_path)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 198, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 102, in handle
    self.loaddata(fixture_labels)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/loaddata.py", line 171, in loaddata
    connection.check_constraints(table_names=table_names)
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 383, in check_constraints
    raise IntegrityError(
django.db.utils.IntegrityError: Problem installing fixtures: The row in table 'documents_document' with primary key '2' has an invalid foreign key: documents_document.storage_path_id contains a value '1' that does not have a corresponding value in documents_storagepath.id.

### Steps to reproduce

create storage path with associated document

use document exporter

try to import with document importer

### Paperless-ngx version

1.8.0

### Host OS

unraid

### Installation method

Docker - official image

### Browser

firefox

**Comment by stumpylog** [comment] 2022-09-20 19:23
This is a duplicate of #1554 and is fixed in the next release.

**Comment by shamoon** [comment] 2022-09-20 19:23
Thanks for the report, this one (and the other you reported) have already been fixed and are being tested in our current [beta](https://github.com/paperless-ngx/paperless-ngx/pull/1560). Gentle reminder to search before opening an issue, but thanks again.

See #1554

**Closed** 2022-09-20 19:23 UTC
Labels: bug, unconfirmed
