### ISSUE TITLE
[BUG] conversion between UTF8 and SQL_ASCII is not supported [update to 2.8.0]

### ISSUE THREAD

**Issue by fcarucci** [paperless-ngx/paperless-ngx#6586] opened 2024-05-06 22:44 UTC
### Description

Hello, I just updated the docker image to 2.8.0 and I get this error on start.
Reverting to 2.7.2 fixes the issue.

### Steps to reproduce

1. Update to 2.8.0
2. Start docker service

### Webserver logs

```bash
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
Waiting for PostgreSQL to start...
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.FeatureNotSupported: conversion between UTF8 and SQL_ASCII is not supported
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 235, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 831, in alter_field
    self._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 288, in _alter_field
    super()._alter_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 1056, in _alter_field
    self.execute(
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.NotSupportedError: conversion between UTF8 and SQL_ASCII is not supported
  Applying auditlog.0015_alter_logentry_changes...
```

### Paperless-ngx version

2.8.8

### Host OS

Ubuntu 22.03

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-05-06 22:48
Looks like an issue with auditlog.  I would report it upstream, if it hasn't been already: https://github.com/jazzband/django-auditlog/issues

**Comment by stumpylog** [comment] 2024-05-06 22:49
I would also make sure your database is using UTF-8.  That's really the only encoding to ever use

**Comment by stumpylog** [comment] 2024-05-06 22:59
Yeah, I can't reproduce this with a proper encoding database.  It should look like this for you:

```
                                                        List of databases
   Name    |   Owner   | Encoding | Locale Provider |  Collate   |   Ctype    | ICU Locale | ICU Rules |    Access privileges
-----------+-----------+----------+-----------------+------------+------------+------------+-----------+-------------------------
 paperless | paperless | UTF8     | libc            | en_US.utf8 | en_US.utf8 |            |           |
```

I don't know about the process of converting.  An export/import with a fresh database should create it as UTF-8

**Comment by fcarucci** [comment] 2024-05-06 23:24
Thanks, I'm pretty sure I converted to UTF-8 a while ago because of a similar issue. It's working fine with 2.7.2.

**Comment by stumpylog** [comment] 2024-05-06 23:33
Something isn't converted or they have an issue with their migration.  As mentioned, I cannot reproduce, so I presume the former.

**Comment by fcarucci** [comment] 2024-05-06 23:45
I stand corrected, I'm still on ASCII.

**Comment by shamoon** [comment] 2024-05-07 00:31
Closing as above, thanks for investigating stumpy. Perhaps we should mention utf-8 in our docs (if we don’t already).

OP, feel free to update this thread if you have more to add or eg open an issue upstream.

**Closed by shamoon** 2024-05-07 00:31 UTC
Labels: cant-reproduce

**Comment by ronnyandre** [comment] 2024-05-26 20:01
@fcarucci Did you solve this by converting to UTF-8? How did you do that?

**Comment by fcarucci** [comment] 2024-05-26 20:28
Yes, I did what stumpylog recommended and converted to UTF8. I did a pgdump, recreated the database with the correct format, then pgrestore and updated to latest. Worked seemlessly. Thanks so much for your help, @stumpylog.
