### ISSUE TITLE
[BUG] Password reset after docker container restarted

### ISSUE THREAD

**Issue by alexthamm** [paperless-ngx/paperless-ngx#140] opened 2022-02-24 08:55 UTC
*Copy from old repository*: https://github.com/jonaswinkler/paperless-ng/issues/1511

**Describe the bug**
I deployed Paperless-NG in TrueNAS via the TrueCharts integration. TrueCharts uses the official docker container and passes environment variables to configure the superuser.

I changed the admin password in the Django admin interface. However, after redeploying the application (for example due to an update) the password gets overridden by the initial password passed via environment variable.

**To Reproduce**
1. Deploy Paperless with credentials admin//secret
2. Open Paperless
3. Navigate to admin interface
4. Change password to "mysupersecretpassword"
5. Restart/update the docker container
6. Navigate to Paperless and try to login with admin/mysupersecretpassword
7. You can't login.

**Expected behavior**
The admin password should not be overridden by the initial password.

**Relevant information**
 - Version 
 - Installation method: **docker**
 - Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`. -

I think this is related to the admin user password reset when the docker container is started:
docker-entrypoint.sh calls docker-prepare.sh calls the manage_superuser mgmt command and there the password is updated:
https://github.com/jonaswinkler/paperless-ng/blob/master/src/documents/management/commands/manage_superuser.py#L29

Am I missing something?

**Comment by FrankStrieter** [comment] 2022-02-24 18:06
@alexthamm this is by design. https://paperless-ngx.readthedocs.io/en/latest/configuration.html#configuration see the section of `PAPERLESS_ADMIN_USER` and `PAPERLESS_ADMIN_PASSWORD`. Otherwise, you are able to lock out the admin user. Maybe the only improvement here can be, to disable password changes for the admin user in UI and API.

The "Superuser" should only be used to configure paperless-ngx add (restricted) admins or employees users.

**Comment by shamoon** [comment] 2022-02-24 18:57
Yea, I think the point is you should set `PAPERLESS_ADMIN_PASSWORD` to 'mysupersecretpassword', problem solved, no?

**Comment by schnuffle** [comment] 2022-02-24 19:09
Most of the compose services I'm running follow the pattern:

1. Check if admin account exists
2. IF not create it with the given password
3. If it's already existing, do nothing

I checked the django management command https://github.com/paperless-ngx/paperless-ngx/blob/main/src/documents/management/commands/manage_superuser.py

It would be a small change, to adopt it'S behaviour and I think from a security standpoint it's better.
The comments state that it has been the default behaviour until apparently someone changed the behaviour. And it has been changed without adopting the input checks, so I would call it broken.

So maybe we should cleanup.

I can create a PR that would change the django management command so it has following behaviour:

1. Define a New parameter: PAPERLESS_ADMIN_FORCE
2.  Check if super_user exists
3. Yes -> Only change password if PAPERLESS_ADMIN_FORCE
4. No -> Create Super User

Regards

Schnuffle

**Comment by alexthamm** [comment] 2022-02-25 13:21
Hi all, thanks for your feedback!

However, I don't agree with the concept of setting the password somewhere readable (even iff the admin is supposed to have access to this information).
One of Django's best features is the user management. This includes storage of *securely hashed* passwords. Setting the password in the environment variable contradicts this idea.

@FrankStrieter 
> Otherwise, you are able to lock out the admin user. Maybe the only improvement here can be, to disable password changes for the admin user in UI and API.
Django has a management command and you can use the shell to override the admin/user password:
-> https://docs.djangoproject.com/en/3.2/topics/auth/default/#changing-passwords

IMO the management command should be documented and the password should never be touched by the environment/start scripts after the initial setup.

What do you think about this?

**Comment by schnuffle** [comment] 2022-02-25 17:43
I happily aggree, The offer of a PAPERLESS_ADMIN_FORCE was to compromise. In the end it would be a shortcut to call the django manage.py inside the container.
I'm totally in favour of restricting dockers influence on the containers state purely to the setup.

The mentioned additional management command already exists and is used to create the super user. I linked to the code above.
So it's not a question of doing it, more about dropping it by using standard django manage commands or adopting it, so it has a sane behaviour
The advantage of having it, is that you have a precise place where you define the logic, in contrast to severall django commands.
The drawback, of course it's some lines of code.

My opinion:
Keep it with following logic:
If user exists -> do nothing
Else -> create super user


Regards

Schnuffle

**Comment by schnuffle** [comment] 2022-02-27 19:48
So should I create a PR?

Regards

Schnuffle

**Comment by schnuffle** [comment] 2022-03-04 11:19
Here's the new PR: #208

**Comment by schnuffle** [comment] 2022-03-05 11:47
The logic needed to become a bit more complex as the user "consumer" is created during migration 

The admin user with username "admin" and password from env variable PAPERLESS_ADMIN_PASSWORD is created when:

- There's no user or superuser called admin
- There's no superuser with other name
- PAPERLESS_ADMIN_PASSWORD is provided

**Comment by m3nu** [comment] 2022-04-29 13:43
Please reopen. This is still an issue. If a user exists, this env var should do nothing.

**Comment by qcasey** [comment] 2022-04-29 13:53
Yep, the PR has to be rebased and reviewed still.

**Comment by qcasey** [comment] 2022-05-11 00:08
Fixed in next release as of #903

**Closed by qcasey** 2022-05-11 00:08 UTC
Labels: bug, imported
