### ISSUE TITLE
[BUG] Minor translation Issues

### ISSUE THREAD

**Issue by sukisoft** [paperless-ngx/paperless-ngx#1317] opened 2022-08-01 04:49 UTC
### Description

I came across the new update checker and it seems somewhere the version string isn't correct. I searched in crowdin, but i couldnt find the translation. Maybe the double "v" should be removed.

![2022-08-01_06-13](https://user-images.githubusercontent.com/88422038/182074326-578c38cf-51e8-41e8-90fb-5d3cab1e94e4.png)

Also, when loading paperless-ngx from my nas, when it isnt started yet, but the browser tries zu restore the page, this text is provided which should be translated. 

![2022-08-01_06-09](https://user-images.githubusercontent.com/88422038/182074407-903ed7c4-15b7-40da-90ea-dd5038217e87.png)

### Steps to reproduce

1. load paperless from a device which isnt started or does not provide the page anymore
2. see the message

### Paperless-ngx version

1.7.1

### Host OS

Synology DSM

### Installation method

Docker - official image

### Browser

Chrome Version 103.0.5060.114

### Configuration changes

none of relevance

**Comment by shamoon** [comment] 2022-08-01 16:05
Hmm, these are odd.

- I cannot reproduce the 'vv' thing and I dont know why it would be happening. Nowhere in the code does it add a 'v', the process is:
    - Ping https://api.github.com/repos/paperless-ngx/paperless-ngx/releases/latest , I verified this has `"tag_name": "v1.8.0"`
    - Pass that version string along via API see https://github.com/paperless-ngx/paperless-ngx/blob/20671c718e2620ea8dbca2e37efe6371b65fd12f/src/documents/views.py#L727
    - The UI displays it (if needed) untouched, see https://github.com/paperless-ngx/paperless-ngx/blob/20671c718e2620ea8dbca2e37efe6371b65fd12f/src-ui/src/app/components/app-frame/app-frame.component.html#L205 + https://github.com/paperless-ngx/paperless-ngx/blob/20671c718e2620ea8dbca2e37efe6371b65fd12f/src-ui/src/app/components/app-frame/app-frame.component.ts#L47
    - As you noted there is no translation around the actual version string
    - Again, Im not seeing that (screenshot) <img width="238" alt="Screen Shot 2022-08-01 at 8 50 16 AM" src="https://user-images.githubusercontent.com/4887959/182189032-8fb4b49c-a7ce-4f62-8bdd-6a5fe818683d.png">

- As for the translated warning message, it already should be translated, see https://github.com/paperless-ngx/paperless-ngx/blob/20671c718e2620ea8dbca2e37efe6371b65fd12f/src/documents/templates/index.html#L79 + https://crowdin.com/translate/paperless-ngx/14/en-de#1464 --> https://github.com/paperless-ngx/paperless-ngx/blob/20671c718e2620ea8dbca2e37efe6371b65fd12f/src/locale/de_DE/LC_MESSAGES/django.po#L405
- Again, cannot reproduce, screenshot: <img width="716" alt="Screen Shot 2022-08-01 at 9 04 27 AM" src="https://user-images.githubusercontent.com/4887959/182191549-2022b47e-9a10-4c80-80d0-c42dae6cccab.png">


So honestly, Im not sure why youre seeing either one of them. Have you tried basic stuff like clearing all browser cache, restarting containers, etc?

**Comment by shamoon** [comment] 2022-08-01 16:07
Ohh! It occurs to me what you are using v1.7.1, in other words both of these are fixed now but weren't then =)
E.g. https://github.com/paperless-ngx/paperless-ngx/pull/1090 etc.

**Closed by shamoon** 2022-08-01 16:07 UTC
Labels: bug, unconfirmed
