### ISSUE TITLE
[BUG] gotenberg URL path not working

### ISSUE THREAD

**Issue by nheine** [paperless-ngx/paperless-ngx#2215] opened 2022-12-19 10:49 UTC
### Description

![image](https://user-images.githubusercontent.com/5304481/208408169-c727d202-04ec-43a7-91bc-8cdcd5a9b0e7.png)

I checked the URL from the webserver console. Its OK. http://gotenberg:3000/health works fine too.

Here the log of the gotenberg server

`{"level":"error","ts":1671446495.1393292,"logger":"api","msg":"convert to PDF: lock long-running LibreOffice listener: acquire LibreOffice listener lock: context deadline exceeded","trace":"2c5cc6c0-87fb-4841-bfd8-d0a6bc31feb6","remote_ip":"172.22.0.6","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"python-requests/2.28.1","status":503,"latency":30002038461,"latency_human":"30.002038461s","bytes_in":126484,"bytes_out":19}
`
Any ideas what this can be?

### Steps to reproduce

1. upload docx file through paperless-ngx website
2. receive error as above screenshot

### Webserver logs

```bash
`{"level":"error","ts":1671446495.1393292,"logger":"api","msg":"convert to PDF: lock long-running LibreOffice listener: acquire LibreOffice listener lock: context deadline exceeded","trace":"2c5cc6c0-87fb-4841-bfd8-d0a6bc31feb6","remote_ip":"172.22.0.6","host":"gotenberg:3000","uri":"/forms/libreoffice/convert","method":"POST","path":"/forms/libreoffice/convert","referer":"","user_agent":"python-requests/2.28.1","status":503,"latency":30002038461,"latency_human":"30.002038461s","bytes_in":126484,"bytes_out":19}
`
```

### Browser logs

```bash
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/paperless/src/documents/tasks.py", line 177, in consume_file
    document = Consumer().try_consume_file(
  File "/usr/src/paperless/src/documents/consumer.py", line 356, in try_consume_file
    self._fail(
  File "/usr/src/paperless/src/documents/consumer.py", line 91, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: 123.docx: Error while consuming document 123.docx: Error while converting document to PDF: 503 Server Error: Service Unavailable for url: http://gotenberg:3000/forms/libreoffice/convert
```

### Paperless-ngx version

1.10.2

### Host OS

Raspberry 64

### Installation method

Docker - official image

**Comment by stumpylog** [comment] 2022-12-19 14:23
Duplicate of #2116.

Unfortunately we can't do anything about Gotenberg.  It seems to struggle with some Word files in particular.  Some people have had success with downgrades or upgrades of the image.

**Closed by stumpylog** 2022-12-19 14:23 UTC
Labels: bug, unconfirmed
