### ISSUE TITLE
[BUG] Applying filters on page >1 throws error

### ISSUE THREAD

**Issue by feuerwasser85** [paperless-ngx/paperless-ngx#997] opened 2022-05-20 16:55 UTC
### Description

By clicking on "documents" on the left side panel and clicking on a random page under "reset filter" when i click on a tag on a document or selecting a document type/correspondent/tag from the drop down menus, i get the Error "Fehler beim Laden des Dokuments: undefined: U". This can be reproduced by resetting the filter, clicking on page 1, clicking on "Startseite" and start again.
![image](https://user-images.githubusercontent.com/10442073/169574831-1cd59d2b-a32b-4f14-9902-c122d6516411.png)

### Steps to reproduce

1. clicking on "documents" on the left side panel
2. clicking on a random page under "reset filter"
3. clicking on a tag/correspondent/document type on a document or selecting a document type/correspondent/tag from the drop down menus
4. Getting an error message

### Webserver logs

```bash
[2022-05-20 18:51:49,711] [WARNING] [django.request] Not Found: /api/documents/
[2022-05-20 18:51:49,760] [WARNING] [django.request] Not Found: /api/documents/
[2022-05-20 18:51:49,806] [WARNING] [django.request] Not Found: /api/documents/
[2022-05-20 18:51:49,852] [WARNING] [django.request] Not Found: /api/documents/
[2022-05-20 18:51:49,895] [WARNING] [django.request] Not Found: /api/documents/
```

### Paperless-ngx version

1.7.1

### Host OS

Synology DS920+ (BusyBox Linux mediaserver 4.4.180+ x86_64 GNU/Linux synology_geminilake_920+)

### Installation method

Docker

### Browser

Chrome 101.0.4951.67 64bit

**Comment by shamoon** [comment] 2022-05-20 16:58
Ah, the page param. I'll have to sort this out, thanks.

**Comment by feuerwasser85** [comment] 2022-05-21 10:55
Thanks for fixing!

**Comment by qcasey** [comment] 2022-05-26 15:19
This should be fixed as of #1000

**Closed by qcasey** 2022-05-26 15:19 UTC
Labels: bug, frontend

**Comment by iSnackyCracky** [comment] 2022-08-04 18:33
This should be already fixed in the current 1.8.0 version, right?
Cause this still happens on my instance:

I open a saved view (with some filters), when then trying to navigate to the next page, I get back to "all documents" with the last filter that was set there (when there is a filter configured, I get the issue described in this bugreport - `undefined: U`).

**Comment by shamoon** [comment] 2022-08-04 22:17
Oh thank you, this looks like a regression that must have come back from the dead, I think its a little different actually so will create a new issue.

**Comment by Michael1337** [comment] 2023-01-26 18:58
I just had this issue, but I don't know why. I got an error when I navigated to /settings/mail and then the app kind of froze, i. e. I couldn't view documents and some other parts of the app. Using version 1.12.1. Being on Docker, I could just restart the container and didn't get another error.
