### ISSUE TITLE
[BUG] Cannot consume file.pdf: File not found.

### ISSUE THREAD

**Issue by horvatkm** [paperless-ngx/paperless-ngx#8111] opened 2024-10-30 09:03 UTC
### Description

While importing my magazine collection into paperless, I'm getting "Cannot consume"  error for about 1/3 of imported files. Weird thing is, that such documents are actually correctly consumed. For some reason, sometimes document consumption is later performed again and it fails, because document has been processed and deleted earlier.

I'm importing into empty paperless instance. Currently 439 documents have been successfully imported. File tasks shows 124 failed and 315 complete tasks.

Log files are also somewhat large, therefore I've included all messages for a file, which gave "Cannot consume" error first time. If necessary, I can attach whole zipped logs

Configuration change field in bug report form is single line, therefore I'm putting it here
PAPERLESS_OCR_LANGUAGE=ces
PAPERLESS_TASK_WORKERS=8
PAPERLESS_THREADS_PER_WORKER=3
PAPERLESS_TIME_ZONE=Europe/Prague
PAPERLESS_CONSUMER_POLLING=10
PAPERLESS_CONSUMER_RECURSIVE=true
PAPERLESS_PRE_CONSUME_SCRIPT=/opt/paperless/scripts/pre-consumption.sh
PAPERLESS_POST_CONSUME_SCRIPT=/opt/paperless/scripts/post-consumption.sh
PAPERLESS_GS_BINARY=/usr/local/bin/gs

Pre/post consumption scripts are processing metadata only, not touching any files, therefore they shouldn't have any influence on this issue. But for the sake of completeness, I've included them as well.

[scripts.zip](https://github.com/user-attachments/files/17568808/scripts.zip)

### Steps to reproduce

Reproducing the issue may be somewhat complicated, since I'm importing fairly large collection of documents, 1238 files, total size 8976MB. But it's probably possible to reproduce the issue even with subset of these documents. First such error occurred after processing 220 files with size 920MB. If needed, I could upload it somewhere.

The issue is not caused by a file being queued multiple times, since adding number of failed+complete+started+queued is giving 1238.

### Webserver logs

```bash
paperless.log
----------------------------------
[2024-10-29 21:56:08,957] [DEBUG] [paperless.management.consumer] Waiting for file /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf to remain unmodified
[2024-10-29 21:56:13,962] [INFO] [paperless.management.consumer] Adding /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf to the task queue.
[2024-10-30 01:21:25,446] [INFO] [paperless.consumer] Consuming RK - 1966 - 05.pdf
[2024-10-30 01:21:25,459] [DEBUG] [paperless.consumer] Detected mime type: application/pdf
[2024-10-30 01:21:25,460] [INFO] [paperless.consumer] Executing pre-consume script /opt/paperless/scripts/pre-consumption.sh
[2024-10-30 01:21:25,490] [INFO] [paperless.consumer] /opt/paperless/scripts/pre-consumption.sh exited 0
[2024-10-30 01:21:25,491] [INFO] [paperless.consumer] /opt/paperless/scripts/pre-consumption.sh stdout:
[2024-10-30 01:21:25,492] [INFO] [paperless.consumer] A tash with an id of 3e1c9e43-042a-4f40-9631-a8a2013df8e1 was just started.  I know the
[2024-10-30 01:21:25,492] [INFO] [paperless.consumer] following additional information about it:
[2024-10-30 01:21:25,493] [INFO] [paperless.consumer] 
[2024-10-30 01:21:25,493] [INFO] [paperless.consumer] * Source path: /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf
[2024-10-30 01:21:25,494] [INFO] [paperless.consumer] * Working path: /tmp/paperless/paperless-ngxyhl7l5kx/RK - 1966 - 05.pdf
[2024-10-30 01:21:25,494] [INFO] [paperless.consumer] 
[2024-10-30 01:21:25,494] [INFO] [paperless.consumer] redis-cli set DSP3e1c9e43-042a-4f40-9631-a8a2013df8e1 /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf
[2024-10-30 01:21:25,495] [INFO] [paperless.consumer] OK
[2024-10-30 01:21:25,495] [INFO] [paperless.consumer] DSP is /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf
[2024-10-30 01:21:25,504] [DEBUG] [paperless.consumer] Parser: RasterisedDocumentParser
[2024-10-30 01:21:25,512] [DEBUG] [paperless.consumer] Parsing RK - 1966 - 05.pdf...
[2024-10-30 01:21:25,533] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
[2024-10-30 01:21:25,696] [DEBUG] [paperless.parsing.tesseract] Calling OCRmyPDF with args: {'input_file': PosixPath('/tmp/paperless/paperless-ngxyhl7l5kx/RK - 1966 - 05.pdf'), 'output_file': PosixPath('/tmp/paperless/paperless-2kkq3lj0/archive.pdf'), 'use_threads': True, 'jobs': '3', 'language': 'ces', 'output_type': 'pdfa', 'progress_bar': False, 'color_conversion_strategy': 'RGB', 'skip_text': True, 'clean': True, 'deskew': True, 'rotate_pages': True, 'rotate_pages_threshold': 12.0, 'sidecar': PosixPath('/tmp/paperless/paperless-2kkq3lj0/sidecar.txt')}
[2024-10-30 01:21:26,129] [INFO] [ocrmypdf._pipelines.ocr] Start processing 3 pages concurrently
[2024-10-30 01:21:26,451] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2024-10-30 01:21:29,932] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 20.47 - rotation appears correct
[2024-10-30 01:40:24,182] [DEBUG] [paperless.parsing.tesseract] Using text from sidecar file
[2024-10-30 01:40:24,215] [DEBUG] [paperless.consumer] Generating thumbnail for RK - 1966 - 05.pdf...
[2024-10-30 01:40:24,223] [DEBUG] [paperless.parsing] Execute: convert -density 300 -scale 500x5000> -alpha remove -strip -auto-orient -define pdf:use-cropbox=true /tmp/paperless/paperless-2kkq3lj0/archive.pdf[0] /tmp/paperless/paperless-2kkq3lj0/convert.webp
[2024-10-30 01:40:26,528] [INFO] [paperless.parsing] convert exited 0
[2024-10-30 01:40:29,692] [INFO] [ocrmypdf._pipeline] page is facing ⇧, confidence 19.22 - rotation appears correct
[2024-10-30 01:40:30,420] [DEBUG] [paperless.classifier] Document classification model does not exist (yet), not performing automatic matching.
[2024-10-30 01:40:30,426] [DEBUG] [paperless.consumer] Saving record to database
[2024-10-30 01:40:30,427] [DEBUG] [paperless.consumer] Creation date from parse_date: 1964-01-13 00:00:00+01:00
[2024-10-30 01:40:31,827] [DEBUG] [paperless.consumer] Deleting file /tmp/paperless/paperless-ngxyhl7l5kx/RK - 1966 - 05.pdf
[2024-10-30 01:40:31,831] [DEBUG] [paperless.parsing.tesseract] Deleting directory /tmp/paperless/paperless-2kkq3lj0
[2024-10-30 01:40:31,837] [INFO] [paperless.consumer] Executing post-consume script /opt/paperless/scripts/post-consumption.sh
[2024-10-30 01:40:33,735] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2024-10-30 01:40:34,557] [WARNING] [ocrmypdf._exec.tesseract] [tesseract] lots of diacritics - possibly poor OCR
[2024-10-30 01:40:37,731] [INFO] [paperless.consumer] /opt/paperless/scripts/post-consumption.sh exited 0
[2024-10-30 01:40:37,732] [INFO] [paperless.consumer] /opt/paperless/scripts/post-consumption.sh stdout:
[2024-10-30 01:40:37,732] [INFO] [paperless.consumer] A document with an id of 258 was just consumed.  I know the
[2024-10-30 01:40:37,733] [INFO] [paperless.consumer] following additional information about it:
[2024-10-30 01:40:37,733] [INFO] [paperless.consumer] 
[2024-10-30 01:40:37,734] [INFO] [paperless.consumer] * Generated File Name: 1964-01-13 RK - 1966 - 05.pdf
[2024-10-30 01:40:37,734] [INFO] [paperless.consumer] * Archive Path: /opt/paperless/media/documents/archive/0000258.pdf
[2024-10-30 01:40:37,735] [INFO] [paperless.consumer] * Source Path: /opt/paperless/media/documents/originals/0000258.pdf
[2024-10-30 01:40:37,735] [INFO] [paperless.consumer] * Created: 1964-01-12 23:00:00+00:00
[2024-10-30 01:40:37,736] [INFO] [paperless.consumer] * Added: 2024-10-30 00:40:30.452909+00:00
[2024-10-30 01:40:37,736] [INFO] [paperless.consumer] * Modified: 2024-10-30 00:40:31.808308+00:00
[2024-10-30 01:40:37,736] [INFO] [paperless.consumer] * Thumbnail Path: /opt/paperless/media/documents/thumbnails/0000258.webp
[2024-10-30 01:40:37,737] [INFO] [paperless.consumer] * Download URL: /api/documents/258/download/
[2024-10-30 01:40:37,737] [INFO] [paperless.consumer] * Thumbnail URL: /api/documents/258/thumb/
[2024-10-30 01:40:37,737] [INFO] [paperless.consumer] * Owner Name: 
[2024-10-30 01:40:37,738] [INFO] [paperless.consumer] * Correspondent: None
[2024-10-30 01:40:37,738] [INFO] [paperless.consumer] * Tags: 
[2024-10-30 01:40:37,738] [INFO] [paperless.consumer] * Task ID: 3e1c9e43-042a-4f40-9631-a8a2013df8e1
[2024-10-30 01:40:37,739] [INFO] [paperless.consumer] 
[2024-10-30 01:40:37,739] [INFO] [paperless.consumer] It was consumed with the passphrase 
[2024-10-30 01:40:37,740] [INFO] [paperless.consumer] 
[2024-10-30 01:40:37,740] [INFO] [paperless.consumer] magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf
[2024-10-30 01:40:37,740] [INFO] [paperless.consumer] declare -a a=([0]="magazines" [1]="Amaterske Radio" [2]="1966" [3]=$'RK - 1966 - 05.pdf\n')
[2024-10-30 01:40:37,741] [INFO] [paperless.consumer] doc type str is  magazines
[2024-10-30 01:40:37,741] [INFO] [paperless.consumer] title is  Amaterske Radio
[2024-10-30 01:40:37,741] [INFO] [paperless.consumer] year is 1966
[2024-10-30 01:40:37,742] [INFO] [paperless.consumer] doc type ID is  2
[2024-10-30 01:40:37,742] [INFO] [paperless.consumer] 1
[2024-10-30 01:40:37,743] [INFO] [paperless.consumer] Document 1964-01-13 RK - 1966 - 05 consumption finished
[2024-10-30 01:40:37,757] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 258 created

[2024-10-30 02:30:14,941] [ERROR] [paperless.consumer] Cannot consume /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf: File not found.
[2024-10-30 02:30:14,942] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: RK - 1966 - 05.pdf: Cannot consume /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf: File not found.
Traceback (most recent call last):
  File "/opt/paperless/src/documents/tasks.py", line 148, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/opt/paperless/src/documents/consumer.py", line 368, in run
    self.pre_check_file_exists()
  File "/opt/paperless/src/documents/consumer.py", line 158, in pre_check_file_exists
    self._fail(
  File "/opt/paperless/src/documents/consumer.py", line 151, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: RK - 1966 - 05.pdf: Cannot consume /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf: File not found.

[2024-10-30 03:27:22,769] [ERROR] [paperless.consumer] Cannot consume /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf: File not found.
[2024-10-30 03:27:22,771] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: RK - 1966 - 05.pdf: Cannot consume /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf: File not found.
Traceback (most recent call last):
  File "/opt/paperless/src/documents/tasks.py", line 148, in consume_file
    msg = plugin.run()
          ^^^^^^^^^^^^
  File "/opt/paperless/src/documents/consumer.py", line 368, in run
    self.pre_check_file_exists()
  File "/opt/paperless/src/documents/consumer.py", line 158, in pre_check_file_exists
    self._fail(
  File "/opt/paperless/src/documents/consumer.py", line 151, in _fail
    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
documents.consumer.ConsumerError: RK - 1966 - 05.pdf: Cannot consume /opt/paperless/consume/magazines/Amaterske Radio/1966/RK - 1966 - 05.pdf: File not found.
```

### Browser logs

```bash
--  no issues with browser --
```

### Paperless-ngx version

2.13.1

### Host OS

Debian 12/x86_64

### Installation method

Bare metal

### System status

```json
{
    "pngx_version": "2.13.1",
    "server_os": "Linux-6.8.12-2-pve-x86_64-with-glibc2.36",
    "install_type": "bare-metal",
    "storage": {
        "total": 83955703808,
        "available": 37976518656
    },
    "database": {
        "type": "postgresql",
        "url": "paperlessdb",
        "status": "OK",
        "error": null,
        "migration_status": {
            "latest_migration": "paperless_mail.0011_remove_mailrule_assign_tag_squashed_0024_alter_mailrule_name_and_more",
            "unapplied_migrations": []
        }
    },
    "tasks": {
        "redis_url": "redis://localhost:6379",
        "redis_status": "OK",
        "redis_error": null,
        "celery_status": "OK",
        "index_status": "OK",
        "index_last_modified": "2024-10-30T09:44:45.226971+01:00",
        "index_error": null,
        "classifier_status": "WARNING",
        "classifier_last_trained": null,
        "classifier_error": "Classifier file does not exist (yet). Re-training may be pending."
    }
}
```

### Browser

Firefox

### Configuration changes

see above

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by stumpylog** [comment] 2024-10-30 12:53
I can't tell from the logs, bit e this is usually caused by the file being queued multiple times.  In fact it's the only way it could be caused.  If you dropped a large amount of files in the folder, particularly in folders, inotify had trouble keeping up, just because of how it is.

Certainly not a reproducible bug.

**Comment by shamoon** [comment] 2024-10-31 14:08
Closing as there’s nothing actionable here. Feel free to add more context.

**Closed by shamoon** 2024-10-31 14:08 UTC
Labels: cant-reproduce

**Comment by jdelker** [comment] 2024-11-01 16:56
I have the same problem, even with a single file placed into the import directory via SMB. 

Here my log excerpt to hopefully give more insight. It shows what happened, when I placed a single file (`R552238842.pdf`) via SMB into the import directory:
```
webserver-1  | [2024-11-01 17:23:50,743] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/R552238842.pdf to the task queue.
webserver-1  | [2024-11-01 17:23:55,480] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[df1ff5bb-d0c4-4da1-8c5a-99608003c89a] received
webserver-1  | [2024-11-01 17:23:57,718] [INFO] [paperless.tasks] BarcodePlugin completed with no message
webserver-1  | [2024-11-01 17:23:57,724] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:
webserver-1  | [2024-11-01 17:23:57,927] [INFO] [paperless.consumer] Consuming R552238842.pdf
webserver-1  | [2024-11-01 17:23:57,999] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
webserver-1  | [2024-11-01 17:24:01,287] [INFO] [paperless.management.consumer] Adding /usr/src/paperless/consume/R552238842.pdf to the task queue.
webserver-1  | [2024-11-01 17:24:01,302] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[7595b6a2-cab5-48cb-b534-be0e9c205da6] received
webserver-1  | [2024-11-01 17:24:03,834] [INFO] [ocrmypdf._pipeline] skipping all processing on this page
webserver-1  | [2024-11-01 17:24:03,841] [INFO] [ocrmypdf._pipelines.ocr] Postprocessing...
webserver-1  | [2024-11-01 17:24:05,365] [INFO] [ocrmypdf._pipeline] Image optimization ratio: 1.07 savings: 7.0%
webserver-1  | [2024-11-01 17:24:05,368] [INFO] [ocrmypdf._pipeline] Total file size ratio: 0.97 savings: -3.5%
webserver-1  | [2024-11-01 17:24:05,374] [WARNING] [ocrmypdf._pipelines._common] Output file is a valid PDF, but conversion to PDF/A did not succeed (issue: No PDF/A metadata in XMP)
webserver-1  | [2024-11-01 17:24:05,456] [INFO] [paperless.parsing.tesseract] pdftotext exited 0
webserver-1  | [2024-11-01 17:24:07,027] [INFO] [paperless.parsing] convert exited 0
webserver-1  | [2024-11-01 17:24:18,657] [INFO] [paperless.handlers] Assigning correspondent <redacted>
webserver-1  | [2024-11-01 17:24:18,666] [INFO] [paperless.handlers] Assigning document type <redacted>
webserver-1  | [2024-11-01 17:24:19,681] [INFO] [paperless.matching] Document matched WorkflowTrigger 4 from Workflow: Default assignments for new documents
webserver-1  | [2024-11-01 17:24:19,682] [INFO] [paperless.handlers] Applying WorkflowAction 4 from Workflow: Default assignments for new documents
webserver-1  | [2024-11-01 17:24:19,765] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,779] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,784] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,788] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,800] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,806] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,811] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,826] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,831] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,836] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,872] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,876] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,882] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,887] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,904] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,917] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,934] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,944] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,957] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,961] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,966] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,971] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,987] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,991] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,995] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:19,998] [INFO] [paperless.matching] Document did not match Workflow: <redacted>
webserver-1  | [2024-11-01 17:24:20,207] [INFO] [paperless.consumer] Document <redacted> R552238842 consumption finished
webserver-1  | [2024-11-01 17:24:20,227] [INFO] [paperless.tasks] ConsumeTaskPlugin completed with: Success. New document id 7483 created
webserver-1  | [2024-11-01 17:24:20,235] [INFO] [celery.app.trace] Task documents.tasks.consume_file[df1ff5bb-d0c4-4da1-8c5a-99608003c89a] succeeded in 24.750320405932143s: 'Success. New document id 7483 created'
webserver-1  | [2024-11-01 17:24:20,624] [WARNING] [paperless.barcodes] Exception during barcode scanning: [Errno 2] No such file or directory: '/usr/src/paperless/consume/R552238842.pdf'
webserver-1  | [2024-11-01 17:24:20,624] [WARNING] [paperless.barcodes] Exception during barcode scanning: [Errno 2] No such file or directory: '/usr/src/paperless/consume/R552238842.pdf'
webserver-1  | [2024-11-01 17:24:20,625] [INFO] [paperless.tasks] BarcodePlugin completed with no message
webserver-1  | [2024-11-01 17:24:20,631] [INFO] [paperless.tasks] WorkflowTriggerPlugin completed with:
webserver-1  | [2024-11-01 17:24:20,651] [ERROR] [paperless.consumer] Cannot consume /usr/src/paperless/consume/R552238842.pdf: File not found.
webserver-1  | [2024-11-01 17:24:20,658] [ERROR] [paperless.tasks] ConsumeTaskPlugin failed: R552238842.pdf: Cannot consume /usr/src/paperless/consume/R552238842.pdf: File not found.
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 148, in consume_file
webserver-1  |     msg = plugin.run()
webserver-1  |           ^^^^^^^^^^^^
webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 368, in run
webserver-1  |     self.pre_check_file_exists()
webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 158, in pre_check_file_exists
webserver-1  |     self._fail(
webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail
webserver-1  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
webserver-1  | documents.consumer.ConsumerError: R552238842.pdf: Cannot consume /usr/src/paperless/consume/R552238842.pdf: File not found.
webserver-1  | [2024-11-01 17:24:20,810] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[7595b6a2-cab5-48cb-b534-be0e9c205da6] raised unexpected: ConsumerError('R552238842.pdf: Cannot consume /usr/src/paperless/consume/R552238842.pdf: File not found.')
webserver-1  | Traceback (most recent call last):
webserver-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
webserver-1  |     R = retval = fun(*args, **kwargs)
webserver-1  |                  ^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
webserver-1  |     return self.run(*args, **kwargs)
webserver-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
webserver-1  |   File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap
webserver-1  |     raise exc_info[1]
webserver-1  |   File "/usr/src/paperless/src/documents/tasks.py", line 148, in consume_file
webserver-1  |     msg = plugin.run()
webserver-1  |           ^^^^^^^^^^^^
webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 368, in run
webserver-1  |     self.pre_check_file_exists()
webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 158, in pre_check_file_exists
webserver-1  |     self._fail(
webserver-1  |   File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail
webserver-1  |     raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
webserver-1  | documents.consumer.ConsumerError: R552238842.pdf: Cannot consume /usr/src/paperless/consume/R552238842.pdf: File not found.
```

Final outcome:
- The document was imported to paperless apparently ok.
- The file consumed and isn't present in the import directory anymore.
- The "File Task" page shows a new "Failed" entry.

**Comment by shamoon** [comment] 2024-11-01 17:02
Importing files from a directory over a network share is generally not supported / not a good idea. Unsure if that was OPs problem

**Comment by shamoon** [comment] 2024-11-01 17:04
At the very least if you’re doing it that way consider using polling instead of Inotify. The logs suggest the file was detected twice which isn’t something we particularly control (especially with inotify)

**Comment by jdelker** [comment] 2024-11-01 23:04
> Importing files from a directory over a network share is generally not supported / not a good idea.

Just to be sure, we have no misunderstanding:
The import directory **is not** mounted as a network share from a remote server. It's a local host directory for paperless, just bind mounted into the container.
But other remote clients accessing this host directory via SMB to deploy files there for paperless to consume.

I'll try what polling will have for an effect...

**Comment by horvatkm** [comment] 2024-11-02 10:05
Paperless consumer should IMHO check, if the file has already been already queued and not add it to the queue, if it's already there. I've also noticed this issue, though not in this bug report.
