### ISSUE TITLE
[BUG] Lower part of sidebar disappears when increasing browser zoom 

### ISSUE THREAD

**Issue by DrJungArt** [paperless-ngx/paperless-ngx#7909] opened 2024-10-13 17:53 UTC
### Description

When increasing the zoom in the browser the lower part of the sidebar dissaperas.
![image](https://github.com/user-attachments/assets/d956259f-d421-4f5e-b32a-052a6671e15a)

### Steps to reproduce

set zoom to a lower scale

### Webserver logs

```bash
n/a
```

### Browser logs

```bash
n/a
```

### Paperless-ngx version

2.12.1

### Host OS

x86_64

### Installation method

Docker - official image

### System status

```json
n/a
```

### Browser

Chrome

### Configuration changes

custom titel and custom logo

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-10-13 17:54
If you're saying the issue is scrolling when you do that, this has been reported about a zillion times and is already fixed in our next release. Please search first in the future.

**Closed by shamoon** 2024-10-13 17:54 UTC
Labels: bug, unconfirmed

**Comment by DrJungArt** [comment] 2024-10-13 17:57
ups - your're right - thank you for the reply and sorry for your time. your're making a great product.
