### ISSUE TITLE
[BUG] document_renamer dates in filename off by one day

### ISSUE THREAD

**Issue by Vedeneb** [paperless-ngx/paperless-ngx#926] opened 2022-05-11 20:23 UTC
### Description

After running the `document_renamer`, all dates in the filename are off by one day. E.g. a document with the date 11.05.2022 will have 10.05.2022 in the filename after running the exporter.

This is related to #267, however since the original issue was regarding the `document_exporter` which seems to be fixed in the new version v1.7.1, I decided to open a new issue.

### Steps to reproduce

1. (Since this is probably a time zone issue: Set Timezone to Europe/Berlin)
2. Set `PAPERLESS_FILENAME_FORMAT` to something that contains `{created_day}`
3. Modify some details of the document (e.g. the tile) using the web ui
4. The filename of the pdf will contain the correct document day
5. Now run the `document_renamer`
6. The document day in the file name will be off by one day

### Paperless-ngx version

1.7.1

### Host OS

x86_64

### Installation method

Docker

**Comment by stumpylog** [comment] 2022-05-12 02:30
If you use `{created}` as opposed to `{created_date}`, is the date correct then?

**Comment by Vedeneb** [comment] 2022-05-12 07:28
Nope, also `{created}` is off by one day.

Tested using the following filename format:
```
PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}/{document_type}/{created_year}{created_month}{created_day}_{created}_{correspondent}_{title}
```

Example result after running the `document_renamer` (document date is set to 14.02.2022):
![image](https://user-images.githubusercontent.com/39202639/168015092-43843c6f-5eea-45a7-a19f-b5a71b74f657.png)

After changing some doc properties using paperless it's correct again:
![image](https://user-images.githubusercontent.com/39202639/168015635-ff2cad2c-8ec5-4d9e-b4a2-894edcd03e52.png)

**Comment by stumpylog** [comment] 2022-05-12 14:52
I haven't been able to reproduce this with 1.7.1.

I've got the settings:
```
TZ: "Europe/Berlin"
PAPERLESS_TIME_ZONE: "Europe/Berlin"
PAPERLESS_FILENAME_FORMAT: "{created_year}{created_month}{created_day}_{created}_{correspondent}_{title}"
```

Document created is 14.02.2022.  That produces (in documents/originals) a filename of `20220214_2022-02-14...`.  After running the renamer, the filename is unchanged.  On export, the filename is also corrected.  

I have also tried shutting down and changing the format, then doing a rename.  The filename was updated to the new format, but the date was still correct.

`date` inside the container returns CEST, so the timezone has definitely taken effect.

**Comment by Vedeneb** [comment] 2022-05-12 17:35
I didn't know of the `TZ`-Env-variable - it wasn't set and indeed running `date` inside the container the timezone had not taken effect. 
However, even after setting `TZ` to `Europe/Berlin` as well, the dates after running the `document_renamer` are still off by one day...
The `date` command returns the correct date now though...

Here's my full `docker-compose.env` (comments removed and some private details replaced with xxx):
```
USERMAP_UID=1026
USERMAP_GID=100

PAPERLESS_SECRET_KEY=xxx

PAPERLESS_TIME_ZONE=Europe/Berlin
TZ=Europe/Berlin

PAPERLESS_OCR_LANGUAGE=deu

PAPERLESS_TRASH_DIR=/usr/src/paperless/trash
PAPERLESS_FILENAME_FORMAT={correspondent}/{created_year}/{document_type}/{created_year}{created_month}{created_day}_{created}_{correspondent}_{title}
PAPERLESS_CONSUMER_DELETE_DUPLICATES=true

PAPERLESS_IGNORE_DATES=xx.xx.xxxx

PAPERLESS_URL=http://paperless

PAPERLESS_CONSUMER_ENABLE_BARCODES=true
```

Let me know if there's anything else you need me to check or send you to help you find the error.

Thanks.

**Comment by stumpylog** [comment] 2022-05-12 17:49
TZ is a standard POSIX value (https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html), I tend to set it on all my containers, just is case.  In this case, I don't think it would matter, since django is using the PAPERLESS_TIME_ZONE as its setting.

**Comment by stumpylog** [comment] 2022-05-12 18:45
Even matching to exact format, timezone, and language, I can't get this to happen.

1. Start from a clean slate
2. Start the containers
3. Upload a document
4. Change the created date via the web ui to 01/01/2022
5. document is stored as `media\documents\originals\Test\2022\empty\20220101_2022-01-01_Test_blank-page.pdf`
6. `docker exec -it paperless-ngx-dev-webserver /bin/bash`
7. `document_renamer`
8. document is still `20220101_2022-01-01_none_blank-page.pdf`

**Comment by Vedeneb** [comment] 2022-05-12 19:09
So now things are getting strange. I just setup a second instance of paperless to do some more testing. I uploaded only two documents, one test-document (simple MS Word export) and an actual scan (the one I used as an example before).

The test document works fine! The date in the filename stays correct after running the renamer. The scan however has the same wrong behaviour I described before...

**Comment by Vedeneb** [comment] 2022-05-12 19:13
The dest-document is fine in my main instance of paperless as well, so this issue seems to be document specific for some reason... Let me see if I can find a problematic document I can send you.

**Comment by Vedeneb** [comment] 2022-05-12 19:38
Okay, I think I'm one step closer. It seems to happen only with documents, were the date initially was automatically recognized. Please try with the following pdf:
[Test with date.pdf](https://github.com/paperless-ngx/paperless-ngx/files/8682045/Test.with.date.pdf)

**Comment by stumpylog** [comment] 2022-05-12 21:05
Ok, there's certainly something going on between frontend and backend values here.  Maybe @shamoon can help me understand how the frontend handles dates.

When I put the document in first, I get the following values:

Creation date from parse_date: `2012-12-12 00:00:00+01:00`  (this is good, the date was located in the text)
Database: `2012-12-11 23:00:00 UTC`  (also makes sense, UTC is 2 hours behind Europe/Berlin
Filename: `20121212_2012-12-12...` (also good, this isn't UTC)
GET: `2012-12-12T00:00:00+01:00` (Seems good, converted UTC back to Europe/Berlin)
Displayed: `12/11/2012` (not so good, went back to UTC maybe?)

I then edit the date back to `12/12/2012`.

The sent payload has `created: "2012-12-12T23:00:00.000Z"`  (sent as UTC instead of local time?)

Database: `2012-12-12 23:00:00 UTC` (matches what the frontend sent)
GET: `created: "2012-12-13T00:00:00+01:00"` (database UTC converted to Europe/Berlin)
File name: `20121213_2012-12-13....`

Is the frontend also doing some amount of date conversions?  Which ends up de-timezoning the date?

**Comment by shamoon** [comment] 2022-05-12 21:16
I have been following along with these issues waiting to see if the frontend is involved in any way...

The front end does localize dates see https://github.com/paperless-ngx/paperless-ngx/blob/b034e972b031dff50c81964c8b98d14c899dee29/src-ui/src/app/pipes/custom-date.pipe.ts#L26 , the only recent changes to this was https://github.com/paperless-ngx/paperless-ngx/pull/654 which was designed to _retain_ TZ information which was being lost because the datepicker UI component has no awareness of time.

I will play with the example above when I have some time (tonight or tomorrow) and see if I can pin it down further. @stumpylog in the above is your frontend timezone set to Europe/Berlin to match the backend?

**Comment by stumpylog** [comment] 2022-05-12 21:19
Yes, this is with both TZ: "Europe/Berlin" and PAPERLESS_TIME_ZONE: "Europe/Berlin" in my environment

**Comment by shamoon** [comment] 2022-05-13 04:40
@stumpylog I think your frontend is using US dates, I think that because your frontend is showing `mm/dd/yyyy`, which is US format instead of German `dd.mm.yyyy`. If you change the frontend to use German (or system language as long as its set as such) it displays `11.12.2012`. In either case if I leave the date alone its unchanged in the DB (which suggests #654 works btw).

I think thats correct, no?

**Comment by stumpylog** [comment] 2022-05-13 14:54
I've changed the date display to German/medium, which is hopefully enough.  I still see `"2012-12-12T00:00:00+01:00"` coming back from the GET, then `11.12.2012`, which looks incorrect to me still.  Shouldn't it be `12.12.2012` still?

I do think I've also located something in the backend though, I'm looking into it further as well.

**Comment by shamoon** [comment] 2022-05-13 15:13
Oh you’re right (of course). Ok lemme look again. Also next time let’s choose a less confusing example haha

Dates!

**Comment by stumpylog** [comment] 2022-05-13 15:29
I know, dates are the most annoying thing.  Then add in timezones, it's even worse!

I've located the issue on the backend side anyway.  It looks like when a rename or export happens, the database time is used, so UTC timezone.  The fix would instead be localizing the date.

**Comment by shamoon** [comment] 2022-05-13 15:54
Yeah totally. That’s great. 

FYI, I think the frontend issue here is only happening if the locale is not the same as your system. It’s not such a common situation which is why I don’t think most people are seeing it and I don’t think it’s relevant to this bug. Obviously does need a fix, I’ll take care of that of course

**Comment by shamoon** [comment] 2022-05-13 17:25
Sheesh, this stuff gives me a headache, Im just gonna say this out loud and would appreciate some feedback.

Currently the frontend shows a date in your current timezone, regardless of the UTC offset of the date. It actually has never done anything differently than that. But isnt that what we want? Otherwise youre potentially viewing / editing dates in another timezone. Perhaps one issue is the timezone isnt shown so you'd have no way to realize this. Should we display the current timezone to make it explicit? See screenshot:
<img width="368" alt="Screen Shot 2022-05-13 at 10 15 26 AM" src="https://user-images.githubusercontent.com/4887959/168334818-371865ee-92a4-4a6c-bf2c-d245a7217f5e.png"> 
and here's a screenshot if I change the timezone of my machine (notice 12.12 😄):
<img width="376" alt="Screen Shot 2022-05-13 at 7 18 57 PM" src="https://user-images.githubusercontent.com/4887959/168335309-98996a8f-50ef-46fc-bb9a-e6bcccbaa10c.png">


The alternative would be to use the `PAPERLESS_TIME_ZONE` but that is currently not passed to the frontend in any way, so would have to implement that. **But the real question is would this be closer to "expected behavior"**, the frontend ignores the system timezone and uses whatever is set? I genuinely dont know what is the best choice / convention.

As a reminder, this issue is really only apparent when the user has `PAPERLESS_TIME_ZONE` set differently than their current system timezone. Still worth considering as people have their reasons, or when traveling, etc.

**Comment by Vedeneb** [comment] 2022-05-13 17:35
First of all, big thanks to both of you for all the time you put into trying to fix the issue.

> As a reminder, this issue is really only apparent when the user has PAPERLESS_TIME_ZONE set differently than their current system timezone.

I have set both `TZ` and `PAPERLESS_TIME_ZONE` to `Europe/Berlin`. Running `date` inside the container shows the correct local time. Still the issue is apparent.

Probably a stupid question: Why do we have to worry about Timezones at all for the created date? In the end it's only a date. Why store it with a time at all?

Oh and btw sorry for the stupid example, 12.12.2012 surely wasn't the best idea :grin:

**Comment by shamoon** [comment] 2022-05-13 17:35
Another thing to do would be to display the difference if there is one, see screenshots. Obviously the actual display / text would change but these are examples, presumably the second one wouldn't show anything.

<img width="377" alt="Screen Shot 2022-05-13 at 10 33 23 AM" src="https://user-images.githubusercontent.com/4887959/168337401-184535e3-4a5c-49a4-b916-e7cd084ac484.png">

<img width="378" alt="Screen Shot 2022-05-13 at 10 33 30 AM" src="https://user-images.githubusercontent.com/4887959/168337412-bfeab60e-53d6-42e7-a085-a06cab0426a9.png">

Maybe thats better?

**Comment by shamoon** [comment] 2022-05-13 17:37
> Probably a stupid question: Why do we have to worry about Timezones at all for the created date? In the end it's only a date. Why store it with a time at all?

Yea this has come up, in some ways that would solve a lot.

**Comment by shamoon** [comment] 2022-05-13 17:39
> I have set both `TZ` and `PAPERLESS_TIME_ZONE` to `Europe/Berlin`. Running `date` inside the container shows the correct local time. Still the issue is apparent.

Right, the frontend uses Javascript which pulls the timezone from your system so it doesnt use those settings at all. In your case though Im assuming your system is also on Europe/Berlin. As a reminder Im talking about the frontend issue stumpylog mentioned, not the date export thing, theyre probably not related.

**Comment by stumpylog** [comment] 2022-05-13 17:54
I kind of like the display of the timezone of the date, but I usually like more data in general.  I'd agree it's unlikely a user would be viewing dates from a different timezone, so there might not be any change to the frontend needed

**Comment by shamoon** [comment] 2022-05-13 17:58
So I guess a third option is to just have the frontend treat all dates as the current timezone, in other words discard the time / timezone. This would of course cause the database to change even if the date hasn't been edited, like you edit the document and hit save and the date in the database changes from whatever its original offset was to your current offset. Perhaps this is cleaner than all the timezone stuff since people aren't really using the time (or timezone).

Is that the best option?

(Sorry I've hijacked this thread)

**Comment by shamoon** [comment] 2022-05-17 04:48
Closed in branch by https://github.com/paperless-ngx/paperless-ngx/commit/347d7c07ef454ab884e7a3839d91a8e0d9e5cbc1

**Closed by shamoon** 2022-05-17 04:48 UTC
Labels: bug, backend
