### ISSUE TITLE
[BUG] Some e-mails not imported 

### ISSUE THREAD

**Issue by meifi** [paperless-ngx/paperless-ngx#8408] opened 2024-12-02 10:41 UTC
### Description

I created a mailbox for the email import. Let's take this is called documents@test.de. Several alias addresses are created for this mailfach, which apply to the individual import rules. e.g. documents_full@test.de and documents_onlyattachment@test.de.

Documents are only processed if they are forwarded to one of the alias addresses. 

At what characteristics does Paperless establish this?

### Steps to reproduce

This also works in most cases. However, I get a new document from someone, for example, where the subject of the email and the name of the document is the same, but the documents are not size, the email is not processed and fades in the import mailbox.

### Webserver logs

```bash
[2024-12-02 11: 20: 01.159] [Debug] [Paperless_Mail] Skipping Mail '22' Subject 'FWD: Document test' From 'Meifi@test.de', Already Processed.
```

### Paperless-ngx version

2.13.5

### Host OS

Docker

### Installation method

Docker - official image

### Please confirm the following

- [X] I believe this issue is a bug that affects all users of Paperless-ngx, not something specific to my installation.
- [X] This issue is not about the OCR or archive creation of a specific file(s). Otherwise, please see above regarding OCR tools.
- [X] I have already searched for relevant existing issues and discussions before opening this report.
- [X] I have updated the title field above with a concise description.

**Comment by shamoon** [comment] 2024-12-02 11:41
> Already Processed.

Paperless-ngx uses the message ID to identify messages, so either it has been checked already, or your mail server is incorrectly re-using IDs. Either way this is not a bug (here), so I'll close this.

If you'd like to re-process an email at the moment you would need to remove it from the admin area.

**Closed by shamoon** 2024-12-02 11:41 UTC
Labels: bug, unconfirmed
